// !!! DO NOT EDIT !!! -- automatically generated by scripts/assets.js

import alb from 'url:../../images/aws/alb.svg';
import alexaForBusiness from 'url:../../images/aws/alexa-for-business.svg';
import amplifyConsole from 'url:../../images/aws/amplify-console.svg';
import apacheMxnet from 'url:../../images/aws/apache-mxnet.svg';
import apiGateway from 'url:../../images/aws/api-gateway.svg';
import apiGatewayEndpoint from 'url:../../images/aws/api-gateway_endpoint.svg';
import appConfig from 'url:../../images/aws/app-config.svg';
import appMesh from 'url:../../images/aws/app-mesh.svg';
import appMeshMesh from 'url:../../images/aws/app-mesh_mesh.svg';
import appMeshVirtualGateway from 'url:../../images/aws/app-mesh_virtual-gateway.svg';
import appMeshVirtualNode from 'url:../../images/aws/app-mesh_virtual-node.svg';
import appMeshVirtualRouter from 'url:../../images/aws/app-mesh_virtual-router.svg';
import appMeshVirtualService from 'url:../../images/aws/app-mesh_virtual-service.svg';
import appStream from 'url:../../images/aws/app-stream.svg';
import appWizard from 'url:../../images/aws/app-wizard.svg';
import applicationAutoScaling from 'url:../../images/aws/application-auto-scaling.svg';
import applicationDiscoveryService from 'url:../../images/aws/application-discovery-service.svg';
import appsync from 'url:../../images/aws/appsync.svg';
import artifact from 'url:../../images/aws/artifact.svg';
import athena from 'url:../../images/aws/athena.svg';
import augmentedAiA2I from 'url:../../images/aws/augmented-ai-a2i.svg';
import aurora from 'url:../../images/aws/aurora.svg';
import auroraInstance from 'url:../../images/aws/aurora-instance.svg';
import auroraInstanceAlternate from 'url:../../images/aws/aurora-instance-alternate.svg';
import auroraMariadbInstance from 'url:../../images/aws/aurora-mariadb-instance.svg';
import auroraMariadbInstanceAlternate from 'url:../../images/aws/aurora-mariadb-instance-alternate.svg';
import auroraMysqlInstance from 'url:../../images/aws/aurora-mysql-instance.svg';
import auroraMysqlInstanceAlternate from 'url:../../images/aws/aurora-mysql-instance-alternate.svg';
import auroraOracleInstance from 'url:../../images/aws/aurora-oracle-instance.svg';
import auroraOracleInstanceAlternate from 'url:../../images/aws/aurora-oracle-instance-alternate.svg';
import auroraPiops from 'url:../../images/aws/aurora-piops.svg';
import auroraPostgresqlInstance from 'url:../../images/aws/aurora-postgresql-instance.svg';
import auroraPostgresqlInstanceAlternate from 'url:../../images/aws/aurora-postgresql-instance-alternate.svg';
import auroraSqlServerInstance from 'url:../../images/aws/aurora-sql-server-instance.svg';
import auroraSqlServerInstanceAlternate from 'url:../../images/aws/aurora-sql-server-instance-alternate.svg';
import autoScaling from 'url:../../images/aws/auto-scaling.svg';
import backintAgent from 'url:../../images/aws/backint-agent.svg';
import backup from 'url:../../images/aws/backup.svg';
import batch from 'url:../../images/aws/batch.svg';
import bottlerocket from 'url:../../images/aws/bottlerocket.svg';
import braket from 'url:../../images/aws/braket.svg';
import budgets from 'url:../../images/aws/budgets.svg';
import certificateManager from 'url:../../images/aws/certificate-manager.svg';
import certificateManagerCertificateAuthority from 'url:../../images/aws/certificate-manager_certificate-authority.svg';
import chatbot from 'url:../../images/aws/chatbot.svg';
import chime from 'url:../../images/aws/chime.svg';
import client from 'url:../../images/aws/client.svg';
import cloud9 from 'url:../../images/aws/cloud9.svg';
import cloudDevelopmentKit from 'url:../../images/aws/cloud-development-kit.svg';
import cloudDirectory from 'url:../../images/aws/cloud-directory.svg';
import cloudMapNamespace from 'url:../../images/aws/cloud-map_namespace.svg';
import cloudMapResource from 'url:../../images/aws/cloud-map_resource.svg';
import cloudMapService from 'url:../../images/aws/cloud-map_service.svg';
import cloudTrail from 'url:../../images/aws/cloud-trail.svg';
import cloudendureDisasterRecovery from 'url:../../images/aws/cloudendure-disaster-recovery.svg';
import cloudendureMigration from 'url:../../images/aws/cloudendure-migration.svg';
import cloudformation from 'url:../../images/aws/cloudformation.svg';
import cloudformationChangeSet from 'url:../../images/aws/cloudformation_change-set.svg';
import cloudformationStack from 'url:../../images/aws/cloudformation_stack.svg';
import cloudformationTemplate from 'url:../../images/aws/cloudformation_template.svg';
import cloudfront from 'url:../../images/aws/cloudfront.svg';
import cloudfrontDownloadDistribution from 'url:../../images/aws/cloudfront_download-distribution.svg';
import cloudfrontEdgeLocation from 'url:../../images/aws/cloudfront_edge-location.svg';
import cloudfrontStreamingDistribution from 'url:../../images/aws/cloudfront_streaming-distribution.svg';
import cloudhsm from 'url:../../images/aws/cloudhsm.svg';
import cloudmap from 'url:../../images/aws/cloudmap.svg';
import cloudsearch from 'url:../../images/aws/cloudsearch.svg';
import cloudsearchSearchDocuments from 'url:../../images/aws/cloudsearch_search-documents.svg';
import cloudwatch from 'url:../../images/aws/cloudwatch.svg';
import cloudwatchAlarm from 'url:../../images/aws/cloudwatch_alarm.svg';
import cloudwatchEventBased from 'url:../../images/aws/cloudwatch_event-based.svg';
import cloudwatchEventTimeBased from 'url:../../images/aws/cloudwatch_event-time-based.svg';
import cloudwatchLogs from 'url:../../images/aws/cloudwatch_logs.svg';
import cloudwatchRule from 'url:../../images/aws/cloudwatch_rule.svg';
import codeartifact from 'url:../../images/aws/codeartifact.svg';
import codebuild from 'url:../../images/aws/codebuild.svg';
import codecommit from 'url:../../images/aws/codecommit.svg';
import codedeploy from 'url:../../images/aws/codedeploy.svg';
import codeguru from 'url:../../images/aws/codeguru.svg';
import codepipeline from 'url:../../images/aws/codepipeline.svg';
import codestar from 'url:../../images/aws/codestar.svg';
import cognito from 'url:../../images/aws/cognito.svg';
import commandLineInterface from 'url:../../images/aws/command-line-interface.svg';
import comprehend from 'url:../../images/aws/comprehend.svg';
import computeOptimizer from 'url:../../images/aws/compute-optimizer.svg';
import config from 'url:../../images/aws/config.svg';
import connect from 'url:../../images/aws/connect.svg';
import consoleMobileApplication from 'url:../../images/aws/console-mobile-application.svg';
import controlTower from 'url:../../images/aws/control-tower.svg';
import costAndUsageReport from 'url:../../images/aws/cost-and-usage-report.svg';
import costExplorer from 'url:../../images/aws/cost-explorer.svg';
import dataExchange from 'url:../../images/aws/data-exchange.svg';
import dataPipeline from 'url:../../images/aws/data-pipeline.svg';
import dataSync from 'url:../../images/aws/data-sync.svg';
import databaseAmazonRdsProxy from 'url:../../images/aws/database_amazon-rds-proxy.svg';
import databaseAmazonRdsProxyAlternate from 'url:../../images/aws/database_amazon-rds-proxy-alternate.svg';
import databaseMigration from 'url:../../images/aws/database-migration.svg';
import databaseMigrationWorkflowJob from 'url:../../images/aws/database-migration-workflow-job.svg';
import datasyncAgent from 'url:../../images/aws/datasync_agent.svg';
import deepComposer from 'url:../../images/aws/deep-composer.svg';
import deepLearningAmis from 'url:../../images/aws/deep-learning-amis.svg';
import deepLearningContainers from 'url:../../images/aws/deep-learning-containers.svg';
import deepLens from 'url:../../images/aws/deep-lens.svg';
import deepracer from 'url:../../images/aws/deepracer.svg';
import detective from 'url:../../images/aws/detective.svg';
import deviceFarm from 'url:../../images/aws/device-farm.svg';
import directConnect from 'url:../../images/aws/direct-connect.svg';
import directConnectGateway from 'url:../../images/aws/direct-connect_gateway.svg';
import directoryService from 'url:../../images/aws/directory-service.svg';
import directoryServiceAdConnector from 'url:../../images/aws/directory-service_ad-connector.svg';
import directoryServiceAwsManagedMicrosoftAd from 'url:../../images/aws/directory-service_aws-managed-microsoft-ad.svg';
import directoryServiceSimpleAd from 'url:../../images/aws/directory-service_simple-ad.svg';
import disk from 'url:../../images/aws/disk.svg';
import documentdb from 'url:../../images/aws/documentdb.svg';
import dynamodb from 'url:../../images/aws/dynamodb.svg';
import dynamodbAmazonDynamodbAccelerator from 'url:../../images/aws/dynamodb_amazon-dynamodb-accelerator.svg';
import dynamodbAttribute from 'url:../../images/aws/dynamodb_attribute.svg';
import dynamodbAttributes from 'url:../../images/aws/dynamodb_attributes.svg';
import dynamodbGlobalSecondaryIndex from 'url:../../images/aws/dynamodb_global-secondary-index.svg';
import dynamodbItem from 'url:../../images/aws/dynamodb_item.svg';
import dynamodbItems from 'url:../../images/aws/dynamodb_items.svg';
import dynamodbTable from 'url:../../images/aws/dynamodb_table.svg';
import ebs from 'url:../../images/aws/ebs.svg';
import ebsMultipleVolumes from 'url:../../images/aws/ebs_multiple-volumes.svg';
import ebsSnapshot from 'url:../../images/aws/ebs_snapshot.svg';
import ebsVolume from 'url:../../images/aws/ebs_volume.svg';
import ec2 from 'url:../../images/aws/ec2.svg';
import ec2A1Instance from 'url:../../images/aws/ec2_a1-instance.svg';
import ec2AmiResource from 'url:../../images/aws/ec2_ami_resource.svg';
import ec2AutoScaling from 'url:../../images/aws/ec2_auto-scaling.svg';
import ec2AwsInferentia from 'url:../../images/aws/ec2_aws-inferentia.svg';
import ec2C4Instance from 'url:../../images/aws/ec2_c4-instance.svg';
import ec2C5Instance from 'url:../../images/aws/ec2_c5-instance.svg';
import ec2C5NInstance from 'url:../../images/aws/ec2_c5n-instance.svg';
import ec2C6GInstance from 'url:../../images/aws/ec2_c6g-instance.svg';
import ec2D2Instance from 'url:../../images/aws/ec2_d2-instance.svg';
import ec2DbInstance from 'url:../../images/aws/ec2_db-instance.svg';
import ec2ElasticIpAddress from 'url:../../images/aws/ec2_elastic-ip-address.svg';
import ec2F1Instance from 'url:../../images/aws/ec2_f1-instance.svg';
import ec2G3Instance from 'url:../../images/aws/ec2_g3-instance.svg';
import ec2H1Instance from 'url:../../images/aws/ec2_h1-instance.svg';
import ec2HmiInstance from 'url:../../images/aws/ec2_hmi-instance.svg';
import ec2I3Instance from 'url:../../images/aws/ec2_i3-instance.svg';
import ec2ImageBuilder from 'url:../../images/aws/ec2-image-builder.svg';
import ec2Instance from 'url:../../images/aws/ec2_instance.svg';
import ec2InstanceWithCloudwatch from 'url:../../images/aws/ec2_instance-with-cloudwatch.svg';
import ec2Instances from 'url:../../images/aws/ec2_instances.svg';
import ec2M4Instance from 'url:../../images/aws/ec2_m4-instance.svg';
import ec2M5AInstance from 'url:../../images/aws/ec2_m5a-instance.svg';
import ec2M5Instance from 'url:../../images/aws/ec2_m5-instance.svg';
import ec2M5N from 'url:../../images/aws/ec2-m5n.svg';
import ec2M5NInstance from 'url:../../images/aws/ec2_m5n-instance.svg';
import ec2M6GInstance from 'url:../../images/aws/ec2_m6g-instance.svg';
import ec2P2Instance from 'url:../../images/aws/ec2_p2-instance.svg';
import ec2P3Instance from 'url:../../images/aws/ec2_p3-instance.svg';
import ec2R4Instance from 'url:../../images/aws/ec2_r4-instance.svg';
import ec2R5AInstance from 'url:../../images/aws/ec2_r5a-instance.svg';
import ec2R5Instance from 'url:../../images/aws/ec2_r5-instance.svg';
import ec2R5N from 'url:../../images/aws/ec2-r5n.svg';
import ec2R5NInstance from 'url:../../images/aws/ec2_r5n-instance.svg';
import ec2R6GInstance from 'url:../../images/aws/ec2_r6g-instance.svg';
import ec2Rescue from 'url:../../images/aws/ec2_rescue.svg';
import ec2SpotInstance from 'url:../../images/aws/ec2_spot-instance.svg';
import ec2T2Instance from 'url:../../images/aws/ec2_t2-instance.svg';
import ec2T3Instance from 'url:../../images/aws/ec2_t3-instance.svg';
import ec2X1EInstance from 'url:../../images/aws/ec2_x1e-instance.svg';
import ec2X1Instance from 'url:../../images/aws/ec2_x1-instance.svg';
import ec2Z1DInstance from 'url:../../images/aws/ec2_z1d-instance.svg';
import ecr from 'url:../../images/aws/ecr.svg';
import ecrImage from 'url:../../images/aws/ecr_image.svg';
import ecrRegistry from 'url:../../images/aws/ecr_registry.svg';
import ecs from 'url:../../images/aws/ecs.svg';
import ecsContainer1 from 'url:../../images/aws/ecs_container-1.svg';
import ecsContainer2 from 'url:../../images/aws/ecs_container-2.svg';
import ecsContainer3 from 'url:../../images/aws/ecs_container-3.svg';
import ecsService from 'url:../../images/aws/ecs_service.svg';
import ecsTask from 'url:../../images/aws/ecs_task.svg';
import efs from 'url:../../images/aws/efs.svg';
import efsFileSystem from 'url:../../images/aws/efs_file-system.svg';
import elasticBeanstalk from 'url:../../images/aws/elastic-beanstalk.svg';
import elasticBeanstalkApplication from 'url:../../images/aws/elastic-beanstalk_application.svg';
import elasticBeanstalkDeployment from 'url:../../images/aws/elastic-beanstalk_deployment.svg';
import elasticContainerKubernetes from 'url:../../images/aws/elastic-container-kubernetes.svg';
import elasticInference from 'url:../../images/aws/elastic-inference.svg';
import elasticTranscoder from 'url:../../images/aws/elastic-transcoder.svg';
import elasticache from 'url:../../images/aws/elasticache.svg';
import elasticacheCacheNode from 'url:../../images/aws/elasticache_cache-node.svg';
import elasticacheForMemcached from 'url:../../images/aws/elasticache-for-memcached.svg';
import elasticacheForRedis from 'url:../../images/aws/elasticache-for-redis.svg';
import elasticsearchService from 'url:../../images/aws/elasticsearch-service.svg';
import elb from 'url:../../images/aws/elb.svg';
import elbClassicLoadBalancer from 'url:../../images/aws/elb_classic-load-balancer.svg';
import elementalAppliancesAndSoftware from 'url:../../images/aws/elemental-appliances-and-software.svg';
import elementalLink from 'url:../../images/aws/elemental-link.svg';
import elementalMediaconnect from 'url:../../images/aws/elemental-mediaconnect.svg';
import elementalMediaconvert from 'url:../../images/aws/elemental-mediaconvert.svg';
import elementalMedialive from 'url:../../images/aws/elemental-medialive.svg';
import elementalMediapackage from 'url:../../images/aws/elemental-mediapackage.svg';
import elementalMediastore from 'url:../../images/aws/elemental-mediastore.svg';
import elementalMediatailor from 'url:../../images/aws/elemental-mediatailor.svg';
import email from 'url:../../images/aws/email.svg';
import emr from 'url:../../images/aws/emr.svg';
import emrCluster from 'url:../../images/aws/emr_cluster.svg';
import emrEngine from 'url:../../images/aws/emr-engine.svg';
import emrEngineMaprM3 from 'url:../../images/aws/emr-engine-mapr-m3.svg';
import emrEngineMaprM5 from 'url:../../images/aws/emr-engine-mapr-m5.svg';
import emrEngineMaprM7 from 'url:../../images/aws/emr-engine-mapr-m7.svg';
import emrHdfsCluster from 'url:../../images/aws/emr_hdfs-cluster.svg';
import eventbridge from 'url:../../images/aws/eventbridge.svg';
import eventbridgeCustomEventBus from 'url:../../images/aws/eventbridge_custom-event-bus.svg';
import eventbridgeDefaultEventBus from 'url:../../images/aws/eventbridge_default-event-bus.svg';
import eventbridgeEvent from 'url:../../images/aws/eventbridge-event.svg';
import eventbridgeRule from 'url:../../images/aws/eventbridge_rule.svg';
import eventbridgeSaasPartnerEvent from 'url:../../images/aws/eventbridge-saas-partner-event.svg';
import expressWorkflow from 'url:../../images/aws/express-workflow.svg';
import fargate from 'url:../../images/aws/fargate.svg';
import firewall from 'url:../../images/aws/firewall.svg';
import firewallManager from 'url:../../images/aws/firewall-manager.svg';
import forecast from 'url:../../images/aws/forecast.svg';
import forums from 'url:../../images/aws/forums.svg';
import fraudDetector from 'url:../../images/aws/fraud-detector.svg';
import freertos from 'url:../../images/aws/freertos.svg';
import fsx from 'url:../../images/aws/fsx.svg';
import fsxForLustre from 'url:../../images/aws/fsx-for-lustre.svg';
import fsxForWfs from 'url:../../images/aws/fsx-for-wfs.svg';
import gamelift from 'url:../../images/aws/gamelift.svg';
import general from 'url:../../images/aws/general.svg';
import generalAlternate from 'url:../../images/aws/general-alternate.svg';
import genericDatabase from 'url:../../images/aws/generic-database.svg';
import glacier from 'url:../../images/aws/glacier.svg';
import globalAccelerator from 'url:../../images/aws/global-accelerator.svg';
import glue from 'url:../../images/aws/glue.svg';
import glueCrawler from 'url:../../images/aws/glue_crawler.svg';
import glueDataCatalog from 'url:../../images/aws/glue_data-catalog.svg';
import groundStation from 'url:../../images/aws/ground-station.svg';
import guardduty from 'url:../../images/aws/guardduty.svg';
import iam from 'url:../../images/aws/iam.svg';
import iamAccessAnalyzer from 'url:../../images/aws/iam-access-analyzer.svg';
import iamAddOn from 'url:../../images/aws/iam_add-on.svg';
import iamDataEncryptionKey from 'url:../../images/aws/iam_data-encryption-key.svg';
import iamEncryptedData from 'url:../../images/aws/iam_encrypted-data.svg';
import iamLongTermSecurityCredential from 'url:../../images/aws/iam_long-term-security-credential.svg';
import iamMfaToken from 'url:../../images/aws/iam_mfa-token.svg';
import iamPermissions from 'url:../../images/aws/iam_permissions.svg';
import iamRole from 'url:../../images/aws/iam_role.svg';
import iamSts from 'url:../../images/aws/iam-sts.svg';
import iamStsAlternate from 'url:../../images/aws/iam-sts-alternate.svg';
import iamTemporarySecurityCredential from 'url:../../images/aws/iam_temporary-security-credential.svg';
import infrequentAccessStorageClass from 'url:../../images/aws/infrequent-access-storage-class.svg';
import inspector from 'url:../../images/aws/inspector.svg';
import inspectorAgent from 'url:../../images/aws/inspector_agent.svg';
import interactiveVideo from 'url:../../images/aws/interactive-video.svg';
import internetAlt1 from 'url:../../images/aws/internet-alt1.svg';
import internetAlt2 from 'url:../../images/aws/internet-alt2.svg';
import internetGateway from 'url:../../images/aws/internet-gateway.svg';
import iot1Click from 'url:../../images/aws/iot-1-click.svg';
import iotAction from 'url:../../images/aws/iot_action.svg';
import iotActuator from 'url:../../images/aws/iot_actuator.svg';
import iotAlexaEnabledDevice from 'url:../../images/aws/iot_alexa_enabled-device.svg';
import iotAlexaSkill from 'url:../../images/aws/iot_alexa_skill.svg';
import iotAlexaVoiceService from 'url:../../images/aws/iot_alexa_voice-service.svg';
import iotAnalytics from 'url:../../images/aws/iot-analytics.svg';
import iotAnalyticsChannel from 'url:../../images/aws/iot-analytics_channel.svg';
import iotAnalyticsDataSet from 'url:../../images/aws/iot-analytics_data-set.svg';
import iotAnalyticsDataStore from 'url:../../images/aws/iot-analytics_data-store.svg';
import iotAnalyticsNotebook from 'url:../../images/aws/iot-analytics_notebook.svg';
import iotAnalyticsPipeline from 'url:../../images/aws/iot-analytics_pipeline.svg';
import iotButton from 'url:../../images/aws/iot-button.svg';
import iotCertificate from 'url:../../images/aws/iot_certificate.svg';
import iotCore from 'url:../../images/aws/iot-core.svg';
import iotDesiredState from 'url:../../images/aws/iot_desired-state.svg';
import iotDeviceDefender from 'url:../../images/aws/iot-device-defender.svg';
import iotDeviceDefenderIotDeviceJobs from 'url:../../images/aws/iot-device-defender_iot-device-jobs.svg';
import iotDeviceGateway from 'url:../../images/aws/iot_device-gateway.svg';
import iotDeviceManagement from 'url:../../images/aws/iot-device-management.svg';
import iotEcho from 'url:../../images/aws/iot_echo.svg';
import iotEvents from 'url:../../images/aws/iot-events.svg';
import iotFireTv from 'url:../../images/aws/iot_fire_tv.svg';
import iotFireTvStick from 'url:../../images/aws/iot_fire-tv_stick.svg';
import iotGreengrassConnector from 'url:../../images/aws/iot_greengrass_connector.svg';
import iotGreengrassCore from 'url:../../images/aws/iot-greengrass-core.svg';
import iotHardwareBoard from 'url:../../images/aws/iot-hardware-board.svg';
import iotHttp2Protocol from 'url:../../images/aws/iot_http2-protocol.svg';
import iotHttpProtocol from 'url:../../images/aws/iot_http_protocol.svg';
import iotLambdaFunction from 'url:../../images/aws/iot_lambda_function.svg';
import iotMqttProtocol from 'url:../../images/aws/iot_mqtt_protocol.svg';
import iotOverAirUpdate from 'url:../../images/aws/iot_over-air-update.svg';
import iotPolicy from 'url:../../images/aws/iot_policy.svg';
import iotReportedState from 'url:../../images/aws/iot_reported-state.svg';
import iotRule from 'url:../../images/aws/iot-rule.svg';
import iotSensor from 'url:../../images/aws/iot_sensor.svg';
import iotServo from 'url:../../images/aws/iot_servo.svg';
import iotShadow from 'url:../../images/aws/iot_shadow.svg';
import iotSimulator from 'url:../../images/aws/iot_simulator.svg';
import iotSitewise from 'url:../../images/aws/iot-sitewise.svg';
import iotThingBank from 'url:../../images/aws/iot_thing_bank.svg';
import iotThingBicycle from 'url:../../images/aws/iot_thing_bicycle.svg';
import iotThingCamera from 'url:../../images/aws/iot_thing_camera.svg';
import iotThingCar from 'url:../../images/aws/iot_thing_car.svg';
import iotThingCart from 'url:../../images/aws/iot_thing_cart.svg';
import iotThingCoffeePot from 'url:../../images/aws/iot_thing_coffee-pot.svg';
import iotThingDoorLock from 'url:../../images/aws/iot_thing_door-lock.svg';
import iotThingFactory from 'url:../../images/aws/iot_thing_factory.svg';
import iotThingGeneric from 'url:../../images/aws/iot_thing_generic.svg';
import iotThingHouse from 'url:../../images/aws/iot_thing_house.svg';
import iotThingLightbulb from 'url:../../images/aws/iot_thing_lightbulb.svg';
import iotThingMedicalEmergency from 'url:../../images/aws/iot_thing_medical-emergency.svg';
import iotThingPoliceEmergency from 'url:../../images/aws/iot_thing_police-emergency.svg';
import iotThingThermostat from 'url:../../images/aws/iot_thing_thermostat.svg';
import iotThingTravel from 'url:../../images/aws/iot_thing_travel.svg';
import iotThingUtility from 'url:../../images/aws/iot_thing_utility.svg';
import iotThingWindfarm from 'url:../../images/aws/iot_thing_windfarm.svg';
import iotThingsGraph from 'url:../../images/aws/iot-things-graph.svg';
import iotTopic from 'url:../../images/aws/iot_topic.svg';
import iq from 'url:../../images/aws/iq.svg';
import kendra from 'url:../../images/aws/kendra.svg';
import keyManagementServices from 'url:../../images/aws/key-management-services.svg';
import keyspaces from 'url:../../images/aws/keyspaces.svg';
import kinesis from 'url:../../images/aws/kinesis.svg';
import kinesisDataAnalytics from 'url:../../images/aws/kinesis-data-analytics.svg';
import kinesisDataStreams from 'url:../../images/aws/kinesis-data-streams.svg';
import kinesisFirehose from 'url:../../images/aws/kinesis-firehose.svg';
import kinesisVideoStreams from 'url:../../images/aws/kinesis-video-streams.svg';
import lakeFormation from 'url:../../images/aws/lake-formation.svg';
import lakeFormationDataLake from 'url:../../images/aws/lake-formation_data-lake.svg';
import lambda from 'url:../../images/aws/lambda.svg';
import lambdaFunction from 'url:../../images/aws/lambda-function.svg';
import lex from 'url:../../images/aws/lex.svg';
import licenseManager from 'url:../../images/aws/license-manager.svg';
import lightsail from 'url:../../images/aws/lightsail.svg';
import localZones from 'url:../../images/aws/local-zones.svg';
import lumberyard from 'url:../../images/aws/lumberyard.svg';
import macie from 'url:../../images/aws/macie.svg';
import managedBlockchain from 'url:../../images/aws/managed-blockchain.svg';
import managedServices from 'url:../../images/aws/managed-services.svg';
import managedStreamingForKafka from 'url:../../images/aws/managed-streaming-for-kafka.svg';
import managementConsole from 'url:../../images/aws/management-console.svg';
import marketplace from 'url:../../images/aws/marketplace.svg';
import marketplaceAlternate from 'url:../../images/aws/marketplace-alternate.svg';
import migrationHub from 'url:../../images/aws/migration-hub.svg';
import mobileClient from 'url:../../images/aws/mobile-client.svg';
import mq from 'url:../../images/aws/mq.svg';
import multimedia from 'url:../../images/aws/multimedia.svg';
import neptune from 'url:../../images/aws/neptune.svg';
import neuronMlSdk from 'url:../../images/aws/neuron-ml-sdk.svg';
import nitroEnclaves from 'url:../../images/aws/nitro-enclaves.svg';
import nlb from 'url:../../images/aws/nlb.svg';
import officeBuilding from 'url:../../images/aws/office-building.svg';
import opsworks from 'url:../../images/aws/opsworks.svg';
import opsworksApps from 'url:../../images/aws/opsworks_apps.svg';
import opsworksDeployments from 'url:../../images/aws/opsworks_deployments.svg';
import opsworksInstances from 'url:../../images/aws/opsworks_instances.svg';
import opsworksLayers from 'url:../../images/aws/opsworks_layers.svg';
import opsworksMonitoring from 'url:../../images/aws/opsworks-monitoring.svg';
import opsworksPermissions from 'url:../../images/aws/opsworks_permissions.svg';
import opsworksResources from 'url:../../images/aws/opsworks_resources.svg';
import opsworksStack2 from 'url:../../images/aws/opsworks-stack2.svg';
import organizations from 'url:../../images/aws/organizations.svg';
import organizationsAccount from 'url:../../images/aws/organizations_account.svg';
import organizationsOrganizationalUnit from 'url:../../images/aws/organizations_organizational-unit.svg';
import outposts from 'url:../../images/aws/outposts.svg';
import parallelCluster from 'url:../../images/aws/parallel-cluster.svg';
import personalHealthDashboard from 'url:../../images/aws/personal-health-dashboard.svg';
import personalize from 'url:../../images/aws/personalize.svg';
import pinpoint from 'url:../../images/aws/pinpoint.svg';
import pinpointJourney from 'url:../../images/aws/pinpoint-journey.svg';
import polly from 'url:../../images/aws/polly.svg';
import privatelink from 'url:../../images/aws/privatelink.svg';
import professionalServices from 'url:../../images/aws/professional-services.svg';
import quantumLedgerDatabase from 'url:../../images/aws/quantum-ledger-database.svg';
import quicksight from 'url:../../images/aws/quicksight.svg';
import rds from 'url:../../images/aws/rds.svg';
import rdsForVmware from 'url:../../images/aws/rds-for-vmware.svg';
import rdsInstance from 'url:../../images/aws/rds-instance.svg';
import rdsInstanceAlternate from 'url:../../images/aws/rds-instance-alternate.svg';
import redshift from 'url:../../images/aws/redshift.svg';
import redshiftDenseComputeNode from 'url:../../images/aws/redshift_dense-compute-node.svg';
import redshiftDenseStorageNode from 'url:../../images/aws/redshift_dense-storage-node.svg';
import redshiftct from 'url:../../images/aws/redshiftct.svg';
import rekognition from 'url:../../images/aws/rekognition.svg';
import rekognitionImage from 'url:../../images/aws/rekognition_image.svg';
import rekognitionVideo from 'url:../../images/aws/rekognition_video.svg';
import reservedInstanceReporting from 'url:../../images/aws/reserved-instance-reporting.svg';
import resourcesAccessManager from 'url:../../images/aws/resources-access-manager.svg';
import robomaker from 'url:../../images/aws/robomaker.svg';
import robomakerCloudExtensionsRos from 'url:../../images/aws/robomaker_cloud-extensions-ros.svg';
import robomakerDevelopmentEnvironment from 'url:../../images/aws/robomaker_development-environment.svg';
import robomakerFleetManagement from 'url:../../images/aws/robomaker_fleet-management.svg';
import robomakerSimulation from 'url:../../images/aws/robomaker_simulation.svg';
import route53 from 'url:../../images/aws/route-53.svg';
import route53HostedZone from 'url:../../images/aws/route-53-hosted-zone.svg';
import route53RouteTable from 'url:../../images/aws/route-53_route-table.svg';
import s3 from 'url:../../images/aws/s3.svg';
import s3Bucket from 'url:../../images/aws/s3_bucket.svg';
import s3BucketWithObjects from 'url:../../images/aws/s3_bucket-with-objects.svg';
import s3GeneralAccessPoints from 'url:../../images/aws/s3_general-access-points.svg';
import s3Glacier from 'url:../../images/aws/s3-glacier.svg';
import s3GlacierArchive from 'url:../../images/aws/s3-glacier_archive.svg';
import s3GlacierDeepArchive from 'url:../../images/aws/s3-glacier-deep-archive.svg';
import s3GlacierVault from 'url:../../images/aws/s3-glacier_vault.svg';
import s3IntelligentTiering from 'url:../../images/aws/s3-intelligent-tiering.svg';
import s3Object from 'url:../../images/aws/s3_object.svg';
import s3OneZoneIa from 'url:../../images/aws/s3-one-zone-ia.svg';
import s3Replication from 'url:../../images/aws/s3-replication.svg';
import s3ReplicationTimeControl from 'url:../../images/aws/s3-replication-time-control.svg';
import s3StandardIa from 'url:../../images/aws/s3-standard-ia.svg';
import s3VpcAccessPoints from 'url:../../images/aws/s3_vpc-access-points.svg';
import sagemaker from 'url:../../images/aws/sagemaker.svg';
import sagemakerGroundTruth from 'url:../../images/aws/sagemaker-ground-truth.svg';
import sagemakerModel from 'url:../../images/aws/sagemaker_model.svg';
import sagemakerNotebook from 'url:../../images/aws/sagemaker_notebook.svg';
import sagemakerTrain from 'url:../../images/aws/sagemaker_train.svg';
import samlToken from 'url:../../images/aws/saml-token.svg';
import savingsPlans from 'url:../../images/aws/savings-plans.svg';
import sdk from 'url:../../images/aws/sdk.svg';
import secretsManager from 'url:../../images/aws/secrets-manager.svg';
import securityHub from 'url:../../images/aws/security-hub.svg';
import securityHubFinding from 'url:../../images/aws/security-hub_finding.svg';
import serverMigrationService from 'url:../../images/aws/server-migration-service.svg';
import serverlessApplicationRepository from 'url:../../images/aws/serverless-application-repository.svg';
import serviceCatalog from 'url:../../images/aws/service-catalog.svg';
import ses from 'url:../../images/aws/ses.svg';
import sesEmail from 'url:../../images/aws/ses_email.svg';
import shield from 'url:../../images/aws/shield.svg';
import shieldAdvanced from 'url:../../images/aws/shield-advanced.svg';
import singleSignOn from 'url:../../images/aws/single-sign-on.svg';
import siteToSiteVpn from 'url:../../images/aws/site-to-site-vpn.svg';
import snowball from 'url:../../images/aws/snowball.svg';
import snowballEdge from 'url:../../images/aws/snowball-edge.svg';
import snowballImportExport from 'url:../../images/aws/snowball-import-export.svg';
import snowcone from 'url:../../images/aws/snowcone.svg';
import snowmobile from 'url:../../images/aws/snowmobile.svg';
import sns from 'url:../../images/aws/sns.svg';
import snsEmailNotification from 'url:../../images/aws/sns_email-notification.svg';
import snsHttpNotification from 'url:../../images/aws/sns_http-notification.svg';
import snsTopic from 'url:../../images/aws/sns_topic.svg';
import sqs from 'url:../../images/aws/sqs.svg';
import sqsMessage from 'url:../../images/aws/sqs_message.svg';
import sqsQueue from 'url:../../images/aws/sqs_queue.svg';
import sslPadlock from 'url:../../images/aws/ssl-padlock.svg';
import standardStorageClass from 'url:../../images/aws/standard-storage-class.svg';
import stepFunctions from 'url:../../images/aws/step-functions.svg';
import storageGateway from 'url:../../images/aws/storage-gateway.svg';
import storageGatewayCachedVolume from 'url:../../images/aws/storage-gateway_cached-volume.svg';
import storageGatewayFileGateway from 'url:../../images/aws/storage-gateway_file-gateway.svg';
import storageGatewayNonCachedVolume from 'url:../../images/aws/storage-gateway_non-cached-volume.svg';
import storageGatewayTapeGateway from 'url:../../images/aws/storage-gateway_tape-gateway.svg';
import storageGatewayVirtualTapeLibrary from 'url:../../images/aws/storage-gateway_virtual-tape-library.svg';
import storageGatewayVolumeGateway from 'url:../../images/aws/storage-gateway_volume-gateway.svg';
import sumerian from 'url:../../images/aws/sumerian.svg';
import support from 'url:../../images/aws/support.svg';
import systemManagerAutomation from 'url:../../images/aws/system-manager_automation.svg';
import systemManagerDocuments from 'url:../../images/aws/system-manager_documents.svg';
import systemManagerInventory from 'url:../../images/aws/system-manager_inventory.svg';
import systemManagerMaintenanceWindows from 'url:../../images/aws/system-manager_maintenance-windows.svg';
import systemManagerOpscenter from 'url:../../images/aws/system-manager_opscenter.svg';
import systemManagerParameterStore from 'url:../../images/aws/system-manager_parameter-store.svg';
import systemManagerPatchManager from 'url:../../images/aws/system-manager_patch-manager.svg';
import systemManagerRunCommand from 'url:../../images/aws/system-manager_run-command.svg';
import systemManagerStateManager from 'url:../../images/aws/system-manager_state-manager.svg';
import systemsManager from 'url:../../images/aws/systems-manager.svg';
import tapeStorage from 'url:../../images/aws/tape-storage.svg';
import tensorflowOnAws from 'url:../../images/aws/tensorflow-on-aws.svg';
import textract from 'url:../../images/aws/textract.svg';
import thinkboxDeadline from 'url:../../images/aws/thinkbox-deadline.svg';
import thinkboxFrost from 'url:../../images/aws/thinkbox-frost.svg';
import thinkboxKrakatoa from 'url:../../images/aws/thinkbox-krakatoa.svg';
import thinkboxSequoia from 'url:../../images/aws/thinkbox-sequoia.svg';
import thinkboxStoke from 'url:../../images/aws/thinkbox-stoke.svg';
import thinkboxXmesh from 'url:../../images/aws/thinkbox-xmesh.svg';
import timestream from 'url:../../images/aws/timestream.svg';
import toolkit from 'url:../../images/aws/toolkit.svg';
import toolsAndSdk from 'url:../../images/aws/tools-and-sdk.svg';
import torchserve from 'url:../../images/aws/torchserve.svg';
import traditionalServer from 'url:../../images/aws/traditional-server.svg';
import trainingCertification from 'url:../../images/aws/training-certification.svg';
import transcribe from 'url:../../images/aws/transcribe.svg';
import transferFamily from 'url:../../images/aws/transfer-family.svg';
import transferFamilyAwsFtp from 'url:../../images/aws/transfer-family_aws-ftp.svg';
import transferFamilyAwsFtps from 'url:../../images/aws/transfer-family_aws-ftps.svg';
import transferFamilyAwsSftp from 'url:../../images/aws/transfer-family_aws-sftp.svg';
import transitGateway from 'url:../../images/aws/transit-gateway.svg';
import translate from 'url:../../images/aws/translate.svg';
import trustedAdvisor from 'url:../../images/aws/trusted-advisor.svg';
import trustedAdvisorChecklist from 'url:../../images/aws/trusted-advisor_checklist.svg';
import trustedAdvisorChecklistCost from 'url:../../images/aws/trusted-advisor_checklist-cost.svg';
import trustedAdvisorChecklistFaultTolerant from 'url:../../images/aws/trusted-advisor_checklist-fault-tolerant.svg';
import trustedAdvisorChecklistPerformance from 'url:../../images/aws/trusted-advisor_checklist-performance.svg';
import trustedAdvisorChecklistSecurity from 'url:../../images/aws/trusted-advisor_checklist-security.svg';
import user from 'url:../../images/aws/user.svg';
import users from 'url:../../images/aws/users.svg';
import virtualPrivateCloud from 'url:../../images/aws/virtual-private-cloud.svg';
import vmwareCloudOnAws from 'url:../../images/aws/vmware-cloud-on-aws.svg';
import vpcCustomerGateway from 'url:../../images/aws/vpc_customer-gateway.svg';
import vpcElasticNetworkAdapter from 'url:../../images/aws/vpc_elastic-network-adapter.svg';
import vpcElasticNetworkInterface from 'url:../../images/aws/vpc_elastic-network-interface.svg';
import vpcEndpoints from 'url:../../images/aws/vpc_endpoints.svg';
import vpcFlowLogs from 'url:../../images/aws/vpc_flow-logs.svg';
import vpcInternetGateway from 'url:../../images/aws/vpc_internet-gateway.svg';
import vpcNatGateway from 'url:../../images/aws/vpc_nat-gateway.svg';
import vpcNetworkAccessControlList from 'url:../../images/aws/vpc_network-access-control-list.svg';
import vpcPeeringConnection from 'url:../../images/aws/vpc_peering-connection.svg';
import vpcRouter from 'url:../../images/aws/vpc_router.svg';
import vpcTrafficMirroring from 'url:../../images/aws/vpc_traffic-mirroring.svg';
import vpcVpnConnection from 'url:../../images/aws/vpc_vpn-connection.svg';
import vpcVpnGateway from 'url:../../images/aws/vpc_vpn-gateway.svg';
import vpn from 'url:../../images/aws/vpn.svg';
import waf from 'url:../../images/aws/waf.svg';
import wafFilteringRule from 'url:../../images/aws/waf_filtering-rule.svg';
import wavelength from 'url:../../images/aws/wavelength.svg';
import wellArchitectTool from 'url:../../images/aws/well-architect-tool.svg';
import workdocs from 'url:../../images/aws/workdocs.svg';
import worklink from 'url:../../images/aws/worklink.svg';
import workmail from 'url:../../images/aws/workmail.svg';
import workspaces from 'url:../../images/aws/workspaces.svg';
import xRay from 'url:../../images/aws/x-ray.svg';

export {
  alb,
  alexaForBusiness,
  amplifyConsole,
  apacheMxnet,
  apiGateway,
  apiGatewayEndpoint,
  appConfig,
  appMesh,
  appMeshMesh,
  appMeshVirtualGateway,
  appMeshVirtualNode,
  appMeshVirtualRouter,
  appMeshVirtualService,
  appStream,
  appWizard,
  applicationAutoScaling,
  applicationDiscoveryService,
  appsync,
  artifact,
  athena,
  augmentedAiA2I,
  aurora,
  auroraInstance,
  auroraInstanceAlternate,
  auroraMariadbInstance,
  auroraMariadbInstanceAlternate,
  auroraMysqlInstance,
  auroraMysqlInstanceAlternate,
  auroraOracleInstance,
  auroraOracleInstanceAlternate,
  auroraPiops,
  auroraPostgresqlInstance,
  auroraPostgresqlInstanceAlternate,
  auroraSqlServerInstance,
  auroraSqlServerInstanceAlternate,
  autoScaling,
  backintAgent,
  backup,
  batch,
  bottlerocket,
  braket,
  budgets,
  certificateManager,
  certificateManagerCertificateAuthority,
  chatbot,
  chime,
  client,
  cloud9,
  cloudDevelopmentKit,
  cloudDirectory,
  cloudMapNamespace,
  cloudMapResource,
  cloudMapService,
  cloudTrail,
  cloudendureDisasterRecovery,
  cloudendureMigration,
  cloudformation,
  cloudformationChangeSet,
  cloudformationStack,
  cloudformationTemplate,
  cloudfront,
  cloudfrontDownloadDistribution,
  cloudfrontEdgeLocation,
  cloudfrontStreamingDistribution,
  cloudhsm,
  cloudmap,
  cloudsearch,
  cloudsearchSearchDocuments,
  cloudwatch,
  cloudwatchAlarm,
  cloudwatchEventBased,
  cloudwatchEventTimeBased,
  cloudwatchLogs,
  cloudwatchRule,
  codeartifact,
  codebuild,
  codecommit,
  codedeploy,
  codeguru,
  codepipeline,
  codestar,
  cognito,
  commandLineInterface,
  comprehend,
  computeOptimizer,
  config,
  connect,
  consoleMobileApplication,
  controlTower,
  costAndUsageReport,
  costExplorer,
  dataExchange,
  dataPipeline,
  dataSync,
  databaseAmazonRdsProxy,
  databaseAmazonRdsProxyAlternate,
  databaseMigration,
  databaseMigrationWorkflowJob,
  datasyncAgent,
  deepComposer,
  deepLearningAmis,
  deepLearningContainers,
  deepLens,
  deepracer,
  detective,
  deviceFarm,
  directConnect,
  directConnectGateway,
  directoryService,
  directoryServiceAdConnector,
  directoryServiceAwsManagedMicrosoftAd,
  directoryServiceSimpleAd,
  disk,
  documentdb,
  dynamodb,
  dynamodbAmazonDynamodbAccelerator,
  dynamodbAttribute,
  dynamodbAttributes,
  dynamodbGlobalSecondaryIndex,
  dynamodbItem,
  dynamodbItems,
  dynamodbTable,
  ebs,
  ebsMultipleVolumes,
  ebsSnapshot,
  ebsVolume,
  ec2,
  ec2A1Instance,
  ec2AmiResource,
  ec2AutoScaling,
  ec2AwsInferentia,
  ec2C4Instance,
  ec2C5Instance,
  ec2C5NInstance,
  ec2C6GInstance,
  ec2D2Instance,
  ec2DbInstance,
  ec2ElasticIpAddress,
  ec2F1Instance,
  ec2G3Instance,
  ec2H1Instance,
  ec2HmiInstance,
  ec2I3Instance,
  ec2ImageBuilder,
  ec2Instance,
  ec2InstanceWithCloudwatch,
  ec2Instances,
  ec2M4Instance,
  ec2M5AInstance,
  ec2M5Instance,
  ec2M5N,
  ec2M5NInstance,
  ec2M6GInstance,
  ec2P2Instance,
  ec2P3Instance,
  ec2R4Instance,
  ec2R5AInstance,
  ec2R5Instance,
  ec2R5N,
  ec2R5NInstance,
  ec2R6GInstance,
  ec2Rescue,
  ec2SpotInstance,
  ec2T2Instance,
  ec2T3Instance,
  ec2X1EInstance,
  ec2X1Instance,
  ec2Z1DInstance,
  ecr,
  ecrImage,
  ecrRegistry,
  ecs,
  ecsContainer1,
  ecsContainer2,
  ecsContainer3,
  ecsService,
  ecsTask,
  efs,
  efsFileSystem,
  elasticBeanstalk,
  elasticBeanstalkApplication,
  elasticBeanstalkDeployment,
  elasticContainerKubernetes,
  elasticInference,
  elasticTranscoder,
  elasticache,
  elasticacheCacheNode,
  elasticacheForMemcached,
  elasticacheForRedis,
  elasticsearchService,
  elb,
  elbClassicLoadBalancer,
  elementalAppliancesAndSoftware,
  elementalLink,
  elementalMediaconnect,
  elementalMediaconvert,
  elementalMedialive,
  elementalMediapackage,
  elementalMediastore,
  elementalMediatailor,
  email,
  emr,
  emrCluster,
  emrEngine,
  emrEngineMaprM3,
  emrEngineMaprM5,
  emrEngineMaprM7,
  emrHdfsCluster,
  eventbridge,
  eventbridgeCustomEventBus,
  eventbridgeDefaultEventBus,
  eventbridgeEvent,
  eventbridgeRule,
  eventbridgeSaasPartnerEvent,
  expressWorkflow,
  fargate,
  firewall,
  firewallManager,
  forecast,
  forums,
  fraudDetector,
  freertos,
  fsx,
  fsxForLustre,
  fsxForWfs,
  gamelift,
  general,
  generalAlternate,
  genericDatabase,
  glacier,
  globalAccelerator,
  glue,
  glueCrawler,
  glueDataCatalog,
  groundStation,
  guardduty,
  iam,
  iamAccessAnalyzer,
  iamAddOn,
  iamDataEncryptionKey,
  iamEncryptedData,
  iamLongTermSecurityCredential,
  iamMfaToken,
  iamPermissions,
  iamRole,
  iamSts,
  iamStsAlternate,
  iamTemporarySecurityCredential,
  infrequentAccessStorageClass,
  inspector,
  inspectorAgent,
  interactiveVideo,
  internetAlt1,
  internetAlt2,
  internetGateway,
  iot1Click,
  iotAction,
  iotActuator,
  iotAlexaEnabledDevice,
  iotAlexaSkill,
  iotAlexaVoiceService,
  iotAnalytics,
  iotAnalyticsChannel,
  iotAnalyticsDataSet,
  iotAnalyticsDataStore,
  iotAnalyticsNotebook,
  iotAnalyticsPipeline,
  iotButton,
  iotCertificate,
  iotCore,
  iotDesiredState,
  iotDeviceDefender,
  iotDeviceDefenderIotDeviceJobs,
  iotDeviceGateway,
  iotDeviceManagement,
  iotEcho,
  iotEvents,
  iotFireTv,
  iotFireTvStick,
  iotGreengrassConnector,
  iotGreengrassCore,
  iotHardwareBoard,
  iotHttp2Protocol,
  iotHttpProtocol,
  iotLambdaFunction,
  iotMqttProtocol,
  iotOverAirUpdate,
  iotPolicy,
  iotReportedState,
  iotRule,
  iotSensor,
  iotServo,
  iotShadow,
  iotSimulator,
  iotSitewise,
  iotThingBank,
  iotThingBicycle,
  iotThingCamera,
  iotThingCar,
  iotThingCart,
  iotThingCoffeePot,
  iotThingDoorLock,
  iotThingFactory,
  iotThingGeneric,
  iotThingHouse,
  iotThingLightbulb,
  iotThingMedicalEmergency,
  iotThingPoliceEmergency,
  iotThingThermostat,
  iotThingTravel,
  iotThingUtility,
  iotThingWindfarm,
  iotThingsGraph,
  iotTopic,
  iq,
  kendra,
  keyManagementServices,
  keyspaces,
  kinesis,
  kinesisDataAnalytics,
  kinesisDataStreams,
  kinesisFirehose,
  kinesisVideoStreams,
  lakeFormation,
  lakeFormationDataLake,
  lambda,
  lambdaFunction,
  lex,
  licenseManager,
  lightsail,
  localZones,
  lumberyard,
  macie,
  managedBlockchain,
  managedServices,
  managedStreamingForKafka,
  managementConsole,
  marketplace,
  marketplaceAlternate,
  migrationHub,
  mobileClient,
  mq,
  multimedia,
  neptune,
  neuronMlSdk,
  nitroEnclaves,
  nlb,
  officeBuilding,
  opsworks,
  opsworksApps,
  opsworksDeployments,
  opsworksInstances,
  opsworksLayers,
  opsworksMonitoring,
  opsworksPermissions,
  opsworksResources,
  opsworksStack2,
  organizations,
  organizationsAccount,
  organizationsOrganizationalUnit,
  outposts,
  parallelCluster,
  personalHealthDashboard,
  personalize,
  pinpoint,
  pinpointJourney,
  polly,
  privatelink,
  professionalServices,
  quantumLedgerDatabase,
  quicksight,
  rds,
  rdsForVmware,
  rdsInstance,
  rdsInstanceAlternate,
  redshift,
  redshiftDenseComputeNode,
  redshiftDenseStorageNode,
  redshiftct,
  rekognition,
  rekognitionImage,
  rekognitionVideo,
  reservedInstanceReporting,
  resourcesAccessManager,
  robomaker,
  robomakerCloudExtensionsRos,
  robomakerDevelopmentEnvironment,
  robomakerFleetManagement,
  robomakerSimulation,
  route53,
  route53HostedZone,
  route53RouteTable,
  s3,
  s3Bucket,
  s3BucketWithObjects,
  s3GeneralAccessPoints,
  s3Glacier,
  s3GlacierArchive,
  s3GlacierDeepArchive,
  s3GlacierVault,
  s3IntelligentTiering,
  s3Object,
  s3OneZoneIa,
  s3Replication,
  s3ReplicationTimeControl,
  s3StandardIa,
  s3VpcAccessPoints,
  sagemaker,
  sagemakerGroundTruth,
  sagemakerModel,
  sagemakerNotebook,
  sagemakerTrain,
  samlToken,
  savingsPlans,
  sdk,
  secretsManager,
  securityHub,
  securityHubFinding,
  serverMigrationService,
  serverlessApplicationRepository,
  serviceCatalog,
  ses,
  sesEmail,
  shield,
  shieldAdvanced,
  singleSignOn,
  siteToSiteVpn,
  snowball,
  snowballEdge,
  snowballImportExport,
  snowcone,
  snowmobile,
  sns,
  snsEmailNotification,
  snsHttpNotification,
  snsTopic,
  sqs,
  sqsMessage,
  sqsQueue,
  sslPadlock,
  standardStorageClass,
  stepFunctions,
  storageGateway,
  storageGatewayCachedVolume,
  storageGatewayFileGateway,
  storageGatewayNonCachedVolume,
  storageGatewayTapeGateway,
  storageGatewayVirtualTapeLibrary,
  storageGatewayVolumeGateway,
  sumerian,
  support,
  systemManagerAutomation,
  systemManagerDocuments,
  systemManagerInventory,
  systemManagerMaintenanceWindows,
  systemManagerOpscenter,
  systemManagerParameterStore,
  systemManagerPatchManager,
  systemManagerRunCommand,
  systemManagerStateManager,
  systemsManager,
  tapeStorage,
  tensorflowOnAws,
  textract,
  thinkboxDeadline,
  thinkboxFrost,
  thinkboxKrakatoa,
  thinkboxSequoia,
  thinkboxStoke,
  thinkboxXmesh,
  timestream,
  toolkit,
  toolsAndSdk,
  torchserve,
  traditionalServer,
  trainingCertification,
  transcribe,
  transferFamily,
  transferFamilyAwsFtp,
  transferFamilyAwsFtps,
  transferFamilyAwsSftp,
  transitGateway,
  translate,
  trustedAdvisor,
  trustedAdvisorChecklist,
  trustedAdvisorChecklistCost,
  trustedAdvisorChecklistFaultTolerant,
  trustedAdvisorChecklistPerformance,
  trustedAdvisorChecklistSecurity,
  user,
  users,
  virtualPrivateCloud,
  vmwareCloudOnAws,
  vpcCustomerGateway,
  vpcElasticNetworkAdapter,
  vpcElasticNetworkInterface,
  vpcEndpoints,
  vpcFlowLogs,
  vpcInternetGateway,
  vpcNatGateway,
  vpcNetworkAccessControlList,
  vpcPeeringConnection,
  vpcRouter,
  vpcTrafficMirroring,
  vpcVpnConnection,
  vpcVpnGateway,
  vpn,
  waf,
  wafFilteringRule,
  wavelength,
  wellArchitectTool,
  workdocs,
  worklink,
  workmail,
  workspaces,
  xRay,
};
