// !!! DO NOT EDIT !!! -- automatically generated by scripts/assets.js

import absMember from 'url:../../images/azure/abs-member.svg';
import activeDirectory from 'url:../../images/azure/active-directory.svg';
import activeDirectoryConnectHealth from 'url:../../images/azure/active-directory-connect-health.svg';
import activityLog from 'url:../../images/azure/activity-log.svg';
import adB2C from 'url:../../images/azure/ad-b2c.svg';
import adDomainServices from 'url:../../images/azure/ad-domain-services.svg';
import adRolesAndAdministrators from 'url:../../images/azure/ad-roles-and-administrators.svg';
import advisor from 'url:../../images/azure/advisor.svg';
import alerts from 'url:../../images/azure/alerts.svg';
import allResources from 'url:../../images/azure/all-resources.svg';
import analysisServices from 'url:../../images/azure/analysis-services.svg';
import apiManagementServices from 'url:../../images/azure/api-management-services.svg';
import appRegistrations from 'url:../../images/azure/app-registrations.svg';
import appServiceCertificates from 'url:../../images/azure/app-service-certificates.svg';
import appServiceDomains from 'url:../../images/azure/app-service-domains.svg';
import appServiceEnvironments from 'url:../../images/azure/app-service-environments.svg';
import appServicePlans from 'url:../../images/azure/app-service-plans.svg';
import appServices from 'url:../../images/azure/app-services.svg';
import applicationInsights from 'url:../../images/azure/application-insights.svg';
import arc from 'url:../../images/azure/arc.svg';
import automationAccounts from 'url:../../images/azure/automation-accounts.svg';
import availabilitySets from 'url:../../images/azure/availability-sets.svg';
import avs from 'url:../../images/azure/avs.svg';
import backlog from 'url:../../images/azure/backlog.svg';
import batchAccounts from 'url:../../images/azure/batch-accounts.svg';
import bizTalk from 'url:../../images/azure/biz-talk.svg';
import blobBlock from 'url:../../images/azure/blob-block.svg';
import blobPage from 'url:../../images/azure/blob-page.svg';
import blockchainService from 'url:../../images/azure/blockchain-service.svg';
import blueprints from 'url:../../images/azure/blueprints.svg';
import botServices from 'url:../../images/azure/bot-services.svg';
import branch from 'url:../../images/azure/branch.svg';
import browser from 'url:../../images/azure/browser.svg';
import bug from 'url:../../images/azure/bug.svg';
import builds from 'url:../../images/azure/builds.svg';
import cache from 'url:../../images/azure/cache.svg';
import cacheRedis from 'url:../../images/azure/cache-redis.svg';
import capacity from 'url:../../images/azure/capacity.svg';
import cdnProfiles from 'url:../../images/azure/cdn-profiles.svg';
import cloudServicesClassic from 'url:../../images/azure/cloud-services-(classic).svg';
import code from 'url:../../images/azure/code.svg';
import cognitiveServices from 'url:../../images/azure/cognitive-services.svg';
import commit from 'url:../../images/azure/commit.svg';
import compliance from 'url:../../images/azure/compliance.svg';
import consortium from 'url:../../images/azure/consortium.svg';
import containerInstances from 'url:../../images/azure/container-instances.svg';
import containerRegistries from 'url:../../images/azure/container-registries.svg';
import containerServicesDeprecated from 'url:../../images/azure/container-services-(deprecated).svg';
import controls from 'url:../../images/azure/controls.svg';
import controlsHorizontal from 'url:../../images/azure/controls-horizontal.svg';
import cosmosDb from 'url:../../images/azure/cosmos-db.svg';
import costAlerts from 'url:../../images/azure/cost-alerts.svg';
import costAnalysis from 'url:../../images/azure/cost-analysis.svg';
import costBudgets from 'url:../../images/azure/cost-budgets.svg';
import costManagement from 'url:../../images/azure/cost-management.svg';
import counter from 'url:../../images/azure/counter.svg';
import cubes from 'url:../../images/azure/cubes.svg';
import dashboard from 'url:../../images/azure/dashboard.svg';
import dataBox from 'url:../../images/azure/data-box.svg';
import dataBoxEdge from 'url:../../images/azure/data-box-edge.svg';
import dataCatalog from 'url:../../images/azure/data-catalog.svg';
import dataExplorerClusters from 'url:../../images/azure/data-explorer-clusters.svg';
import dataFactory from 'url:../../images/azure/data-factory.svg';
import dataLakeStoreGen1 from 'url:../../images/azure/data-lake-store-gen1.svg';
import databaseMariadbServer from 'url:../../images/azure/database-mariadb-server.svg';
import databaseMigrationServices from 'url:../../images/azure/database-migration-services.svg';
import databaseMysqlServer from 'url:../../images/azure/database-mysql-server.svg';
import databasePostgresqlServer from 'url:../../images/azure/database-postgresql-server.svg';
import devConsole from 'url:../../images/azure/dev-console.svg';
import deviceProvisioningServices from 'url:../../images/azure/device-provisioning-services.svg';
import deviceSecurityApple from 'url:../../images/azure/device-security-apple.svg';
import deviceSecurityGoogle from 'url:../../images/azure/device-security-google.svg';
import deviceSecurityWindows from 'url:../../images/azure/device-security-windows.svg';
import devops from 'url:../../images/azure/devops.svg';
import devtestLabs from 'url:../../images/azure/devtest-labs.svg';
import diagnosticsSettings from 'url:../../images/azure/diagnostics-settings.svg';
import digitalTwins from 'url:../../images/azure/digital-twins.svg';
import diskEncryptionSets from 'url:../../images/azure/disk-encryption-sets.svg';
import disks from 'url:../../images/azure/disks.svg';
import disksClassic from 'url:../../images/azure/disks-(classic).svg';
import disksSnapshots from 'url:../../images/azure/disks-snapshots.svg';
import download from 'url:../../images/azure/download.svg';
import education from 'url:../../images/azure/education.svg';
import elasticJobAgents from 'url:../../images/azure/elastic-job-agents.svg';
import elixir from 'url:../../images/azure/elixir.svg';
import elixirPurple from 'url:../../images/azure/elixir-purple.svg';
import enterpriseApplications from 'url:../../images/azure/enterprise-applications.svg';
import error from 'url:../../images/azure/error.svg';
import eventGridDomains from 'url:../../images/azure/event-grid-domains.svg';
import eventGridSubscriptions from 'url:../../images/azure/event-grid-subscriptions.svg';
import eventGridTopics from 'url:../../images/azure/event-grid-topics.svg';
import eventHubClusters from 'url:../../images/azure/event-hub-clusters.svg';
import eventHubs from 'url:../../images/azure/event-hubs.svg';
import extensions from 'url:../../images/azure/extensions.svg';
import file from 'url:../../images/azure/file.svg';
import files from 'url:../../images/azure/files.svg';
import folderBlank from 'url:../../images/azure/folder-blank.svg';
import folderWebsite from 'url:../../images/azure/folder-website.svg';
import ftp from 'url:../../images/azure/ftp.svg';
import functionApps from 'url:../../images/azure/function-apps.svg';
import gear from 'url:../../images/azure/gear.svg';
import globe from 'url:../../images/azure/globe.svg';
import globeError from 'url:../../images/azure/globe-error.svg';
import globeSuccess from 'url:../../images/azure/globe-success.svg';
import globeWarning from 'url:../../images/azure/globe-warning.svg';
import groups from 'url:../../images/azure/groups.svg';
import guide from 'url:../../images/azure/guide.svg';
import hdInsightClusters from 'url:../../images/azure/hd-insight-clusters.svg';
import heart from 'url:../../images/azure/heart.svg';
import helpAndSupport from 'url:../../images/azure/help-and-support.svg';
import identityGovernance from 'url:../../images/azure/identity-governance.svg';
import image from 'url:../../images/azure/image.svg';
import imageDefinitions from 'url:../../images/azure/image-definitions.svg';
import imageVersions from 'url:../../images/azure/image-versions.svg';
import images from 'url:../../images/azure/images.svg';
import information from 'url:../../images/azure/information.svg';
import infrastructureBackup from 'url:../../images/azure/infrastructure-backup.svg';
import inputOutput from 'url:../../images/azure/input-output.svg';
import instancePools from 'url:../../images/azure/instance-pools.svg';
import integrationAccounts from 'url:../../images/azure/integration-accounts.svg';
import iotCentralApplications from 'url:../../images/azure/iot-central-applications.svg';
import iotHub from 'url:../../images/azure/iot-hub.svg';
import journeyHub from 'url:../../images/azure/journey-hub.svg';
import kubernetesServices from 'url:../../images/azure/kubernetes-services.svg';
import labServices from 'url:../../images/azure/lab-services.svg';
import launchPortal from 'url:../../images/azure/launch-portal.svg';
import learn from 'url:../../images/azure/learn.svg';
import lighthouse from 'url:../../images/azure/lighthouse.svg';
import loadTest from 'url:../../images/azure/load-test.svg';
import location from 'url:../../images/azure/location.svg';
import logAnalyticsWorkspaces from 'url:../../images/azure/log-analytics-workspaces.svg';
import logStreaming from 'url:../../images/azure/log-streaming.svg';
import logicApps from 'url:../../images/azure/logic-apps.svg';
import machinesAzureArc from 'url:../../images/azure/machines-azure-arc.svg';
import managedApplicationsCenter from 'url:../../images/azure/managed-applications-center.svg';
import managedDatabase from 'url:../../images/azure/managed-database.svg';
import managementGroups from 'url:../../images/azure/management-groups.svg';
import managementPortal from 'url:../../images/azure/management-portal.svg';
import mapsAccounts from 'url:../../images/azure/maps-accounts.svg';
import marketplace from 'url:../../images/azure/marketplace.svg';
import media from 'url:../../images/azure/media.svg';
import mediaFile from 'url:../../images/azure/media-file.svg';
import meshApplications from 'url:../../images/azure/mesh-applications.svg';
import metrics from 'url:../../images/azure/metrics.svg';
import migrate from 'url:../../images/azure/migrate.svg';
import mobile from 'url:../../images/azure/mobile.svg';
import mobileEngagement from 'url:../../images/azure/mobile-engagement.svg';
import module from 'url:../../images/azure/module.svg';
import monitor from 'url:../../images/azure/monitor.svg';
import multiTenancy from 'url:../../images/azure/multi-tenancy.svg';
import myCustomers from 'url:../../images/azure/my-customers.svg';
import notificationHubs from 'url:../../images/azure/notification-hubs.svg';
import offers from 'url:../../images/azure/offers.svg';
import operationLogClassic from 'url:../../images/azure/operation-log-(classic).svg';
import osImagesClassic from 'url:../../images/azure/os-images-(classic).svg';
import outboundConnection from 'url:../../images/azure/outbound-connection.svg';
import plans from 'url:../../images/azure/plans.svg';
import policy from 'url:../../images/azure/policy.svg';
import power from 'url:../../images/azure/power.svg';
import powerUp from 'url:../../images/azure/power-up.svg';
import powershell from 'url:../../images/azure/powershell.svg';
import preview from 'url:../../images/azure/preview.svg';
import processExplorer from 'url:../../images/azure/process-explorer.svg';
import productionReadyDatabase from 'url:../../images/azure/production-ready-database.svg';
import quickstartCenter from 'url:../../images/azure/quickstart-center.svg';
import recent from 'url:../../images/azure/recent.svg';
import recoveryServicesVaults from 'url:../../images/azure/recovery-services-vaults.svg';
import relays from 'url:../../images/azure/relays.svg';
import remoteRendering from 'url:../../images/azure/remote-rendering.svg';
import reservations from 'url:../../images/azure/reservations.svg';
import resourceGraphExplorer from 'url:../../images/azure/resource-graph-explorer.svg';
import resourceGroupList from 'url:../../images/azure/resource-group-list.svg';
import resourceGroups from 'url:../../images/azure/resource-groups.svg';
import resourceLinked from 'url:../../images/azure/resource-linked.svg';
import sapAzureMonitor from 'url:../../images/azure/sap-azure-monitor.svg';
import scale from 'url:../../images/azure/scale.svg';
import scheduler from 'url:../../images/azure/scheduler.svg';
import search from 'url:../../images/azure/search.svg';
import searchGrid from 'url:../../images/azure/search-grid.svg';
import searchServices from 'url:../../images/azure/search-services.svg';
import serverFarm from 'url:../../images/azure/server-farm.svg';
import serviceBus from 'url:../../images/azure/service-bus.svg';
import serviceFabricClusters from 'url:../../images/azure/service-fabric-clusters.svg';
import serviceHealth from 'url:../../images/azure/service-health.svg';
import serviceProviders from 'url:../../images/azure/service-providers.svg';
import sharedImageGalleries from 'url:../../images/azure/shared-image-galleries.svg';
import softwareAsAService from 'url:../../images/azure/software-as-a-service.svg';
import solutions from 'url:../../images/azure/solutions.svg';
import sqlDataWarehouses from 'url:../../images/azure/sql-data-warehouses.svg';
import sqlDatabase from 'url:../../images/azure/sql-database.svg';
import sqlElasticPools from 'url:../../images/azure/sql-elastic-pools.svg';
import sqlManagedInstance from 'url:../../images/azure/sql-managed-instance.svg';
import sqlServer from 'url:../../images/azure/sql-server.svg';
import sqlServerStretchDatabases from 'url:../../images/azure/sql-server-stretch-databases.svg';
import sqlVm from 'url:../../images/azure/sql-vm.svg';
import ssd from 'url:../../images/azure/ssd.svg';
import stack from 'url:../../images/azure/stack.svg';
import storageAzureFiles from 'url:../../images/azure/storage-azure-files.svg';
import storageContainer from 'url:../../images/azure/storage-container.svg';
import storageQueue from 'url:../../images/azure/storage-queue.svg';
import streamAnalyticsJobs from 'url:../../images/azure/stream-analytics-jobs.svg';
import subscriptions from 'url:../../images/azure/subscriptions.svg';
import synapseAnalytics from 'url:../../images/azure/synapse-analytics.svg';
import table from 'url:../../images/azure/table.svg';
import tags from 'url:../../images/azure/tags.svg';
import tfsVcRepository from 'url:../../images/azure/tfs-vc-repository.svg';
import timeSeriesInsightsEnvironments from 'url:../../images/azure/time-series-insights-environments.svg';
import timeSeriesInsightsEventSources from 'url:../../images/azure/time-series-insights-event-sources.svg';
import tokenService from 'url:../../images/azure/token-service.svg';
import toolbox from 'url:../../images/azure/toolbox.svg';
import updates from 'url:../../images/azure/updates.svg';
import userPrivacy from 'url:../../images/azure/user-privacy.svg';
import userSubscriptions from 'url:../../images/azure/user-subscriptions.svg';
import users from 'url:../../images/azure/users.svg';
import versions from 'url:../../images/azure/versions.svg';
import virtualClusters from 'url:../../images/azure/virtual-clusters.svg';
import virtualMachine from 'url:../../images/azure/virtual-machine.svg';
import virtualMachinesClassic from 'url:../../images/azure/virtual-machines-(classic).svg';
import vmImagesClassic from 'url:../../images/azure/vm-images-(classic).svg';
import vmScaleSets from 'url:../../images/azure/vm-scale-sets.svg';
import webSlots from 'url:../../images/azure/web-slots.svg';
import webTest from 'url:../../images/azure/web-test.svg';
import websitePower from 'url:../../images/azure/website-power.svg';
import websiteStaging from 'url:../../images/azure/website-staging.svg';
import workbooks from 'url:../../images/azure/workbooks.svg';
import workflow from 'url:../../images/azure/workflow.svg';
import workspaces from 'url:../../images/azure/workspaces.svg';

export {
  absMember,
  activeDirectory,
  activeDirectoryConnectHealth,
  activityLog,
  adB2C,
  adDomainServices,
  adRolesAndAdministrators,
  advisor,
  alerts,
  allResources,
  analysisServices,
  apiManagementServices,
  appRegistrations,
  appServiceCertificates,
  appServiceDomains,
  appServiceEnvironments,
  appServicePlans,
  appServices,
  applicationInsights,
  arc,
  automationAccounts,
  availabilitySets,
  avs,
  backlog,
  batchAccounts,
  bizTalk,
  blobBlock,
  blobPage,
  blockchainService,
  blueprints,
  botServices,
  branch,
  browser,
  bug,
  builds,
  cache,
  cacheRedis,
  capacity,
  cdnProfiles,
  cloudServicesClassic,
  code,
  cognitiveServices,
  commit,
  compliance,
  consortium,
  containerInstances,
  containerRegistries,
  containerServicesDeprecated,
  controls,
  controlsHorizontal,
  cosmosDb,
  costAlerts,
  costAnalysis,
  costBudgets,
  costManagement,
  counter,
  cubes,
  dashboard,
  dataBox,
  dataBoxEdge,
  dataCatalog,
  dataExplorerClusters,
  dataFactory,
  dataLakeStoreGen1,
  databaseMariadbServer,
  databaseMigrationServices,
  databaseMysqlServer,
  databasePostgresqlServer,
  devConsole,
  deviceProvisioningServices,
  deviceSecurityApple,
  deviceSecurityGoogle,
  deviceSecurityWindows,
  devops,
  devtestLabs,
  diagnosticsSettings,
  digitalTwins,
  diskEncryptionSets,
  disks,
  disksClassic,
  disksSnapshots,
  download,
  education,
  elasticJobAgents,
  elixir,
  elixirPurple,
  enterpriseApplications,
  error,
  eventGridDomains,
  eventGridSubscriptions,
  eventGridTopics,
  eventHubClusters,
  eventHubs,
  extensions,
  file,
  files,
  folderBlank,
  folderWebsite,
  ftp,
  functionApps,
  gear,
  globe,
  globeError,
  globeSuccess,
  globeWarning,
  groups,
  guide,
  hdInsightClusters,
  heart,
  helpAndSupport,
  identityGovernance,
  image,
  imageDefinitions,
  imageVersions,
  images,
  information,
  infrastructureBackup,
  inputOutput,
  instancePools,
  integrationAccounts,
  iotCentralApplications,
  iotHub,
  journeyHub,
  kubernetesServices,
  labServices,
  launchPortal,
  learn,
  lighthouse,
  loadTest,
  location,
  logAnalyticsWorkspaces,
  logStreaming,
  logicApps,
  machinesAzureArc,
  managedApplicationsCenter,
  managedDatabase,
  managementGroups,
  managementPortal,
  mapsAccounts,
  marketplace,
  media,
  mediaFile,
  meshApplications,
  metrics,
  migrate,
  mobile,
  mobileEngagement,
  module,
  monitor,
  multiTenancy,
  myCustomers,
  notificationHubs,
  offers,
  operationLogClassic,
  osImagesClassic,
  outboundConnection,
  plans,
  policy,
  power,
  powerUp,
  powershell,
  preview,
  processExplorer,
  productionReadyDatabase,
  quickstartCenter,
  recent,
  recoveryServicesVaults,
  relays,
  remoteRendering,
  reservations,
  resourceGraphExplorer,
  resourceGroupList,
  resourceGroups,
  resourceLinked,
  sapAzureMonitor,
  scale,
  scheduler,
  search,
  searchGrid,
  searchServices,
  serverFarm,
  serviceBus,
  serviceFabricClusters,
  serviceHealth,
  serviceProviders,
  sharedImageGalleries,
  softwareAsAService,
  solutions,
  sqlDataWarehouses,
  sqlDatabase,
  sqlElasticPools,
  sqlManagedInstance,
  sqlServer,
  sqlServerStretchDatabases,
  sqlVm,
  ssd,
  stack,
  storageAzureFiles,
  storageContainer,
  storageQueue,
  streamAnalyticsJobs,
  subscriptions,
  synapseAnalytics,
  table,
  tags,
  tfsVcRepository,
  timeSeriesInsightsEnvironments,
  timeSeriesInsightsEventSources,
  tokenService,
  toolbox,
  updates,
  userPrivacy,
  userSubscriptions,
  users,
  versions,
  virtualClusters,
  virtualMachine,
  virtualMachinesClassic,
  vmImagesClassic,
  vmScaleSets,
  webSlots,
  webTest,
  websitePower,
  websiteStaging,
  workbooks,
  workflow,
  workspaces,
};
