// !!! DO NOT EDIT !!! -- automatically generated by scripts/assets.js

import aarch64 from 'url:../../images/devicon/aarch64.svg';
import aarch64Plain from 'url:../../images/devicon/aarch64-plain.svg';
import adonisjs from 'url:../../images/devicon/adonisjs.svg';
import adonisjsOriginalWordmark from 'url:../../images/devicon/adonisjs-original-wordmark.svg';
import aftereffects from 'url:../../images/devicon/aftereffects.svg';
import aftereffectsPlain from 'url:../../images/devicon/aftereffects-plain.svg';
import amazonwebservices from 'url:../../images/devicon/amazonwebservices.svg';
import amazonwebservicesOriginalWordmark from 'url:../../images/devicon/amazonwebservices-original-wordmark.svg';
import amazonwebservicesPlainWordmark from 'url:../../images/devicon/amazonwebservices-plain-wordmark.svg';
import anaconda from 'url:../../images/devicon/anaconda.svg';
import anacondaOriginalWordmark from 'url:../../images/devicon/anaconda-original-wordmark.svg';
import android from 'url:../../images/devicon/android.svg';
import androidOriginalWordmark from 'url:../../images/devicon/android-original-wordmark.svg';
import androidPlain from 'url:../../images/devicon/android-plain.svg';
import androidPlainWordmark from 'url:../../images/devicon/android-plain-wordmark.svg';
import androidstudio from 'url:../../images/devicon/androidstudio.svg';
import androidstudioOriginalWordmark from 'url:../../images/devicon/androidstudio-original-wordmark.svg';
import androidstudioPlain from 'url:../../images/devicon/androidstudio-plain.svg';
import androidstudioPlainWordmark from 'url:../../images/devicon/androidstudio-plain-wordmark.svg';
import angularjs from 'url:../../images/devicon/angularjs.svg';
import angularjsOriginalWordmark from 'url:../../images/devicon/angularjs-original-wordmark.svg';
import angularjsPlain from 'url:../../images/devicon/angularjs-plain.svg';
import angularjsPlainWordmark from 'url:../../images/devicon/angularjs-plain-wordmark.svg';
import ansible from 'url:../../images/devicon/ansible.svg';
import ansibleOriginalWordmark from 'url:../../images/devicon/ansible-original-wordmark.svg';
import ansiblePlain from 'url:../../images/devicon/ansible-plain.svg';
import ansiblePlainWordmark from 'url:../../images/devicon/ansible-plain-wordmark.svg';
import apache from 'url:../../images/devicon/apache.svg';
import apacheLine from 'url:../../images/devicon/apache-line.svg';
import apacheLineWordmark from 'url:../../images/devicon/apache-line-wordmark.svg';
import apacheOriginalWordmark from 'url:../../images/devicon/apache-original-wordmark.svg';
import apachePlain from 'url:../../images/devicon/apache-plain.svg';
import apachePlainWordmark from 'url:../../images/devicon/apache-plain-wordmark.svg';
import apachekafka from 'url:../../images/devicon/apachekafka.svg';
import apachekafkaOriginalWordmark from 'url:../../images/devicon/apachekafka-original-wordmark.svg';
import appcelerator from 'url:../../images/devicon/appcelerator.svg';
import appceleratorOriginalWordmark from 'url:../../images/devicon/appcelerator-original-wordmark.svg';
import appceleratorPlainWordmark from 'url:../../images/devicon/appcelerator-plain-wordmark.svg';
import apple from 'url:../../images/devicon/apple.svg';
import appwrite from 'url:../../images/devicon/appwrite.svg';
import appwriteOriginalWordmark from 'url:../../images/devicon/appwrite-original-wordmark.svg';
import appwritePlain from 'url:../../images/devicon/appwrite-plain.svg';
import appwritePlainWordmark from 'url:../../images/devicon/appwrite-plain-wordmark.svg';
import arduino from 'url:../../images/devicon/arduino.svg';
import arduinoOriginalWordmark from 'url:../../images/devicon/arduino-original-wordmark.svg';
import arduinoPlain from 'url:../../images/devicon/arduino-plain.svg';
import arduinoPlainWordmark from 'url:../../images/devicon/arduino-plain-wordmark.svg';
import argocd from 'url:../../images/devicon/argocd.svg';
import argocdOriginalWordmark from 'url:../../images/devicon/argocd-original-wordmark.svg';
import argocdPlain from 'url:../../images/devicon/argocd-plain.svg';
import argocdPlainWordmark from 'url:../../images/devicon/argocd-plain-wordmark.svg';
import atom from 'url:../../images/devicon/atom.svg';
import atomOriginalWordmark from 'url:../../images/devicon/atom-original-wordmark.svg';
import azure from 'url:../../images/devicon/azure.svg';
import azureOriginalWordmark from 'url:../../images/devicon/azure-original-wordmark.svg';
import azurePlain from 'url:../../images/devicon/azure-plain.svg';
import azurePlainWordmark from 'url:../../images/devicon/azure-plain-wordmark.svg';
import babel from 'url:../../images/devicon/babel.svg';
import babelPlain from 'url:../../images/devicon/babel-plain.svg';
import backbonejs from 'url:../../images/devicon/backbonejs.svg';
import backbonejsOriginalWordmark from 'url:../../images/devicon/backbonejs-original-wordmark.svg';
import backbonejsPlain from 'url:../../images/devicon/backbonejs-plain.svg';
import backbonejsPlainWordmark from 'url:../../images/devicon/backbonejs-plain-wordmark.svg';
import bamboo from 'url:../../images/devicon/bamboo.svg';
import bambooOriginalWordmark from 'url:../../images/devicon/bamboo-original-wordmark.svg';
import bash from 'url:../../images/devicon/bash.svg';
import bashPlain from 'url:../../images/devicon/bash-plain.svg';
import behance from 'url:../../images/devicon/behance.svg';
import behanceOriginalWordmark from 'url:../../images/devicon/behance-original-wordmark.svg';
import behancePlain from 'url:../../images/devicon/behance-plain.svg';
import behancePlainWordmark from 'url:../../images/devicon/behance-plain-wordmark.svg';
import bitbucket from 'url:../../images/devicon/bitbucket.svg';
import bitbucketOriginalWordmark from 'url:../../images/devicon/bitbucket-original-wordmark.svg';
import blender from 'url:../../images/devicon/blender.svg';
import blenderOriginalWordmark from 'url:../../images/devicon/blender-original-wordmark.svg';
import bootstrap from 'url:../../images/devicon/bootstrap.svg';
import bootstrapOriginalWordmark from 'url:../../images/devicon/bootstrap-original-wordmark.svg';
import bootstrapPlain from 'url:../../images/devicon/bootstrap-plain.svg';
import bootstrapPlainWordmark from 'url:../../images/devicon/bootstrap-plain-wordmark.svg';
import bower from 'url:../../images/devicon/bower.svg';
import bowerLine from 'url:../../images/devicon/bower-line.svg';
import bowerLineWordmark from 'url:../../images/devicon/bower-line-wordmark.svg';
import bowerOriginalWordmark from 'url:../../images/devicon/bower-original-wordmark.svg';
import bowerPlain from 'url:../../images/devicon/bower-plain.svg';
import bowerPlainWordmark from 'url:../../images/devicon/bower-plain-wordmark.svg';
import bulmaPlain from 'url:../../images/devicon/bulma-plain.svg';
import c from 'url:../../images/devicon/c.svg';
import cLine from 'url:../../images/devicon/c-line.svg';
import cPlain from 'url:../../images/devicon/c-plain.svg';
import cakephp from 'url:../../images/devicon/cakephp.svg';
import cakephpOriginalWordmark from 'url:../../images/devicon/cakephp-original-wordmark.svg';
import cakephpPlain from 'url:../../images/devicon/cakephp-plain.svg';
import cakephpPlainWordmark from 'url:../../images/devicon/cakephp-plain-wordmark.svg';
import canva from 'url:../../images/devicon/canva.svg';
import centos from 'url:../../images/devicon/centos.svg';
import centosOriginalWordmark from 'url:../../images/devicon/centos-original-wordmark.svg';
import centosPlain from 'url:../../images/devicon/centos-plain.svg';
import centosPlainWordmark from 'url:../../images/devicon/centos-plain-wordmark.svg';
import ceylon from 'url:../../images/devicon/ceylon.svg';
import ceylonOriginalWordmark from 'url:../../images/devicon/ceylon-original-wordmark.svg';
import ceylonPlain from 'url:../../images/devicon/ceylon-plain.svg';
import ceylonPlainWordmark from 'url:../../images/devicon/ceylon-plain-wordmark.svg';
import chrome from 'url:../../images/devicon/chrome.svg';
import chromeOriginalWordmark from 'url:../../images/devicon/chrome-original-wordmark.svg';
import chromePlain from 'url:../../images/devicon/chrome-plain.svg';
import chromePlainWordmark from 'url:../../images/devicon/chrome-plain-wordmark.svg';
import circleciPlain from 'url:../../images/devicon/circleci-plain.svg';
import circleciPlainWordmark from 'url:../../images/devicon/circleci-plain-wordmark.svg';
import clojure from 'url:../../images/devicon/clojure.svg';
import clojureLine from 'url:../../images/devicon/clojure-line.svg';
import clojurescript from 'url:../../images/devicon/clojurescript.svg';
import clojurescriptPlain from 'url:../../images/devicon/clojurescript-plain.svg';
import cmake from 'url:../../images/devicon/cmake.svg';
import cmakeOriginalWordmark from 'url:../../images/devicon/cmake-original-wordmark.svg';
import cmakePlain from 'url:../../images/devicon/cmake-plain.svg';
import cmakePlainWordmark from 'url:../../images/devicon/cmake-plain-wordmark.svg';
import codecovPlain from 'url:../../images/devicon/codecov-plain.svg';
import codeigniterPlain from 'url:../../images/devicon/codeigniter-plain.svg';
import codeigniterPlainWordmark from 'url:../../images/devicon/codeigniter-plain-wordmark.svg';
import codepenOriginalWordmark from 'url:../../images/devicon/codepen-original-wordmark.svg';
import codepenPlain from 'url:../../images/devicon/codepen-plain.svg';
import coffeescript from 'url:../../images/devicon/coffeescript.svg';
import coffeescriptOriginalWordmark from 'url:../../images/devicon/coffeescript-original-wordmark.svg';
import composer from 'url:../../images/devicon/composer.svg';
import composerLine from 'url:../../images/devicon/composer-line.svg';
import composerLineWordmark from 'url:../../images/devicon/composer-line-wordmark.svg';
import confluence from 'url:../../images/devicon/confluence.svg';
import confluenceOriginalWordmark from 'url:../../images/devicon/confluence-original-wordmark.svg';
import couchdb from 'url:../../images/devicon/couchdb.svg';
import couchdbOriginalWordmark from 'url:../../images/devicon/couchdb-original-wordmark.svg';
import couchdbPlain from 'url:../../images/devicon/couchdb-plain.svg';
import couchdbPlainWordmark from 'url:../../images/devicon/couchdb-plain-wordmark.svg';
import cplusplus from 'url:../../images/devicon/cplusplus.svg';
import cplusplusLine from 'url:../../images/devicon/cplusplus-line.svg';
import cplusplusPlain from 'url:../../images/devicon/cplusplus-plain.svg';
import crystal from 'url:../../images/devicon/crystal.svg';
import crystalOriginalWordmark from 'url:../../images/devicon/crystal-original-wordmark.svg';
import csharp from 'url:../../images/devicon/csharp.svg';
import csharpLine from 'url:../../images/devicon/csharp-line.svg';
import csharpPlain from 'url:../../images/devicon/csharp-plain.svg';
import css3 from 'url:../../images/devicon/css3.svg';
import css3OriginalWordmark from 'url:../../images/devicon/css3-original-wordmark.svg';
import css3Plain from 'url:../../images/devicon/css3-plain.svg';
import css3PlainWordmark from 'url:../../images/devicon/css3-plain-wordmark.svg';
import cucumberPlain from 'url:../../images/devicon/cucumber-plain.svg';
import cucumberPlainWordmark from 'url:../../images/devicon/cucumber-plain-wordmark.svg';
import d3Js from 'url:../../images/devicon/d3js.svg';
import d3JsPlain from 'url:../../images/devicon/d3js-plain.svg';
import dart from 'url:../../images/devicon/dart.svg';
import dartOriginalWordmark from 'url:../../images/devicon/dart-original-wordmark.svg';
import dartPlain from 'url:../../images/devicon/dart-plain.svg';
import dartPlainWordmark from 'url:../../images/devicon/dart-plain-wordmark.svg';
import debian from 'url:../../images/devicon/debian.svg';
import debianOriginalWordmark from 'url:../../images/devicon/debian-original-wordmark.svg';
import debianPlain from 'url:../../images/devicon/debian-plain.svg';
import debianPlainWordmark from 'url:../../images/devicon/debian-plain-wordmark.svg';
import denojs from 'url:../../images/devicon/denojs.svg';
import denojsOriginalWordmark from 'url:../../images/devicon/denojs-original-wordmark.svg';
import devicon from 'url:../../images/devicon/devicon.svg';
import deviconLine from 'url:../../images/devicon/devicon-line.svg';
import deviconLineWordmark from 'url:../../images/devicon/devicon-line-wordmark.svg';
import deviconOriginalWordmark from 'url:../../images/devicon/devicon-original-wordmark.svg';
import deviconPlain from 'url:../../images/devicon/devicon-plain.svg';
import deviconPlainWordmark from 'url:../../images/devicon/devicon-plain-wordmark.svg';
import digitalocean from 'url:../../images/devicon/digitalocean.svg';
import digitaloceanOriginalWordmark from 'url:../../images/devicon/digitalocean-original-wordmark.svg';
import digitaloceanPlain from 'url:../../images/devicon/digitalocean-plain.svg';
import digitaloceanPlainWordmark from 'url:../../images/devicon/digitalocean-plain-wordmark.svg';
import discordjs from 'url:../../images/devicon/discordjs.svg';
import discordjsOriginalWordmark from 'url:../../images/devicon/discordjs-original-wordmark.svg';
import discordjsPlain from 'url:../../images/devicon/discordjs-plain.svg';
import discordjsPlainWordmark from 'url:../../images/devicon/discordjs-plain-wordmark.svg';
import djangoPlain from 'url:../../images/devicon/django-plain.svg';
import djangoPlainWordmark from 'url:../../images/devicon/django-plain-wordmark.svg';
import docker from 'url:../../images/devicon/docker.svg';
import dockerOriginalWordmark from 'url:../../images/devicon/docker-original-wordmark.svg';
import dockerPlain from 'url:../../images/devicon/docker-plain.svg';
import dockerPlainWordmark from 'url:../../images/devicon/docker-plain-wordmark.svg';
import doctrine from 'url:../../images/devicon/doctrine.svg';
import doctrineLine from 'url:../../images/devicon/doctrine-line.svg';
import doctrineLineWordmark from 'url:../../images/devicon/doctrine-line-wordmark.svg';
import doctrineOriginalWordmark from 'url:../../images/devicon/doctrine-original-wordmark.svg';
import doctrinePlain from 'url:../../images/devicon/doctrine-plain.svg';
import doctrinePlainWordmark from 'url:../../images/devicon/doctrine-plain-wordmark.svg';
import dotNet from 'url:../../images/devicon/dot-net.svg';
import dotNetOriginalWordmark from 'url:../../images/devicon/dot-net-original-wordmark.svg';
import dotNetPlain from 'url:../../images/devicon/dot-net-plain.svg';
import dotNetPlainWordmark from 'url:../../images/devicon/dot-net-plain-wordmark.svg';
import dotnetcore from 'url:../../images/devicon/dotnetcore.svg';
import dotnetcorePlain from 'url:../../images/devicon/dotnetcore-plain.svg';
import dropwizard from 'url:../../images/devicon/dropwizard.svg';
import dropwizardPlain from 'url:../../images/devicon/dropwizard-plain.svg';
import drupal from 'url:../../images/devicon/drupal.svg';
import drupalOriginalWordmark from 'url:../../images/devicon/drupal-original-wordmark.svg';
import drupalPlain from 'url:../../images/devicon/drupal-plain.svg';
import drupalPlainWordmark from 'url:../../images/devicon/drupal-plain-wordmark.svg';
import electron from 'url:../../images/devicon/electron.svg';
import electronOriginalWordmark from 'url:../../images/devicon/electron-original-wordmark.svg';
import eleventy from 'url:../../images/devicon/eleventy.svg';
import eleventyPlain from 'url:../../images/devicon/eleventy-plain.svg';
import elixir from 'url:../../images/devicon/elixir.svg';
import elixirOriginalWordmark from 'url:../../images/devicon/elixir-original-wordmark.svg';
import elixirPlain from 'url:../../images/devicon/elixir-plain.svg';
import elixirPlainWordmark from 'url:../../images/devicon/elixir-plain-wordmark.svg';
import elm from 'url:../../images/devicon/elm.svg';
import elmOriginalWordmark from 'url:../../images/devicon/elm-original-wordmark.svg';
import elmPlain from 'url:../../images/devicon/elm-plain.svg';
import elmPlainWordmark from 'url:../../images/devicon/elm-plain-wordmark.svg';
import embeddedc from 'url:../../images/devicon/embeddedc.svg';
import embeddedcOriginalWordmark from 'url:../../images/devicon/embeddedc-original-wordmark.svg';
import embeddedcPlain from 'url:../../images/devicon/embeddedc-plain.svg';
import embeddedcPlainWordmark from 'url:../../images/devicon/embeddedc-plain-wordmark.svg';
import emberOriginalWordmark from 'url:../../images/devicon/ember-original-wordmark.svg';
import erlang from 'url:../../images/devicon/erlang.svg';
import erlangOriginalWordmark from 'url:../../images/devicon/erlang-original-wordmark.svg';
import erlangPlain from 'url:../../images/devicon/erlang-plain.svg';
import erlangPlainWordmark from 'url:../../images/devicon/erlang-plain-wordmark.svg';
import eslint from 'url:../../images/devicon/eslint.svg';
import eslintOriginalWordmark from 'url:../../images/devicon/eslint-original-wordmark.svg';
import express from 'url:../../images/devicon/express.svg';
import expressOriginalWordmark from 'url:../../images/devicon/express-original-wordmark.svg';
import facebook from 'url:../../images/devicon/facebook.svg';
import facebookPlain from 'url:../../images/devicon/facebook-plain.svg';
import fastapi from 'url:../../images/devicon/fastapi.svg';
import fastapiOriginalWordmark from 'url:../../images/devicon/fastapi-original-wordmark.svg';
import fastapiPlain from 'url:../../images/devicon/fastapi-plain.svg';
import fastapiPlainWordmark from 'url:../../images/devicon/fastapi-plain-wordmark.svg';
import feathersjs from 'url:../../images/devicon/feathersjs.svg';
import fedora from 'url:../../images/devicon/fedora.svg';
import fedoraPlain from 'url:../../images/devicon/fedora-plain.svg';
import figma from 'url:../../images/devicon/figma.svg';
import figmaPlain from 'url:../../images/devicon/figma-plain.svg';
import filezillaPlain from 'url:../../images/devicon/filezilla-plain.svg';
import filezillaPlainWordmark from 'url:../../images/devicon/filezilla-plain-wordmark.svg';
import firebasePlain from 'url:../../images/devicon/firebase-plain.svg';
import firebasePlainWordmark from 'url:../../images/devicon/firebase-plain-wordmark.svg';
import firefox from 'url:../../images/devicon/firefox.svg';
import firefoxOriginalWordmark from 'url:../../images/devicon/firefox-original-wordmark.svg';
import firefoxPlain from 'url:../../images/devicon/firefox-plain.svg';
import firefoxPlainWordmark from 'url:../../images/devicon/firefox-plain-wordmark.svg';
import flask from 'url:../../images/devicon/flask.svg';
import flaskOriginalWordmark from 'url:../../images/devicon/flask-original-wordmark.svg';
import flutter from 'url:../../images/devicon/flutter.svg';
import flutterPlain from 'url:../../images/devicon/flutter-plain.svg';
import foundation from 'url:../../images/devicon/foundation.svg';
import foundationOriginalWordmark from 'url:../../images/devicon/foundation-original-wordmark.svg';
import foundationPlain from 'url:../../images/devicon/foundation-plain.svg';
import foundationPlainWordmark from 'url:../../images/devicon/foundation-plain-wordmark.svg';
import fsharp from 'url:../../images/devicon/fsharp.svg';
import fsharpPlain from 'url:../../images/devicon/fsharp-plain.svg';
import gatlingPlain from 'url:../../images/devicon/gatling-plain.svg';
import gatlingPlainWordmark from 'url:../../images/devicon/gatling-plain-wordmark.svg';
import gatsby from 'url:../../images/devicon/gatsby.svg';
import gatsbyOriginalWordmark from 'url:../../images/devicon/gatsby-original-wordmark.svg';
import gatsbyPlain from 'url:../../images/devicon/gatsby-plain.svg';
import gatsbyPlainWordmark from 'url:../../images/devicon/gatsby-plain-wordmark.svg';
import gcc from 'url:../../images/devicon/gcc.svg';
import gccPlain from 'url:../../images/devicon/gcc-plain.svg';
import gentooPlain from 'url:../../images/devicon/gentoo-plain.svg';
import gentooPlainWordmark from 'url:../../images/devicon/gentoo-plain-wordmark.svg';
import gimp from 'url:../../images/devicon/gimp.svg';
import gimpOriginalWordmark from 'url:../../images/devicon/gimp-original-wordmark.svg';
import gimpPlain from 'url:../../images/devicon/gimp-plain.svg';
import gimpPlainWordmark from 'url:../../images/devicon/gimp-plain-wordmark.svg';
import git from 'url:../../images/devicon/git.svg';
import gitOriginalWordmark from 'url:../../images/devicon/git-original-wordmark.svg';
import gitPlain from 'url:../../images/devicon/git-plain.svg';
import gitPlainWordmark from 'url:../../images/devicon/git-plain-wordmark.svg';
import github from 'url:../../images/devicon/github.svg';
import githubOriginalWordmark from 'url:../../images/devicon/github-original-wordmark.svg';
import gitlab from 'url:../../images/devicon/gitlab.svg';
import gitlabOriginalWordmark from 'url:../../images/devicon/gitlab-original-wordmark.svg';
import gitlabPlain from 'url:../../images/devicon/gitlab-plain.svg';
import gitlabPlainWordmark from 'url:../../images/devicon/gitlab-plain-wordmark.svg';
import gitterPlain from 'url:../../images/devicon/gitter-plain.svg';
import gitterPlainWordmark from 'url:../../images/devicon/gitter-plain-wordmark.svg';
import go from 'url:../../images/devicon/go.svg';
import goLine from 'url:../../images/devicon/go-line.svg';
import goOriginalWordmark from 'url:../../images/devicon/go-original-wordmark.svg';
import goPlain from 'url:../../images/devicon/go-plain.svg';
import godot from 'url:../../images/devicon/godot.svg';
import godotOriginalWordmark from 'url:../../images/devicon/godot-original-wordmark.svg';
import godotPlain from 'url:../../images/devicon/godot-plain.svg';
import godotPlainWordmark from 'url:../../images/devicon/godot-plain-wordmark.svg';
import google from 'url:../../images/devicon/google.svg';
import googleOriginalWordmark from 'url:../../images/devicon/google-original-wordmark.svg';
import googlePlain from 'url:../../images/devicon/google-plain.svg';
import googlePlainWordmark from 'url:../../images/devicon/google-plain-wordmark.svg';
import googlecloud from 'url:../../images/devicon/googlecloud.svg';
import googlecloudOriginalWordmark from 'url:../../images/devicon/googlecloud-original-wordmark.svg';
import googlecloudPlain from 'url:../../images/devicon/googlecloud-plain.svg';
import googlecloudPlainWordmark from 'url:../../images/devicon/googlecloud-plain-wordmark.svg';
import gradlePlain from 'url:../../images/devicon/gradle-plain.svg';
import gradlePlainWordmark from 'url:../../images/devicon/gradle-plain-wordmark.svg';
import grafana from 'url:../../images/devicon/grafana.svg';
import grafanaOriginalWordmark from 'url:../../images/devicon/grafana-original-wordmark.svg';
import grails from 'url:../../images/devicon/grails.svg';
import grailsPlain from 'url:../../images/devicon/grails-plain.svg';
import graphqlPlain from 'url:../../images/devicon/graphql-plain.svg';
import graphqlPlainWordmark from 'url:../../images/devicon/graphql-plain-wordmark.svg';
import groovy from 'url:../../images/devicon/groovy.svg';
import groovyPlain from 'url:../../images/devicon/groovy-plain.svg';
import grunt from 'url:../../images/devicon/grunt.svg';
import gruntLine from 'url:../../images/devicon/grunt-line.svg';
import gruntLineWordmark from 'url:../../images/devicon/grunt-line-wordmark.svg';
import gruntOriginalWordmark from 'url:../../images/devicon/grunt-original-wordmark.svg';
import gruntPlain from 'url:../../images/devicon/grunt-plain.svg';
import gruntPlainWordmark from 'url:../../images/devicon/grunt-plain-wordmark.svg';
import gulpPlain from 'url:../../images/devicon/gulp-plain.svg';
import handlebars from 'url:../../images/devicon/handlebars.svg';
import handlebarsOriginalWordmark from 'url:../../images/devicon/handlebars-original-wordmark.svg';
import haskell from 'url:../../images/devicon/haskell.svg';
import haskellOriginalWordmark from 'url:../../images/devicon/haskell-original-wordmark.svg';
import haskellPlain from 'url:../../images/devicon/haskell-plain.svg';
import haskellPlainWordmark from 'url:../../images/devicon/haskell-plain-wordmark.svg';
import haxe from 'url:../../images/devicon/haxe.svg';
import haxePlain from 'url:../../images/devicon/haxe-plain.svg';
import heroku from 'url:../../images/devicon/heroku.svg';
import herokuOriginalWordmark from 'url:../../images/devicon/heroku-original-wordmark.svg';
import herokuPlain from 'url:../../images/devicon/heroku-plain.svg';
import herokuPlainWordmark from 'url:../../images/devicon/heroku-plain-wordmark.svg';
import html5 from 'url:../../images/devicon/html5.svg';
import html5OriginalWordmark from 'url:../../images/devicon/html5-original-wordmark.svg';
import html5Plain from 'url:../../images/devicon/html5-plain.svg';
import html5PlainWordmark from 'url:../../images/devicon/html5-plain-wordmark.svg';
import hugo from 'url:../../images/devicon/hugo.svg';
import hugoOriginalWordmark from 'url:../../images/devicon/hugo-original-wordmark.svg';
import hugoPlain from 'url:../../images/devicon/hugo-plain.svg';
import hugoPlainWordmark from 'url:../../images/devicon/hugo-plain-wordmark.svg';
import ie10 from 'url:../../images/devicon/ie10.svg';
import ifttt from 'url:../../images/devicon/ifttt.svg';
import illustratorLine from 'url:../../images/devicon/illustrator-line.svg';
import illustratorPlain from 'url:../../images/devicon/illustrator-plain.svg';
import inkscape from 'url:../../images/devicon/inkscape.svg';
import inkscapeOriginalWordmark from 'url:../../images/devicon/inkscape-original-wordmark.svg';
import inkscapePlain from 'url:../../images/devicon/inkscape-plain.svg';
import inkscapePlainWordmark from 'url:../../images/devicon/inkscape-plain-wordmark.svg';
import intellij from 'url:../../images/devicon/intellij.svg';
import intellijOriginalWordmark from 'url:../../images/devicon/intellij-original-wordmark.svg';
import intellijPlain from 'url:../../images/devicon/intellij-plain.svg';
import intellijPlainWordmark from 'url:../../images/devicon/intellij-plain-wordmark.svg';
import ionic from 'url:../../images/devicon/ionic.svg';
import ionicOriginalWordmark from 'url:../../images/devicon/ionic-original-wordmark.svg';
import jamstack from 'url:../../images/devicon/jamstack.svg';
import jamstackOriginalWordmark from 'url:../../images/devicon/jamstack-original-wordmark.svg';
import jamstackPlainWordmark from 'url:../../images/devicon/jamstack-plain-wordmark.svg';
import jasminePlain from 'url:../../images/devicon/jasmine-plain.svg';
import jasminePlainWordmark from 'url:../../images/devicon/jasmine-plain-wordmark.svg';
import java from 'url:../../images/devicon/java.svg';
import javaOriginalWordmark from 'url:../../images/devicon/java-original-wordmark.svg';
import javaPlain from 'url:../../images/devicon/java-plain.svg';
import javaPlainWordmark from 'url:../../images/devicon/java-plain-wordmark.svg';
import javascript from 'url:../../images/devicon/javascript.svg';
import javascriptPlain from 'url:../../images/devicon/javascript-plain.svg';
import jeet from 'url:../../images/devicon/jeet.svg';
import jeetOriginalWordmark from 'url:../../images/devicon/jeet-original-wordmark.svg';
import jeetPlain from 'url:../../images/devicon/jeet-plain.svg';
import jeetPlainWordmark from 'url:../../images/devicon/jeet-plain-wordmark.svg';
import jenkins from 'url:../../images/devicon/jenkins.svg';
import jenkinsLine from 'url:../../images/devicon/jenkins-line.svg';
import jenkinsPlain from 'url:../../images/devicon/jenkins-plain.svg';
import jestPlain from 'url:../../images/devicon/jest-plain.svg';
import jetbrains from 'url:../../images/devicon/jetbrains.svg';
import jetbrainsPlain from 'url:../../images/devicon/jetbrains-plain.svg';
import jira from 'url:../../images/devicon/jira.svg';
import jiraOriginalWordmark from 'url:../../images/devicon/jira-original-wordmark.svg';
import jiraPlain from 'url:../../images/devicon/jira-plain.svg';
import jiraPlainWordmark from 'url:../../images/devicon/jira-plain-wordmark.svg';
import jquery from 'url:../../images/devicon/jquery.svg';
import jqueryOriginalWordmark from 'url:../../images/devicon/jquery-original-wordmark.svg';
import jqueryPlain from 'url:../../images/devicon/jquery-plain.svg';
import jqueryPlainWordmark from 'url:../../images/devicon/jquery-plain-wordmark.svg';
import julia from 'url:../../images/devicon/julia.svg';
import juliaOriginalWordmark from 'url:../../images/devicon/julia-original-wordmark.svg';
import juliaPlain from 'url:../../images/devicon/julia-plain.svg';
import juliaPlainWordmark from 'url:../../images/devicon/julia-plain-wordmark.svg';
import jupyter from 'url:../../images/devicon/jupyter.svg';
import jupyterOriginalWordmark from 'url:../../images/devicon/jupyter-original-wordmark.svg';
import jupyterPlain from 'url:../../images/devicon/jupyter-plain.svg';
import jupyterPlainWordmark from 'url:../../images/devicon/jupyter-plain-wordmark.svg';
import k3S from 'url:../../images/devicon/k3s.svg';
import k3SOriginalWordmark from 'url:../../images/devicon/k3s-original-wordmark.svg';
import k3SPlainWordmark from 'url:../../images/devicon/k3s-plain-wordmark.svg';
import kaggle from 'url:../../images/devicon/kaggle.svg';
import kaggleOriginalWordmark from 'url:../../images/devicon/kaggle-original-wordmark.svg';
import karma from 'url:../../images/devicon/karma.svg';
import karmaPlain from 'url:../../images/devicon/karma-plain.svg';
import knockoutPlainWordmark from 'url:../../images/devicon/knockout-plain-wordmark.svg';
import kotlin from 'url:../../images/devicon/kotlin.svg';
import kotlinOriginalWordmark from 'url:../../images/devicon/kotlin-original-wordmark.svg';
import kotlinPlain from 'url:../../images/devicon/kotlin-plain.svg';
import kotlinPlainWordmark from 'url:../../images/devicon/kotlin-plain-wordmark.svg';
import krakenjs from 'url:../../images/devicon/krakenjs.svg';
import krakenjsOriginalWordmark from 'url:../../images/devicon/krakenjs-original-wordmark.svg';
import krakenjsPlain from 'url:../../images/devicon/krakenjs-plain.svg';
import krakenjsPlainWordmark from 'url:../../images/devicon/krakenjs-plain-wordmark.svg';
import kubernetesPlain from 'url:../../images/devicon/kubernetes-plain.svg';
import kubernetesPlainWordmark from 'url:../../images/devicon/kubernetes-plain-wordmark.svg';
import labview from 'url:../../images/devicon/labview.svg';
import labviewOriginalWordmark from 'url:../../images/devicon/labview-original-wordmark.svg';
import labviewPlain from 'url:../../images/devicon/labview-plain.svg';
import labviewPlainWordmark from 'url:../../images/devicon/labview-plain-wordmark.svg';
import laravelPlain from 'url:../../images/devicon/laravel-plain.svg';
import laravelPlainWordmark from 'url:../../images/devicon/laravel-plain-wordmark.svg';
import latex from 'url:../../images/devicon/latex.svg';
import lessPlainWordmark from 'url:../../images/devicon/less-plain-wordmark.svg';
import linkedin from 'url:../../images/devicon/linkedin.svg';
import linkedinOriginalWordmark from 'url:../../images/devicon/linkedin-original-wordmark.svg';
import linkedinPlain from 'url:../../images/devicon/linkedin-plain.svg';
import linkedinPlainWordmark from 'url:../../images/devicon/linkedin-plain-wordmark.svg';
import linux from 'url:../../images/devicon/linux.svg';
import linuxPlain from 'url:../../images/devicon/linux-plain.svg';
import lua from 'url:../../images/devicon/lua.svg';
import luaOriginalWordmark from 'url:../../images/devicon/lua-original-wordmark.svg';
import luaPlain from 'url:../../images/devicon/lua-plain.svg';
import luaPlainWordmark from 'url:../../images/devicon/lua-plain-wordmark.svg';
import magento from 'url:../../images/devicon/magento.svg';
import magentoLine from 'url:../../images/devicon/magento-line.svg';
import magentoOriginalWordmark from 'url:../../images/devicon/magento-original-wordmark.svg';
import markdown from 'url:../../images/devicon/markdown.svg';
import materialui from 'url:../../images/devicon/materialui.svg';
import materialuiPlain from 'url:../../images/devicon/materialui-plain.svg';
import matlab from 'url:../../images/devicon/matlab.svg';
import matlabLine from 'url:../../images/devicon/matlab-line.svg';
import matlabPlain from 'url:../../images/devicon/matlab-plain.svg';
import maya from 'url:../../images/devicon/maya.svg';
import mayaOriginalWordmark from 'url:../../images/devicon/maya-original-wordmark.svg';
import mayaPlain from 'url:../../images/devicon/maya-plain.svg';
import mayaPlainWordmark from 'url:../../images/devicon/maya-plain-wordmark.svg';
import meteor from 'url:../../images/devicon/meteor.svg';
import meteorOriginalWordmark from 'url:../../images/devicon/meteor-original-wordmark.svg';
import meteorPlain from 'url:../../images/devicon/meteor-plain.svg';
import meteorPlainWordmark from 'url:../../images/devicon/meteor-plain-wordmark.svg';
import microsoftsqlserverPlain from 'url:../../images/devicon/microsoftsqlserver-plain.svg';
import microsoftsqlserverPlainWordmark from 'url:../../images/devicon/microsoftsqlserver-plain-wordmark.svg';
import minitab from 'url:../../images/devicon/minitab.svg';
import minitabPlain from 'url:../../images/devicon/minitab-plain.svg';
import mochaPlain from 'url:../../images/devicon/mocha-plain.svg';
import modx from 'url:../../images/devicon/modx.svg';
import modxOriginalWordmark from 'url:../../images/devicon/modx-original-wordmark.svg';
import modxPlain from 'url:../../images/devicon/modx-plain.svg';
import modxPlainWordmark from 'url:../../images/devicon/modx-plain-wordmark.svg';
import mongodb from 'url:../../images/devicon/mongodb.svg';
import mongodbOriginalWordmark from 'url:../../images/devicon/mongodb-original-wordmark.svg';
import mongodbPlain from 'url:../../images/devicon/mongodb-plain.svg';
import mongodbPlainWordmark from 'url:../../images/devicon/mongodb-plain-wordmark.svg';
import moodle from 'url:../../images/devicon/moodle.svg';
import moodleOriginalWordmark from 'url:../../images/devicon/moodle-original-wordmark.svg';
import moodlePlain from 'url:../../images/devicon/moodle-plain.svg';
import moodlePlainWordmark from 'url:../../images/devicon/moodle-plain-wordmark.svg';
import msdos from 'url:../../images/devicon/msdos.svg';
import msdosLine from 'url:../../images/devicon/msdos-line.svg';
import msdosPlain from 'url:../../images/devicon/msdos-plain.svg';
import mysql from 'url:../../images/devicon/mysql.svg';
import mysqlOriginalWordmark from 'url:../../images/devicon/mysql-original-wordmark.svg';
import mysqlPlain from 'url:../../images/devicon/mysql-plain.svg';
import mysqlPlainWordmark from 'url:../../images/devicon/mysql-plain-wordmark.svg';
import neo4J from 'url:../../images/devicon/neo4j.svg';
import neo4JOriginalWordmark from 'url:../../images/devicon/neo4j-original-wordmark.svg';
import neo4JPlain from 'url:../../images/devicon/neo4j-plain.svg';
import neo4JPlainWordmark from 'url:../../images/devicon/neo4j-plain-wordmark.svg';
import nestjsPlain from 'url:../../images/devicon/nestjs-plain.svg';
import nestjsPlainWordmark from 'url:../../images/devicon/nestjs-plain-wordmark.svg';
import networkx from 'url:../../images/devicon/networkx.svg';
import nextjs from 'url:../../images/devicon/nextjs.svg';
import nextjsLine from 'url:../../images/devicon/nextjs-line.svg';
import nextjsOriginalWordmark from 'url:../../images/devicon/nextjs-original-wordmark.svg';
import nginx from 'url:../../images/devicon/nginx.svg';
import nixos from 'url:../../images/devicon/nixos.svg';
import nixosOriginalWordmark from 'url:../../images/devicon/nixos-original-wordmark.svg';
import nixosPlain from 'url:../../images/devicon/nixos-plain.svg';
import nixosPlainWordmark from 'url:../../images/devicon/nixos-plain-wordmark.svg';
import nodejs from 'url:../../images/devicon/nodejs.svg';
import nodejsOriginalWordmark from 'url:../../images/devicon/nodejs-original-wordmark.svg';
import nodejsPlain from 'url:../../images/devicon/nodejs-plain.svg';
import nodejsPlainWordmark from 'url:../../images/devicon/nodejs-plain-wordmark.svg';
import nodewebkit from 'url:../../images/devicon/nodewebkit.svg';
import nodewebkitLine from 'url:../../images/devicon/nodewebkit-line.svg';
import nodewebkitLineWordmark from 'url:../../images/devicon/nodewebkit-line-wordmark.svg';
import nodewebkitOriginalWordmark from 'url:../../images/devicon/nodewebkit-original-wordmark.svg';
import nodewebkitPlain from 'url:../../images/devicon/nodewebkit-plain.svg';
import nodewebkitPlainWordmark from 'url:../../images/devicon/nodewebkit-plain-wordmark.svg';
import npmOriginalWordmark from 'url:../../images/devicon/npm-original-wordmark.svg';
import nuget from 'url:../../images/devicon/nuget.svg';
import nugetOriginalWordmark from 'url:../../images/devicon/nuget-original-wordmark.svg';
import numpy from 'url:../../images/devicon/numpy.svg';
import numpyOriginalWordmark from 'url:../../images/devicon/numpy-original-wordmark.svg';
import nuxtjs from 'url:../../images/devicon/nuxtjs.svg';
import nuxtjsOriginalWordmark from 'url:../../images/devicon/nuxtjs-original-wordmark.svg';
import nuxtjsPlain from 'url:../../images/devicon/nuxtjs-plain.svg';
import nuxtjsPlainWordmark from 'url:../../images/devicon/nuxtjs-plain-wordmark.svg';
import objectivecPlain from 'url:../../images/devicon/objectivec-plain.svg';
import ocaml from 'url:../../images/devicon/ocaml.svg';
import ocamlOriginalWordmark from 'url:../../images/devicon/ocaml-original-wordmark.svg';
import ocamlPlain from 'url:../../images/devicon/ocaml-plain.svg';
import ocamlPlainWordmark from 'url:../../images/devicon/ocaml-plain-wordmark.svg';
import openal from 'url:../../images/devicon/openal.svg';
import openalPlain from 'url:../../images/devicon/openal-plain.svg';
import opencv from 'url:../../images/devicon/opencv.svg';
import opencvOriginalWordmark from 'url:../../images/devicon/opencv-original-wordmark.svg';
import opencvPlain from 'url:../../images/devicon/opencv-plain.svg';
import opencvPlainWordmark from 'url:../../images/devicon/opencv-plain-wordmark.svg';
import opengl from 'url:../../images/devicon/opengl.svg';
import openglPlain from 'url:../../images/devicon/opengl-plain.svg';
import opensuse from 'url:../../images/devicon/opensuse.svg';
import opensuseOriginalWordmark from 'url:../../images/devicon/opensuse-original-wordmark.svg';
import opensusePlain from 'url:../../images/devicon/opensuse-plain.svg';
import opensusePlainWordmark from 'url:../../images/devicon/opensuse-plain-wordmark.svg';
import opera from 'url:../../images/devicon/opera.svg';
import operaOriginalWordmark from 'url:../../images/devicon/opera-original-wordmark.svg';
import operaPlain from 'url:../../images/devicon/opera-plain.svg';
import operaPlainWordmark from 'url:../../images/devicon/opera-plain-wordmark.svg';
import oracle from 'url:../../images/devicon/oracle.svg';
import packer from 'url:../../images/devicon/packer.svg';
import packerOriginalWordmark from 'url:../../images/devicon/packer-original-wordmark.svg';
import pandas from 'url:../../images/devicon/pandas.svg';
import pandasOriginalWordmark from 'url:../../images/devicon/pandas-original-wordmark.svg';
import perl from 'url:../../images/devicon/perl.svg';
import perlPlain from 'url:../../images/devicon/perl-plain.svg';
import phalcon from 'url:../../images/devicon/phalcon.svg';
import phalconPlain from 'url:../../images/devicon/phalcon-plain.svg';
import phoenix from 'url:../../images/devicon/phoenix.svg';
import phoenixOriginalWordmark from 'url:../../images/devicon/phoenix-original-wordmark.svg';
import phoenixPlain from 'url:../../images/devicon/phoenix-plain.svg';
import phoenixPlainWordmark from 'url:../../images/devicon/phoenix-plain-wordmark.svg';
import photoshopLine from 'url:../../images/devicon/photoshop-line.svg';
import photoshopPlain from 'url:../../images/devicon/photoshop-plain.svg';
import php from 'url:../../images/devicon/php.svg';
import phpPlain from 'url:../../images/devicon/php-plain.svg';
import phpstorm from 'url:../../images/devicon/phpstorm.svg';
import phpstormOriginalWordmark from 'url:../../images/devicon/phpstorm-original-wordmark.svg';
import phpstormPlain from 'url:../../images/devicon/phpstorm-plain.svg';
import phpstormPlainWordmark from 'url:../../images/devicon/phpstorm-plain-wordmark.svg';
import podman from 'url:../../images/devicon/podman.svg';
import podmanOriginalWordmark from 'url:../../images/devicon/podman-original-wordmark.svg';
import podmanPlain from 'url:../../images/devicon/podman-plain.svg';
import podmanPlainWordmark from 'url:../../images/devicon/podman-plain-wordmark.svg';
import polygon from 'url:../../images/devicon/polygon.svg';
import polygonPlain from 'url:../../images/devicon/polygon-plain.svg';
import postgresql from 'url:../../images/devicon/postgresql.svg';
import postgresqlOriginalWordmark from 'url:../../images/devicon/postgresql-original-wordmark.svg';
import postgresqlPlain from 'url:../../images/devicon/postgresql-plain.svg';
import postgresqlPlainWordmark from 'url:../../images/devicon/postgresql-plain-wordmark.svg';
import premierepro from 'url:../../images/devicon/premierepro.svg';
import premiereproPlain from 'url:../../images/devicon/premierepro-plain.svg';
import processing from 'url:../../images/devicon/processing.svg';
import processingOriginalWordmark from 'url:../../images/devicon/processing-original-wordmark.svg';
import processingPlain from 'url:../../images/devicon/processing-plain.svg';
import processingPlainWordmark from 'url:../../images/devicon/processing-plain-wordmark.svg';
import prometheus from 'url:../../images/devicon/prometheus.svg';
import prometheusOriginalWordmark from 'url:../../images/devicon/prometheus-original-wordmark.svg';
import protractorPlain from 'url:../../images/devicon/protractor-plain.svg';
import protractorPlainWordmark from 'url:../../images/devicon/protractor-plain-wordmark.svg';
import putty from 'url:../../images/devicon/putty.svg';
import puttyPlain from 'url:../../images/devicon/putty-plain.svg';
import pycharm from 'url:../../images/devicon/pycharm.svg';
import pycharmOriginalWordmark from 'url:../../images/devicon/pycharm-original-wordmark.svg';
import pycharmPlain from 'url:../../images/devicon/pycharm-plain.svg';
import pycharmPlainWordmark from 'url:../../images/devicon/pycharm-plain-wordmark.svg';
import pytest from 'url:../../images/devicon/pytest.svg';
import pytestOriginalWordmark from 'url:../../images/devicon/pytest-original-wordmark.svg';
import pytestPlain from 'url:../../images/devicon/pytest-plain.svg';
import pytestPlainWordmark from 'url:../../images/devicon/pytest-plain-wordmark.svg';
import python from 'url:../../images/devicon/python.svg';
import pythonOriginalWordmark from 'url:../../images/devicon/python-original-wordmark.svg';
import pythonPlain from 'url:../../images/devicon/python-plain.svg';
import pythonPlainWordmark from 'url:../../images/devicon/python-plain-wordmark.svg';
import pytorch from 'url:../../images/devicon/pytorch.svg';
import pytorchOriginalWordmark from 'url:../../images/devicon/pytorch-original-wordmark.svg';
import pytorchPlainWordmark from 'url:../../images/devicon/pytorch-plain-wordmark.svg';
import qt from 'url:../../images/devicon/qt.svg';
import r from 'url:../../images/devicon/r.svg';
import rPlain from 'url:../../images/devicon/r-plain.svg';
import railsOriginalWordmark from 'url:../../images/devicon/rails-original-wordmark.svg';
import railsPlain from 'url:../../images/devicon/rails-plain.svg';
import railsPlainWordmark from 'url:../../images/devicon/rails-plain-wordmark.svg';
import raspberrypi from 'url:../../images/devicon/raspberrypi.svg';
import raspberrypiLine from 'url:../../images/devicon/raspberrypi-line.svg';
import raspberrypiLineWordmark from 'url:../../images/devicon/raspberrypi-line-wordmark.svg';
import raspberrypiOriginalWordmark from 'url:../../images/devicon/raspberrypi-original-wordmark.svg';
import react from 'url:../../images/devicon/react.svg';
import reactOriginalWordmark from 'url:../../images/devicon/react-original-wordmark.svg';
import rect from 'url:../../images/devicon/rect.svg';
import rectPlain from 'url:../../images/devicon/rect-plain.svg';
import redhat from 'url:../../images/devicon/redhat.svg';
import redhatOriginalWordmark from 'url:../../images/devicon/redhat-original-wordmark.svg';
import redhatPlain from 'url:../../images/devicon/redhat-plain.svg';
import redhatPlainWordmark from 'url:../../images/devicon/redhat-plain-wordmark.svg';
import redis from 'url:../../images/devicon/redis.svg';
import redisOriginalWordmark from 'url:../../images/devicon/redis-original-wordmark.svg';
import redisPlain from 'url:../../images/devicon/redis-plain.svg';
import redisPlainWordmark from 'url:../../images/devicon/redis-plain-wordmark.svg';
import redux from 'url:../../images/devicon/redux.svg';
import rocksdbPlain from 'url:../../images/devicon/rocksdb-plain.svg';
import rspec from 'url:../../images/devicon/rspec.svg';
import rspecOriginalWordmark from 'url:../../images/devicon/rspec-original-wordmark.svg';
import rstudio from 'url:../../images/devicon/rstudio.svg';
import rstudioPlain from 'url:../../images/devicon/rstudio-plain.svg';
import ruby from 'url:../../images/devicon/ruby.svg';
import rubyOriginalWordmark from 'url:../../images/devicon/ruby-original-wordmark.svg';
import rubyPlain from 'url:../../images/devicon/ruby-plain.svg';
import rubyPlainWordmark from 'url:../../images/devicon/ruby-plain-wordmark.svg';
import rubymine from 'url:../../images/devicon/rubymine.svg';
import rubymineOriginalWordmark from 'url:../../images/devicon/rubymine-original-wordmark.svg';
import rubyminePlain from 'url:../../images/devicon/rubymine-plain.svg';
import rubyminePlainWordmark from 'url:../../images/devicon/rubymine-plain-wordmark.svg';
import rustPlain from 'url:../../images/devicon/rust-plain.svg';
import safari from 'url:../../images/devicon/safari.svg';
import safariLine from 'url:../../images/devicon/safari-line.svg';
import safariLineWordmark from 'url:../../images/devicon/safari-line-wordmark.svg';
import safariOriginalWordmark from 'url:../../images/devicon/safari-original-wordmark.svg';
import safariPlain from 'url:../../images/devicon/safari-plain.svg';
import safariPlainWordmark from 'url:../../images/devicon/safari-plain-wordmark.svg';
import salesforce from 'url:../../images/devicon/salesforce.svg';
import salesforcePlain from 'url:../../images/devicon/salesforce-plain.svg';
import sass from 'url:../../images/devicon/sass.svg';
import scala from 'url:../../images/devicon/scala.svg';
import scalaOriginalWordmark from 'url:../../images/devicon/scala-original-wordmark.svg';
import scalaPlain from 'url:../../images/devicon/scala-plain.svg';
import scalaPlainWordmark from 'url:../../images/devicon/scala-plain-wordmark.svg';
import sdl from 'url:../../images/devicon/sdl.svg';
import sdlPlain from 'url:../../images/devicon/sdl-plain.svg';
import selenium from 'url:../../images/devicon/selenium.svg';
import sequelize from 'url:../../images/devicon/sequelize.svg';
import sequelizeOriginalWordmark from 'url:../../images/devicon/sequelize-original-wordmark.svg';
import sequelizePlain from 'url:../../images/devicon/sequelize-plain.svg';
import sequelizePlainWordmark from 'url:../../images/devicon/sequelize-plain-wordmark.svg';
import shopware from 'url:../../images/devicon/shopware.svg';
import shopwareOriginalWordmark from 'url:../../images/devicon/shopware-original-wordmark.svg';
import shotgrid from 'url:../../images/devicon/shotgrid.svg';
import shotgridOriginalWordmark from 'url:../../images/devicon/shotgrid-original-wordmark.svg';
import shotgridPlain from 'url:../../images/devicon/shotgrid-plain.svg';
import sketch from 'url:../../images/devicon/sketch.svg';
import sketchLine from 'url:../../images/devicon/sketch-line.svg';
import sketchLineWordmark from 'url:../../images/devicon/sketch-line-wordmark.svg';
import sketchOriginalWordmark from 'url:../../images/devicon/sketch-original-wordmark.svg';
import slack from 'url:../../images/devicon/slack.svg';
import slackOriginalWordmark from 'url:../../images/devicon/slack-original-wordmark.svg';
import slackPlain from 'url:../../images/devicon/slack-plain.svg';
import slackPlainWordmark from 'url:../../images/devicon/slack-plain-wordmark.svg';
import socketio from 'url:../../images/devicon/socketio.svg';
import socketioOriginalWordmark from 'url:../../images/devicon/socketio-original-wordmark.svg';
import solidity from 'url:../../images/devicon/solidity.svg';
import solidityPlain from 'url:../../images/devicon/solidity-plain.svg';
import sourcetree from 'url:../../images/devicon/sourcetree.svg';
import sourcetreeOriginalWordmark from 'url:../../images/devicon/sourcetree-original-wordmark.svg';
import spring from 'url:../../images/devicon/spring.svg';
import springOriginalWordmark from 'url:../../images/devicon/spring-original-wordmark.svg';
import springPlain from 'url:../../images/devicon/spring-plain.svg';
import springPlainWordmark from 'url:../../images/devicon/spring-plain-wordmark.svg';
import spss from 'url:../../images/devicon/spss.svg';
import spssPlain from 'url:../../images/devicon/spss-plain.svg';
import sqlalchemy from 'url:../../images/devicon/sqlalchemy.svg';
import sqlalchemyOriginalWordmark from 'url:../../images/devicon/sqlalchemy-original-wordmark.svg';
import sqlalchemyPlain from 'url:../../images/devicon/sqlalchemy-plain.svg';
import sqlite from 'url:../../images/devicon/sqlite.svg';
import sqliteOriginalWordmark from 'url:../../images/devicon/sqlite-original-wordmark.svg';
import sqlitePlain from 'url:../../images/devicon/sqlite-plain.svg';
import sqlitePlainWordmark from 'url:../../images/devicon/sqlite-plain-wordmark.svg';
import ssh from 'url:../../images/devicon/ssh.svg';
import sshOriginalWordmark from 'url:../../images/devicon/ssh-original-wordmark.svg';
import storybook from 'url:../../images/devicon/storybook.svg';
import storybookOriginalWordmark from 'url:../../images/devicon/storybook-original-wordmark.svg';
import storybookPlain from 'url:../../images/devicon/storybook-plain.svg';
import storybookPlainWordmark from 'url:../../images/devicon/storybook-plain-wordmark.svg';
import stylus from 'url:../../images/devicon/stylus.svg';
import subversion from 'url:../../images/devicon/subversion.svg';
import subversionOriginalWordmark from 'url:../../images/devicon/subversion-original-wordmark.svg';
import svelte from 'url:../../images/devicon/svelte.svg';
import svelteOriginalWordmark from 'url:../../images/devicon/svelte-original-wordmark.svg';
import sveltePlain from 'url:../../images/devicon/svelte-plain.svg';
import sveltePlainWordmark from 'url:../../images/devicon/svelte-plain-wordmark.svg';
import swift from 'url:../../images/devicon/swift.svg';
import swiftOriginalWordmark from 'url:../../images/devicon/swift-original-wordmark.svg';
import swiftPlain from 'url:../../images/devicon/swift-plain.svg';
import swiftPlainWordmark from 'url:../../images/devicon/swift-plain-wordmark.svg';
import symfony from 'url:../../images/devicon/symfony.svg';
import symfonyOriginalWordmark from 'url:../../images/devicon/symfony-original-wordmark.svg';
import tailwindcssOriginalWordmark from 'url:../../images/devicon/tailwindcss-original-wordmark.svg';
import tailwindcssPlain from 'url:../../images/devicon/tailwindcss-plain.svg';
import tensorflow from 'url:../../images/devicon/tensorflow.svg';
import tensorflowLine from 'url:../../images/devicon/tensorflow-line.svg';
import tensorflowLineWordmark from 'url:../../images/devicon/tensorflow-line-wordmark.svg';
import tensorflowOriginalWordmark from 'url:../../images/devicon/tensorflow-original-wordmark.svg';
import terraform from 'url:../../images/devicon/terraform.svg';
import terraformOriginalWordmark from 'url:../../images/devicon/terraform-original-wordmark.svg';
import terraformPlain from 'url:../../images/devicon/terraform-plain.svg';
import terraformPlainWordmark from 'url:../../images/devicon/terraform-plain-wordmark.svg';
import thealgorithms from 'url:../../images/devicon/thealgorithms.svg';
import thealgorithmsOriginalWordmark from 'url:../../images/devicon/thealgorithms-original-wordmark.svg';
import thealgorithmsPlain from 'url:../../images/devicon/thealgorithms-plain.svg';
import thealgorithmsPlainWordmark from 'url:../../images/devicon/thealgorithms-plain-wordmark.svg';
import threejs from 'url:../../images/devicon/threejs.svg';
import threejsOriginalWordmark from 'url:../../images/devicon/threejs-original-wordmark.svg';
import tomcat from 'url:../../images/devicon/tomcat.svg';
import tomcatLine from 'url:../../images/devicon/tomcat-line.svg';
import tomcatLineWordmark from 'url:../../images/devicon/tomcat-line-wordmark.svg';
import tomcatOriginalWordmark from 'url:../../images/devicon/tomcat-original-wordmark.svg';
import tortoisegit from 'url:../../images/devicon/tortoisegit.svg';
import tortoisegitLine from 'url:../../images/devicon/tortoisegit-line.svg';
import tortoisegitPlain from 'url:../../images/devicon/tortoisegit-plain.svg';
import towergit from 'url:../../images/devicon/towergit.svg';
import towergitOriginalWordmark from 'url:../../images/devicon/towergit-original-wordmark.svg';
import towergitPlain from 'url:../../images/devicon/towergit-plain.svg';
import towergitPlainWordmark from 'url:../../images/devicon/towergit-plain-wordmark.svg';
import travisPlain from 'url:../../images/devicon/travis-plain.svg';
import travisPlainWordmark from 'url:../../images/devicon/travis-plain-wordmark.svg';
import trelloPlain from 'url:../../images/devicon/trello-plain.svg';
import trelloPlainWordmark from 'url:../../images/devicon/trello-plain-wordmark.svg';
import twitter from 'url:../../images/devicon/twitter.svg';
import typescript from 'url:../../images/devicon/typescript.svg';
import typescriptPlain from 'url:../../images/devicon/typescript-plain.svg';
import typo3 from 'url:../../images/devicon/typo3.svg';
import typo3OriginalWordmark from 'url:../../images/devicon/typo3-original-wordmark.svg';
import typo3Plain from 'url:../../images/devicon/typo3-plain.svg';
import typo3PlainWordmark from 'url:../../images/devicon/typo3-plain-wordmark.svg';
import ubuntuPlain from 'url:../../images/devicon/ubuntu-plain.svg';
import ubuntuPlainWordmark from 'url:../../images/devicon/ubuntu-plain-wordmark.svg';
import unity from 'url:../../images/devicon/unity.svg';
import unityOriginalWordmark from 'url:../../images/devicon/unity-original-wordmark.svg';
import unix from 'url:../../images/devicon/unix.svg';
import unrealengine from 'url:../../images/devicon/unrealengine.svg';
import unrealengineOriginalWordmark from 'url:../../images/devicon/unrealengine-original-wordmark.svg';
import uwsgi from 'url:../../images/devicon/uwsgi.svg';
import uwsgiPlain from 'url:../../images/devicon/uwsgi-plain.svg';
import vagrant from 'url:../../images/devicon/vagrant.svg';
import vagrantOriginalWordmark from 'url:../../images/devicon/vagrant-original-wordmark.svg';
import vagrantPlain from 'url:../../images/devicon/vagrant-plain.svg';
import vagrantPlainWordmark from 'url:../../images/devicon/vagrant-plain-wordmark.svg';
import vim from 'url:../../images/devicon/vim.svg';
import vimPlain from 'url:../../images/devicon/vim-plain.svg';
import visualstudioPlain from 'url:../../images/devicon/visualstudio-plain.svg';
import visualstudioPlainWordmark from 'url:../../images/devicon/visualstudio-plain-wordmark.svg';
import vscode from 'url:../../images/devicon/vscode.svg';
import vscodeOriginalWordmark from 'url:../../images/devicon/vscode-original-wordmark.svg';
import vscodePlain from 'url:../../images/devicon/vscode-plain.svg';
import vscodePlainWordmark from 'url:../../images/devicon/vscode-plain-wordmark.svg';
import vuejs from 'url:../../images/devicon/vuejs.svg';
import vuejsLine from 'url:../../images/devicon/vuejs-line.svg';
import vuejsLineWordmark from 'url:../../images/devicon/vuejs-line-wordmark.svg';
import vuejsOriginalWordmark from 'url:../../images/devicon/vuejs-original-wordmark.svg';
import vuejsPlain from 'url:../../images/devicon/vuejs-plain.svg';
import vuejsPlainWordmark from 'url:../../images/devicon/vuejs-plain-wordmark.svg';
import vuestorefront from 'url:../../images/devicon/vuestorefront.svg';
import vuestorefrontPlain from 'url:../../images/devicon/vuestorefront-plain.svg';
import vuetify from 'url:../../images/devicon/vuetify.svg';
import vuetifyLine from 'url:../../images/devicon/vuetify-line.svg';
import vuetifyPlain from 'url:../../images/devicon/vuetify-plain.svg';
import webflow from 'url:../../images/devicon/webflow.svg';
import weblate from 'url:../../images/devicon/weblate.svg';
import weblateOriginalWordmark from 'url:../../images/devicon/weblate-original-wordmark.svg';
import weblatePlain from 'url:../../images/devicon/weblate-plain.svg';
import weblatePlainWordmark from 'url:../../images/devicon/weblate-plain-wordmark.svg';
import webpack from 'url:../../images/devicon/webpack.svg';
import webpackOriginalWordmark from 'url:../../images/devicon/webpack-original-wordmark.svg';
import webpackPlain from 'url:../../images/devicon/webpack-plain.svg';
import webpackPlainWordmark from 'url:../../images/devicon/webpack-plain-wordmark.svg';
import webstorm from 'url:../../images/devicon/webstorm.svg';
import webstormOriginalWordmark from 'url:../../images/devicon/webstorm-original-wordmark.svg';
import webstormPlain from 'url:../../images/devicon/webstorm-plain.svg';
import webstormPlainWordmark from 'url:../../images/devicon/webstorm-plain-wordmark.svg';
import windows8 from 'url:../../images/devicon/windows8.svg';
import windows8OriginalWordmark from 'url:../../images/devicon/windows8-original-wordmark.svg';
import woocommerce from 'url:../../images/devicon/woocommerce.svg';
import woocommerceOriginalWordmark from 'url:../../images/devicon/woocommerce-original-wordmark.svg';
import woocommercePlain from 'url:../../images/devicon/woocommerce-plain.svg';
import woocommercePlainWordmark from 'url:../../images/devicon/woocommerce-plain-wordmark.svg';
import wordpress from 'url:../../images/devicon/wordpress.svg';
import wordpressPlain from 'url:../../images/devicon/wordpress-plain.svg';
import wordpressPlainWordmark from 'url:../../images/devicon/wordpress-plain-wordmark.svg';
import xamarin from 'url:../../images/devicon/xamarin.svg';
import xamarinOriginalWordmark from 'url:../../images/devicon/xamarin-original-wordmark.svg';
import xcode from 'url:../../images/devicon/xcode.svg';
import xcodePlain from 'url:../../images/devicon/xcode-plain.svg';
import xdLine from 'url:../../images/devicon/xd-line.svg';
import xdPlain from 'url:../../images/devicon/xd-plain.svg';
import yarn from 'url:../../images/devicon/yarn.svg';
import yarnOriginalWordmark from 'url:../../images/devicon/yarn-original-wordmark.svg';
import yii from 'url:../../images/devicon/yii.svg';
import yiiOriginalWordmark from 'url:../../images/devicon/yii-original-wordmark.svg';
import yiiPlain from 'url:../../images/devicon/yii-plain.svg';
import yiiPlainWordmark from 'url:../../images/devicon/yii-plain-wordmark.svg';
import yunohost from 'url:../../images/devicon/yunohost.svg';
import yunohostPlain from 'url:../../images/devicon/yunohost-plain.svg';
import zendPlain from 'url:../../images/devicon/zend-plain.svg';
import zendPlainWordmark from 'url:../../images/devicon/zend-plain-wordmark.svg';
import zig from 'url:../../images/devicon/zig.svg';
import zigOriginalWordmark from 'url:../../images/devicon/zig-original-wordmark.svg';
import zigPlainWordmark from 'url:../../images/devicon/zig-plain-wordmark.svg';

export {
  aarch64,
  aarch64Plain,
  adonisjs,
  adonisjsOriginalWordmark,
  aftereffects,
  aftereffectsPlain,
  amazonwebservices,
  amazonwebservicesOriginalWordmark,
  amazonwebservicesPlainWordmark,
  anaconda,
  anacondaOriginalWordmark,
  android,
  androidOriginalWordmark,
  androidPlain,
  androidPlainWordmark,
  androidstudio,
  androidstudioOriginalWordmark,
  androidstudioPlain,
  androidstudioPlainWordmark,
  angularjs,
  angularjsOriginalWordmark,
  angularjsPlain,
  angularjsPlainWordmark,
  ansible,
  ansibleOriginalWordmark,
  ansiblePlain,
  ansiblePlainWordmark,
  apache,
  apacheLine,
  apacheLineWordmark,
  apacheOriginalWordmark,
  apachePlain,
  apachePlainWordmark,
  apachekafka,
  apachekafkaOriginalWordmark,
  appcelerator,
  appceleratorOriginalWordmark,
  appceleratorPlainWordmark,
  apple,
  appwrite,
  appwriteOriginalWordmark,
  appwritePlain,
  appwritePlainWordmark,
  arduino,
  arduinoOriginalWordmark,
  arduinoPlain,
  arduinoPlainWordmark,
  argocd,
  argocdOriginalWordmark,
  argocdPlain,
  argocdPlainWordmark,
  atom,
  atomOriginalWordmark,
  azure,
  azureOriginalWordmark,
  azurePlain,
  azurePlainWordmark,
  babel,
  babelPlain,
  backbonejs,
  backbonejsOriginalWordmark,
  backbonejsPlain,
  backbonejsPlainWordmark,
  bamboo,
  bambooOriginalWordmark,
  bash,
  bashPlain,
  behance,
  behanceOriginalWordmark,
  behancePlain,
  behancePlainWordmark,
  bitbucket,
  bitbucketOriginalWordmark,
  blender,
  blenderOriginalWordmark,
  bootstrap,
  bootstrapOriginalWordmark,
  bootstrapPlain,
  bootstrapPlainWordmark,
  bower,
  bowerLine,
  bowerLineWordmark,
  bowerOriginalWordmark,
  bowerPlain,
  bowerPlainWordmark,
  bulmaPlain,
  c,
  cLine,
  cPlain,
  cakephp,
  cakephpOriginalWordmark,
  cakephpPlain,
  cakephpPlainWordmark,
  canva,
  centos,
  centosOriginalWordmark,
  centosPlain,
  centosPlainWordmark,
  ceylon,
  ceylonOriginalWordmark,
  ceylonPlain,
  ceylonPlainWordmark,
  chrome,
  chromeOriginalWordmark,
  chromePlain,
  chromePlainWordmark,
  circleciPlain,
  circleciPlainWordmark,
  clojure,
  clojureLine,
  clojurescript,
  clojurescriptPlain,
  cmake,
  cmakeOriginalWordmark,
  cmakePlain,
  cmakePlainWordmark,
  codecovPlain,
  codeigniterPlain,
  codeigniterPlainWordmark,
  codepenOriginalWordmark,
  codepenPlain,
  coffeescript,
  coffeescriptOriginalWordmark,
  composer,
  composerLine,
  composerLineWordmark,
  confluence,
  confluenceOriginalWordmark,
  couchdb,
  couchdbOriginalWordmark,
  couchdbPlain,
  couchdbPlainWordmark,
  cplusplus,
  cplusplusLine,
  cplusplusPlain,
  crystal,
  crystalOriginalWordmark,
  csharp,
  csharpLine,
  csharpPlain,
  css3,
  css3OriginalWordmark,
  css3Plain,
  css3PlainWordmark,
  cucumberPlain,
  cucumberPlainWordmark,
  d3Js,
  d3JsPlain,
  dart,
  dartOriginalWordmark,
  dartPlain,
  dartPlainWordmark,
  debian,
  debianOriginalWordmark,
  debianPlain,
  debianPlainWordmark,
  denojs,
  denojsOriginalWordmark,
  devicon,
  deviconLine,
  deviconLineWordmark,
  deviconOriginalWordmark,
  deviconPlain,
  deviconPlainWordmark,
  digitalocean,
  digitaloceanOriginalWordmark,
  digitaloceanPlain,
  digitaloceanPlainWordmark,
  discordjs,
  discordjsOriginalWordmark,
  discordjsPlain,
  discordjsPlainWordmark,
  djangoPlain,
  djangoPlainWordmark,
  docker,
  dockerOriginalWordmark,
  dockerPlain,
  dockerPlainWordmark,
  doctrine,
  doctrineLine,
  doctrineLineWordmark,
  doctrineOriginalWordmark,
  doctrinePlain,
  doctrinePlainWordmark,
  dotNet,
  dotNetOriginalWordmark,
  dotNetPlain,
  dotNetPlainWordmark,
  dotnetcore,
  dotnetcorePlain,
  dropwizard,
  dropwizardPlain,
  drupal,
  drupalOriginalWordmark,
  drupalPlain,
  drupalPlainWordmark,
  electron,
  electronOriginalWordmark,
  eleventy,
  eleventyPlain,
  elixir,
  elixirOriginalWordmark,
  elixirPlain,
  elixirPlainWordmark,
  elm,
  elmOriginalWordmark,
  elmPlain,
  elmPlainWordmark,
  embeddedc,
  embeddedcOriginalWordmark,
  embeddedcPlain,
  embeddedcPlainWordmark,
  emberOriginalWordmark,
  erlang,
  erlangOriginalWordmark,
  erlangPlain,
  erlangPlainWordmark,
  eslint,
  eslintOriginalWordmark,
  express,
  expressOriginalWordmark,
  facebook,
  facebookPlain,
  fastapi,
  fastapiOriginalWordmark,
  fastapiPlain,
  fastapiPlainWordmark,
  feathersjs,
  fedora,
  fedoraPlain,
  figma,
  figmaPlain,
  filezillaPlain,
  filezillaPlainWordmark,
  firebasePlain,
  firebasePlainWordmark,
  firefox,
  firefoxOriginalWordmark,
  firefoxPlain,
  firefoxPlainWordmark,
  flask,
  flaskOriginalWordmark,
  flutter,
  flutterPlain,
  foundation,
  foundationOriginalWordmark,
  foundationPlain,
  foundationPlainWordmark,
  fsharp,
  fsharpPlain,
  gatlingPlain,
  gatlingPlainWordmark,
  gatsby,
  gatsbyOriginalWordmark,
  gatsbyPlain,
  gatsbyPlainWordmark,
  gcc,
  gccPlain,
  gentooPlain,
  gentooPlainWordmark,
  gimp,
  gimpOriginalWordmark,
  gimpPlain,
  gimpPlainWordmark,
  git,
  gitOriginalWordmark,
  gitPlain,
  gitPlainWordmark,
  github,
  githubOriginalWordmark,
  gitlab,
  gitlabOriginalWordmark,
  gitlabPlain,
  gitlabPlainWordmark,
  gitterPlain,
  gitterPlainWordmark,
  go,
  goLine,
  goOriginalWordmark,
  goPlain,
  godot,
  godotOriginalWordmark,
  godotPlain,
  godotPlainWordmark,
  google,
  googleOriginalWordmark,
  googlePlain,
  googlePlainWordmark,
  googlecloud,
  googlecloudOriginalWordmark,
  googlecloudPlain,
  googlecloudPlainWordmark,
  gradlePlain,
  gradlePlainWordmark,
  grafana,
  grafanaOriginalWordmark,
  grails,
  grailsPlain,
  graphqlPlain,
  graphqlPlainWordmark,
  groovy,
  groovyPlain,
  grunt,
  gruntLine,
  gruntLineWordmark,
  gruntOriginalWordmark,
  gruntPlain,
  gruntPlainWordmark,
  gulpPlain,
  handlebars,
  handlebarsOriginalWordmark,
  haskell,
  haskellOriginalWordmark,
  haskellPlain,
  haskellPlainWordmark,
  haxe,
  haxePlain,
  heroku,
  herokuOriginalWordmark,
  herokuPlain,
  herokuPlainWordmark,
  html5,
  html5OriginalWordmark,
  html5Plain,
  html5PlainWordmark,
  hugo,
  hugoOriginalWordmark,
  hugoPlain,
  hugoPlainWordmark,
  ie10,
  ifttt,
  illustratorLine,
  illustratorPlain,
  inkscape,
  inkscapeOriginalWordmark,
  inkscapePlain,
  inkscapePlainWordmark,
  intellij,
  intellijOriginalWordmark,
  intellijPlain,
  intellijPlainWordmark,
  ionic,
  ionicOriginalWordmark,
  jamstack,
  jamstackOriginalWordmark,
  jamstackPlainWordmark,
  jasminePlain,
  jasminePlainWordmark,
  java,
  javaOriginalWordmark,
  javaPlain,
  javaPlainWordmark,
  javascript,
  javascriptPlain,
  jeet,
  jeetOriginalWordmark,
  jeetPlain,
  jeetPlainWordmark,
  jenkins,
  jenkinsLine,
  jenkinsPlain,
  jestPlain,
  jetbrains,
  jetbrainsPlain,
  jira,
  jiraOriginalWordmark,
  jiraPlain,
  jiraPlainWordmark,
  jquery,
  jqueryOriginalWordmark,
  jqueryPlain,
  jqueryPlainWordmark,
  julia,
  juliaOriginalWordmark,
  juliaPlain,
  juliaPlainWordmark,
  jupyter,
  jupyterOriginalWordmark,
  jupyterPlain,
  jupyterPlainWordmark,
  k3S,
  k3SOriginalWordmark,
  k3SPlainWordmark,
  kaggle,
  kaggleOriginalWordmark,
  karma,
  karmaPlain,
  knockoutPlainWordmark,
  kotlin,
  kotlinOriginalWordmark,
  kotlinPlain,
  kotlinPlainWordmark,
  krakenjs,
  krakenjsOriginalWordmark,
  krakenjsPlain,
  krakenjsPlainWordmark,
  kubernetesPlain,
  kubernetesPlainWordmark,
  labview,
  labviewOriginalWordmark,
  labviewPlain,
  labviewPlainWordmark,
  laravelPlain,
  laravelPlainWordmark,
  latex,
  lessPlainWordmark,
  linkedin,
  linkedinOriginalWordmark,
  linkedinPlain,
  linkedinPlainWordmark,
  linux,
  linuxPlain,
  lua,
  luaOriginalWordmark,
  luaPlain,
  luaPlainWordmark,
  magento,
  magentoLine,
  magentoOriginalWordmark,
  markdown,
  materialui,
  materialuiPlain,
  matlab,
  matlabLine,
  matlabPlain,
  maya,
  mayaOriginalWordmark,
  mayaPlain,
  mayaPlainWordmark,
  meteor,
  meteorOriginalWordmark,
  meteorPlain,
  meteorPlainWordmark,
  microsoftsqlserverPlain,
  microsoftsqlserverPlainWordmark,
  minitab,
  minitabPlain,
  mochaPlain,
  modx,
  modxOriginalWordmark,
  modxPlain,
  modxPlainWordmark,
  mongodb,
  mongodbOriginalWordmark,
  mongodbPlain,
  mongodbPlainWordmark,
  moodle,
  moodleOriginalWordmark,
  moodlePlain,
  moodlePlainWordmark,
  msdos,
  msdosLine,
  msdosPlain,
  mysql,
  mysqlOriginalWordmark,
  mysqlPlain,
  mysqlPlainWordmark,
  neo4J,
  neo4JOriginalWordmark,
  neo4JPlain,
  neo4JPlainWordmark,
  nestjsPlain,
  nestjsPlainWordmark,
  networkx,
  nextjs,
  nextjsLine,
  nextjsOriginalWordmark,
  nginx,
  nixos,
  nixosOriginalWordmark,
  nixosPlain,
  nixosPlainWordmark,
  nodejs,
  nodejsOriginalWordmark,
  nodejsPlain,
  nodejsPlainWordmark,
  nodewebkit,
  nodewebkitLine,
  nodewebkitLineWordmark,
  nodewebkitOriginalWordmark,
  nodewebkitPlain,
  nodewebkitPlainWordmark,
  npmOriginalWordmark,
  nuget,
  nugetOriginalWordmark,
  numpy,
  numpyOriginalWordmark,
  nuxtjs,
  nuxtjsOriginalWordmark,
  nuxtjsPlain,
  nuxtjsPlainWordmark,
  objectivecPlain,
  ocaml,
  ocamlOriginalWordmark,
  ocamlPlain,
  ocamlPlainWordmark,
  openal,
  openalPlain,
  opencv,
  opencvOriginalWordmark,
  opencvPlain,
  opencvPlainWordmark,
  opengl,
  openglPlain,
  opensuse,
  opensuseOriginalWordmark,
  opensusePlain,
  opensusePlainWordmark,
  opera,
  operaOriginalWordmark,
  operaPlain,
  operaPlainWordmark,
  oracle,
  packer,
  packerOriginalWordmark,
  pandas,
  pandasOriginalWordmark,
  perl,
  perlPlain,
  phalcon,
  phalconPlain,
  phoenix,
  phoenixOriginalWordmark,
  phoenixPlain,
  phoenixPlainWordmark,
  photoshopLine,
  photoshopPlain,
  php,
  phpPlain,
  phpstorm,
  phpstormOriginalWordmark,
  phpstormPlain,
  phpstormPlainWordmark,
  podman,
  podmanOriginalWordmark,
  podmanPlain,
  podmanPlainWordmark,
  polygon,
  polygonPlain,
  postgresql,
  postgresqlOriginalWordmark,
  postgresqlPlain,
  postgresqlPlainWordmark,
  premierepro,
  premiereproPlain,
  processing,
  processingOriginalWordmark,
  processingPlain,
  processingPlainWordmark,
  prometheus,
  prometheusOriginalWordmark,
  protractorPlain,
  protractorPlainWordmark,
  putty,
  puttyPlain,
  pycharm,
  pycharmOriginalWordmark,
  pycharmPlain,
  pycharmPlainWordmark,
  pytest,
  pytestOriginalWordmark,
  pytestPlain,
  pytestPlainWordmark,
  python,
  pythonOriginalWordmark,
  pythonPlain,
  pythonPlainWordmark,
  pytorch,
  pytorchOriginalWordmark,
  pytorchPlainWordmark,
  qt,
  r,
  rPlain,
  railsOriginalWordmark,
  railsPlain,
  railsPlainWordmark,
  raspberrypi,
  raspberrypiLine,
  raspberrypiLineWordmark,
  raspberrypiOriginalWordmark,
  react,
  reactOriginalWordmark,
  rect,
  rectPlain,
  redhat,
  redhatOriginalWordmark,
  redhatPlain,
  redhatPlainWordmark,
  redis,
  redisOriginalWordmark,
  redisPlain,
  redisPlainWordmark,
  redux,
  rocksdbPlain,
  rspec,
  rspecOriginalWordmark,
  rstudio,
  rstudioPlain,
  ruby,
  rubyOriginalWordmark,
  rubyPlain,
  rubyPlainWordmark,
  rubymine,
  rubymineOriginalWordmark,
  rubyminePlain,
  rubyminePlainWordmark,
  rustPlain,
  safari,
  safariLine,
  safariLineWordmark,
  safariOriginalWordmark,
  safariPlain,
  safariPlainWordmark,
  salesforce,
  salesforcePlain,
  sass,
  scala,
  scalaOriginalWordmark,
  scalaPlain,
  scalaPlainWordmark,
  sdl,
  sdlPlain,
  selenium,
  sequelize,
  sequelizeOriginalWordmark,
  sequelizePlain,
  sequelizePlainWordmark,
  shopware,
  shopwareOriginalWordmark,
  shotgrid,
  shotgridOriginalWordmark,
  shotgridPlain,
  sketch,
  sketchLine,
  sketchLineWordmark,
  sketchOriginalWordmark,
  slack,
  slackOriginalWordmark,
  slackPlain,
  slackPlainWordmark,
  socketio,
  socketioOriginalWordmark,
  solidity,
  solidityPlain,
  sourcetree,
  sourcetreeOriginalWordmark,
  spring,
  springOriginalWordmark,
  springPlain,
  springPlainWordmark,
  spss,
  spssPlain,
  sqlalchemy,
  sqlalchemyOriginalWordmark,
  sqlalchemyPlain,
  sqlite,
  sqliteOriginalWordmark,
  sqlitePlain,
  sqlitePlainWordmark,
  ssh,
  sshOriginalWordmark,
  storybook,
  storybookOriginalWordmark,
  storybookPlain,
  storybookPlainWordmark,
  stylus,
  subversion,
  subversionOriginalWordmark,
  svelte,
  svelteOriginalWordmark,
  sveltePlain,
  sveltePlainWordmark,
  swift,
  swiftOriginalWordmark,
  swiftPlain,
  swiftPlainWordmark,
  symfony,
  symfonyOriginalWordmark,
  tailwindcssOriginalWordmark,
  tailwindcssPlain,
  tensorflow,
  tensorflowLine,
  tensorflowLineWordmark,
  tensorflowOriginalWordmark,
  terraform,
  terraformOriginalWordmark,
  terraformPlain,
  terraformPlainWordmark,
  thealgorithms,
  thealgorithmsOriginalWordmark,
  thealgorithmsPlain,
  thealgorithmsPlainWordmark,
  threejs,
  threejsOriginalWordmark,
  tomcat,
  tomcatLine,
  tomcatLineWordmark,
  tomcatOriginalWordmark,
  tortoisegit,
  tortoisegitLine,
  tortoisegitPlain,
  towergit,
  towergitOriginalWordmark,
  towergitPlain,
  towergitPlainWordmark,
  travisPlain,
  travisPlainWordmark,
  trelloPlain,
  trelloPlainWordmark,
  twitter,
  typescript,
  typescriptPlain,
  typo3,
  typo3OriginalWordmark,
  typo3Plain,
  typo3PlainWordmark,
  ubuntuPlain,
  ubuntuPlainWordmark,
  unity,
  unityOriginalWordmark,
  unix,
  unrealengine,
  unrealengineOriginalWordmark,
  uwsgi,
  uwsgiPlain,
  vagrant,
  vagrantOriginalWordmark,
  vagrantPlain,
  vagrantPlainWordmark,
  vim,
  vimPlain,
  visualstudioPlain,
  visualstudioPlainWordmark,
  vscode,
  vscodeOriginalWordmark,
  vscodePlain,
  vscodePlainWordmark,
  vuejs,
  vuejsLine,
  vuejsLineWordmark,
  vuejsOriginalWordmark,
  vuejsPlain,
  vuejsPlainWordmark,
  vuestorefront,
  vuestorefrontPlain,
  vuetify,
  vuetifyLine,
  vuetifyPlain,
  webflow,
  weblate,
  weblateOriginalWordmark,
  weblatePlain,
  weblatePlainWordmark,
  webpack,
  webpackOriginalWordmark,
  webpackPlain,
  webpackPlainWordmark,
  webstorm,
  webstormOriginalWordmark,
  webstormPlain,
  webstormPlainWordmark,
  windows8,
  windows8OriginalWordmark,
  woocommerce,
  woocommerceOriginalWordmark,
  woocommercePlain,
  woocommercePlainWordmark,
  wordpress,
  wordpressPlain,
  wordpressPlainWordmark,
  xamarin,
  xamarinOriginalWordmark,
  xcode,
  xcodePlain,
  xdLine,
  xdPlain,
  yarn,
  yarnOriginalWordmark,
  yii,
  yiiOriginalWordmark,
  yiiPlain,
  yiiPlainWordmark,
  yunohost,
  yunohostPlain,
  zendPlain,
  zendPlainWordmark,
  zig,
  zigOriginalWordmark,
  zigPlainWordmark,
};
