// !!! DO NOT EDIT !!! -- automatically generated by scripts/assets.js

import aiplatform from 'url:../../images/gcp/aiplatform.svg';
import apianalytics from 'url:../../images/gcp/apianalytics.svg';
import apigeeapiplatform from 'url:../../images/gcp/apigeeapiplatform.svg';
import apigeesense from 'url:../../images/gcp/apigeesense.svg';
import apimonetization from 'url:../../images/gcp/apimonetization.svg';
import apis from 'url:../../images/gcp/apis.svg';
import appengine from 'url:../../images/gcp/appengine.svg';
import armor from 'url:../../images/gcp/armor.svg';
import artifactRegistry from 'url:../../images/gcp/artifact-registry.svg';
import automl from 'url:../../images/gcp/automl.svg';
import beyondcorp from 'url:../../images/gcp/beyondcorp.svg';
import bigquery from 'url:../../images/gcp/bigquery.svg';
import bigtable from 'url:../../images/gcp/bigtable.svg';
import build from 'url:../../images/gcp/build.svg';
import cdn from 'url:../../images/gcp/cdn.svg';
import cloudDebugger from 'url:../../images/gcp/cloud-debugger.svg';
import composer from 'url:../../images/gcp/composer.svg';
import computeEngine from 'url:../../images/gcp/compute-engine.svg';
import containerOptimizedOs from 'url:../../images/gcp/container-optimized-os.svg';
import dataLab from 'url:../../images/gcp/data-lab.svg';
import dataLossPreventionApi from 'url:../../images/gcp/data-loss-prevention-api.svg';
import dataStudio from 'url:../../images/gcp/data-studio.svg';
import dataflow from 'url:../../images/gcp/dataflow.svg';
import dataprep from 'url:../../images/gcp/dataprep.svg';
import dataproc from 'url:../../images/gcp/dataproc.svg';
import datastore from 'url:../../images/gcp/datastore.svg';
import deploymentManager from 'url:../../images/gcp/deployment-manager.svg';
import developerPortal from 'url:../../images/gcp/developer-portal.svg';
import dialogflow from 'url:../../images/gcp/dialogflow.svg';
import dns from 'url:../../images/gcp/dns.svg';
import eTpu from 'url:../../images/gcp/e-tpu.svg';
import endpoints from 'url:../../images/gcp/endpoints.svg';
import errorReporting from 'url:../../images/gcp/error-reporting.svg';
import externalIpAddresses from 'url:../../images/gcp/external-ip-addresses.svg';
import filestore from 'url:../../images/gcp/filestore.svg';
import firewallRules from 'url:../../images/gcp/firewall-rules.svg';
import functions from 'url:../../images/gcp/functions.svg';
import generic from 'url:../../images/gcp/generic.svg';
import genomics from 'url:../../images/gcp/genomics.svg';
import gke from 'url:../../images/gcp/gke.svg';
import gkeOnPrem from 'url:../../images/gcp/gke-on-prem.svg';
import gpu from 'url:../../images/gcp/gpu.svg';
import iam from 'url:../../images/gcp/iam.svg';
import interconnect from 'url:../../images/gcp/interconnect.svg';
import iotCore from 'url:../../images/gcp/iot-core.svg';
import jobsApi from 'url:../../images/gcp/jobs-api.svg';
import keyAccessJustifications from 'url:../../images/gcp/key-access-justifications.svg';
import loadBalancing from 'url:../../images/gcp/load-balancing.svg';
import logging from 'url:../../images/gcp/logging.svg';
import memorystore from 'url:../../images/gcp/memorystore.svg';
import monitoring from 'url:../../images/gcp/monitoring.svg';
import naturalLanguageApi from 'url:../../images/gcp/natural-language-api.svg';
import network from 'url:../../images/gcp/network.svg';
import partnerInterconnect from 'url:../../images/gcp/partner-interconnect.svg';
import persistentDisk from 'url:../../images/gcp/persistent-disk.svg';
import premiumNetworkTier from 'url:../../images/gcp/premium-network-tier.svg';
import pubSub from 'url:../../images/gcp/pub_sub.svg';
import router from 'url:../../images/gcp/router.svg';
import routes from 'url:../../images/gcp/routes.svg';
import securityCommandCenter from 'url:../../images/gcp/security-command-center.svg';
import spanner from 'url:../../images/gcp/spanner.svg';
import speechToText from 'url:../../images/gcp/speech-to-text.svg';
import sql from 'url:../../images/gcp/sql.svg';
import stackdriver from 'url:../../images/gcp/stackdriver.svg';
import standardNetworkTier from 'url:../../images/gcp/standard-network-tier.svg';
import storage from 'url:../../images/gcp/storage.svg';
import textToSpeech from 'url:../../images/gcp/text-to-speech.svg';
import toolsForPowershell from 'url:../../images/gcp/tools-for-powershell.svg';
import trace from 'url:../../images/gcp/trace.svg';
import transferAppliance from 'url:../../images/gcp/transfer-appliance.svg';
import translationApi from 'url:../../images/gcp/translation-api.svg';
import videoIntelligenceApi from 'url:../../images/gcp/video-intelligence-api.svg';
import virtualPrivateCloud from 'url:../../images/gcp/virtual-private-cloud.svg';
import visionApi from 'url:../../images/gcp/vision-api.svg';
import vpn from 'url:../../images/gcp/vpn.svg';
import webSecurityScanner from 'url:../../images/gcp/web-security-scanner.svg';

export {
  aiplatform,
  apianalytics,
  apigeeapiplatform,
  apigeesense,
  apimonetization,
  apis,
  appengine,
  armor,
  artifactRegistry,
  automl,
  beyondcorp,
  bigquery,
  bigtable,
  build,
  cdn,
  cloudDebugger,
  composer,
  computeEngine,
  containerOptimizedOs,
  dataLab,
  dataLossPreventionApi,
  dataStudio,
  dataflow,
  dataprep,
  dataproc,
  datastore,
  deploymentManager,
  developerPortal,
  dialogflow,
  dns,
  eTpu,
  endpoints,
  errorReporting,
  externalIpAddresses,
  filestore,
  firewallRules,
  functions,
  generic,
  genomics,
  gke,
  gkeOnPrem,
  gpu,
  iam,
  interconnect,
  iotCore,
  jobsApi,
  keyAccessJustifications,
  loadBalancing,
  logging,
  memorystore,
  monitoring,
  naturalLanguageApi,
  network,
  partnerInterconnect,
  persistentDisk,
  premiumNetworkTier,
  pubSub,
  router,
  routes,
  securityCommandCenter,
  spanner,
  speechToText,
  sql,
  stackdriver,
  standardNetworkTier,
  storage,
  textToSpeech,
  toolsForPowershell,
  trace,
  transferAppliance,
  translationApi,
  videoIntelligenceApi,
  virtualPrivateCloud,
  visionApi,
  vpn,
  webSecurityScanner,
};
