// !!! DO NOT EDIT !!! -- automatically generated by scripts/assets.js

import aiplatform from '../../images/gcp/aiplatform.svg';
import apianalytics from '../../images/gcp/apianalytics.svg';
import apigeeapiplatform from '../../images/gcp/apigeeapiplatform.svg';
import apigeesense from '../../images/gcp/apigeesense.svg';
import apimonetization from '../../images/gcp/apimonetization.svg';
import apis from '../../images/gcp/apis.svg';
import appengine from '../../images/gcp/appengine.svg';
import armor from '../../images/gcp/armor.svg';
import artifactRegistry from '../../images/gcp/artifact-registry.svg';
import automl from '../../images/gcp/automl.svg';
import beyondcorp from '../../images/gcp/beyondcorp.svg';
import bigquery from '../../images/gcp/bigquery.svg';
import bigtable from '../../images/gcp/bigtable.svg';
import build from '../../images/gcp/build.svg';
import cdn from '../../images/gcp/cdn.svg';
import cloudDebugger from '../../images/gcp/cloud-debugger.svg';
import composer from '../../images/gcp/composer.svg';
import computeEngine from '../../images/gcp/compute-engine.svg';
import containerOptimizedOs from '../../images/gcp/container-optimized-os.svg';
import dataLab from '../../images/gcp/data-lab.svg';
import dataLossPreventionApi from '../../images/gcp/data-loss-prevention-api.svg';
import dataStudio from '../../images/gcp/data-studio.svg';
import dataflow from '../../images/gcp/dataflow.svg';
import dataprep from '../../images/gcp/dataprep.svg';
import dataproc from '../../images/gcp/dataproc.svg';
import datastore from '../../images/gcp/datastore.svg';
import deploymentManager from '../../images/gcp/deployment-manager.svg';
import developerPortal from '../../images/gcp/developer-portal.svg';
import dialogflow from '../../images/gcp/dialogflow.svg';
import dns from '../../images/gcp/dns.svg';
import eTpu from '../../images/gcp/e-tpu.svg';
import endpoints from '../../images/gcp/endpoints.svg';
import errorReporting from '../../images/gcp/error-reporting.svg';
import externalIpAddresses from '../../images/gcp/external-ip-addresses.svg';
import filestore from '../../images/gcp/filestore.svg';
import firewallRules from '../../images/gcp/firewall-rules.svg';
import functions from '../../images/gcp/functions.svg';
import generic from '../../images/gcp/generic.svg';
import genomics from '../../images/gcp/genomics.svg';
import gke from '../../images/gcp/gke.svg';
import gkeOnPrem from '../../images/gcp/gke-on-prem.svg';
import gpu from '../../images/gcp/gpu.svg';
import iam from '../../images/gcp/iam.svg';
import interconnect from '../../images/gcp/interconnect.svg';
import iotCore from '../../images/gcp/iot-core.svg';
import jobsApi from '../../images/gcp/jobs-api.svg';
import keyAccessJustifications from '../../images/gcp/key-access-justifications.svg';
import loadBalancing from '../../images/gcp/load-balancing.svg';
import logging from '../../images/gcp/logging.svg';
import memorystore from '../../images/gcp/memorystore.svg';
import monitoring from '../../images/gcp/monitoring.svg';
import naturalLanguageApi from '../../images/gcp/natural-language-api.svg';
import network from '../../images/gcp/network.svg';
import partnerInterconnect from '../../images/gcp/partner-interconnect.svg';
import persistentDisk from '../../images/gcp/persistent-disk.svg';
import premiumNetworkTier from '../../images/gcp/premium-network-tier.svg';
import pubSub from '../../images/gcp/pub_sub.svg';
import router from '../../images/gcp/router.svg';
import routes from '../../images/gcp/routes.svg';
import securityCommandCenter from '../../images/gcp/security-command-center.svg';
import spanner from '../../images/gcp/spanner.svg';
import speechToText from '../../images/gcp/speech-to-text.svg';
import sql from '../../images/gcp/sql.svg';
import stackdriver from '../../images/gcp/stackdriver.svg';
import standardNetworkTier from '../../images/gcp/standard-network-tier.svg';
import storage from '../../images/gcp/storage.svg';
import textToSpeech from '../../images/gcp/text-to-speech.svg';
import toolsForPowershell from '../../images/gcp/tools-for-powershell.svg';
import trace from '../../images/gcp/trace.svg';
import transferAppliance from '../../images/gcp/transfer-appliance.svg';
import translationApi from '../../images/gcp/translation-api.svg';
import videoIntelligenceApi from '../../images/gcp/video-intelligence-api.svg';
import virtualPrivateCloud from '../../images/gcp/virtual-private-cloud.svg';
import visionApi from '../../images/gcp/vision-api.svg';
import vpn from '../../images/gcp/vpn.svg';
import webSecurityScanner from '../../images/gcp/web-security-scanner.svg';

export {
  aiplatform,
  apianalytics,
  apigeeapiplatform,
  apigeesense,
  apimonetization,
  apis,
  appengine,
  armor,
  artifactRegistry,
  automl,
  beyondcorp,
  bigquery,
  bigtable,
  build,
  cdn,
  cloudDebugger,
  composer,
  computeEngine,
  containerOptimizedOs,
  dataLab,
  dataLossPreventionApi,
  dataStudio,
  dataflow,
  dataprep,
  dataproc,
  datastore,
  deploymentManager,
  developerPortal,
  dialogflow,
  dns,
  eTpu,
  endpoints,
  errorReporting,
  externalIpAddresses,
  filestore,
  firewallRules,
  functions,
  generic,
  genomics,
  gke,
  gkeOnPrem,
  gpu,
  iam,
  interconnect,
  iotCore,
  jobsApi,
  keyAccessJustifications,
  loadBalancing,
  logging,
  memorystore,
  monitoring,
  naturalLanguageApi,
  network,
  partnerInterconnect,
  persistentDisk,
  premiumNetworkTier,
  pubSub,
  router,
  routes,
  securityCommandCenter,
  spanner,
  speechToText,
  sql,
  stackdriver,
  standardNetworkTier,
  storage,
  textToSpeech,
  toolsForPowershell,
  trace,
  transferAppliance,
  translationApi,
  videoIntelligenceApi,
  virtualPrivateCloud,
  visionApi,
  vpn,
  webSecurityScanner,
};
