// !!! DO NOT EDIT !!! -- automatically generated by scripts/assets.js

import browser from 'url:../../images/generic/browser.svg';
import cassandra from 'url:../../images/generic/cassandra.svg';
import component from 'url:../../images/generic/component.svg';
import consul from 'url:../../images/generic/consul.svg';
import elasticsearch from 'url:../../images/generic/elasticsearch.svg';
import firebase from 'url:../../images/generic/firebase.svg';
import kafka from 'url:../../images/generic/kafka.svg';
import mariadb from 'url:../../images/generic/mariadb.svg';
import mongodb from 'url:../../images/generic/mongodb.svg';
import mysql from 'url:../../images/generic/mysql.svg';
import nomad from 'url:../../images/generic/nomad.svg';
import postgres from 'url:../../images/generic/postgres.svg';
import user from 'url:../../images/generic/user.svg';
import users from 'url:../../images/generic/users.svg';
import vault from 'url:../../images/generic/vault.svg';

export {
  browser,
  cassandra,
  component,
  consul,
  elasticsearch,
  firebase,
  kafka,
  mariadb,
  mongodb,
  mysql,
  nomad,
  postgres,
  user,
  users,
  vault,
};
