// !!! DO NOT EDIT !!! -- automatically generated by scripts/assets.js

import cassandra from '../../images/generic/cassandra.svg';
import consul from '../../images/generic/consul.svg';
import elasticsearch from '../../images/generic/elasticsearch.svg';
import generic from '../../images/generic/generic.svg';
import kafka from '../../images/generic/kafka.svg';
import mariadb from '../../images/generic/mariadb.svg';
import mongodb from '../../images/generic/mongodb.svg';
import mysql from '../../images/generic/mysql.svg';
import nomad from '../../images/generic/nomad.svg';
import postgres from '../../images/generic/postgres.svg';
import user from '../../images/generic/user.svg';
import users from '../../images/generic/users.svg';
import vault from '../../images/generic/vault.svg';

export {cassandra, consul, elasticsearch, generic, kafka, mariadb, mongodb, mysql, nomad, postgres, user, users, vault};
