// !!! DO NOT EDIT !!! -- automatically generated by scripts/assets.js

import cRole from '../../images/k8s/c-role.svg';
import cm from '../../images/k8s/cm.svg';
import crb from '../../images/k8s/crb.svg';
import crd from '../../images/k8s/crd.svg';
import cronjob from '../../images/k8s/cronjob.svg';
import deploy from '../../images/k8s/deploy.svg';
import ds from '../../images/k8s/ds.svg';
import ep from '../../images/k8s/ep.svg';
import etcd from '../../images/k8s/etcd.svg';
import group from '../../images/k8s/group.svg';
import hpa from '../../images/k8s/hpa.svg';
import ing from '../../images/k8s/ing.svg';
import job from '../../images/k8s/job.svg';
import limits from '../../images/k8s/limits.svg';
import master from '../../images/k8s/master.svg';
import netpol from '../../images/k8s/netpol.svg';
import node from '../../images/k8s/node.svg';
import ns from '../../images/k8s/ns.svg';
import pod from '../../images/k8s/pod.svg';
import psp from '../../images/k8s/psp.svg';
import pv from '../../images/k8s/pv.svg';
import pvc from '../../images/k8s/pvc.svg';
import quota from '../../images/k8s/quota.svg';
import rb from '../../images/k8s/rb.svg';
import role from '../../images/k8s/role.svg';
import rs from '../../images/k8s/rs.svg';
import sa from '../../images/k8s/sa.svg';
import sc from '../../images/k8s/sc.svg';
import secret from '../../images/k8s/secret.svg';
import sts from '../../images/k8s/sts.svg';
import svc from '../../images/k8s/svc.svg';
import user from '../../images/k8s/user.svg';
import vol from '../../images/k8s/vol.svg';

export {
  cRole,
  cm,
  crb,
  crd,
  cronjob,
  deploy,
  ds,
  ep,
  etcd,
  group,
  hpa,
  ing,
  job,
  limits,
  master,
  netpol,
  node,
  ns,
  pod,
  psp,
  pv,
  pvc,
  quota,
  rb,
  role,
  rs,
  sa,
  sc,
  secret,
  sts,
  svc,
  user,
  vol,
};
