// !!! DO NOT EDIT !!! -- automatically generated by scripts/assets.js

import cRole from 'url:../../images/k8s/c-role.svg';
import cm from 'url:../../images/k8s/cm.svg';
import controlPlane from 'url:../../images/k8s/control-plane.svg';
import crb from 'url:../../images/k8s/crb.svg';
import crd from 'url:../../images/k8s/crd.svg';
import cronjob from 'url:../../images/k8s/cronjob.svg';
import deploy from 'url:../../images/k8s/deploy.svg';
import ds from 'url:../../images/k8s/ds.svg';
import ep from 'url:../../images/k8s/ep.svg';
import etcd from 'url:../../images/k8s/etcd.svg';
import group from 'url:../../images/k8s/group.svg';
import hpa from 'url:../../images/k8s/hpa.svg';
import ing from 'url:../../images/k8s/ing.svg';
import job from 'url:../../images/k8s/job.svg';
import limits from 'url:../../images/k8s/limits.svg';
import netpol from 'url:../../images/k8s/netpol.svg';
import node from 'url:../../images/k8s/node.svg';
import ns from 'url:../../images/k8s/ns.svg';
import pod from 'url:../../images/k8s/pod.svg';
import psp from 'url:../../images/k8s/psp.svg';
import pv from 'url:../../images/k8s/pv.svg';
import pvc from 'url:../../images/k8s/pvc.svg';
import quota from 'url:../../images/k8s/quota.svg';
import rb from 'url:../../images/k8s/rb.svg';
import role from 'url:../../images/k8s/role.svg';
import rs from 'url:../../images/k8s/rs.svg';
import sa from 'url:../../images/k8s/sa.svg';
import sc from 'url:../../images/k8s/sc.svg';
import secret from 'url:../../images/k8s/secret.svg';
import sts from 'url:../../images/k8s/sts.svg';
import svc from 'url:../../images/k8s/svc.svg';
import user from 'url:../../images/k8s/user.svg';
import vol from 'url:../../images/k8s/vol.svg';

export {
  cRole,
  cm,
  controlPlane,
  crb,
  crd,
  cronjob,
  deploy,
  ds,
  ep,
  etcd,
  group,
  hpa,
  ing,
  job,
  limits,
  netpol,
  node,
  ns,
  pod,
  psp,
  pv,
  pvc,
  quota,
  rb,
  role,
  rs,
  sa,
  sc,
  secret,
  sts,
  svc,
  user,
  vol,
};
