// !!! DO NOT EDIT !!! -- automatically generated by scripts/assets.ts

const absMember = new URL('../../images/azure/abs-member.svg', import.meta.url);
const activeDirectory = new URL('../../images/azure/active-directory.svg', import.meta.url);
const activeDirectoryConnectHealth = new URL('../../images/azure/active-directory-connect-health.svg', import.meta.url);
const activityLog = new URL('../../images/azure/activity-log.svg', import.meta.url);
const adB2C = new URL('../../images/azure/ad-b2c.svg', import.meta.url);
const adDomainServices = new URL('../../images/azure/ad-domain-services.svg', import.meta.url);
const adRolesAndAdministrators = new URL('../../images/azure/ad-roles-and-administrators.svg', import.meta.url);
const advisor = new URL('../../images/azure/advisor.svg', import.meta.url);
const alerts = new URL('../../images/azure/alerts.svg', import.meta.url);
const allResources = new URL('../../images/azure/all-resources.svg', import.meta.url);
const analysisServices = new URL('../../images/azure/analysis-services.svg', import.meta.url);
const apiManagementServices = new URL('../../images/azure/api-management-services.svg', import.meta.url);
const appRegistrations = new URL('../../images/azure/app-registrations.svg', import.meta.url);
const appServiceCertificates = new URL('../../images/azure/app-service-certificates.svg', import.meta.url);
const appServiceDomains = new URL('../../images/azure/app-service-domains.svg', import.meta.url);
const appServiceEnvironments = new URL('../../images/azure/app-service-environments.svg', import.meta.url);
const appServicePlans = new URL('../../images/azure/app-service-plans.svg', import.meta.url);
const appServices = new URL('../../images/azure/app-services.svg', import.meta.url);
const applicationInsights = new URL('../../images/azure/application-insights.svg', import.meta.url);
const arc = new URL('../../images/azure/arc.svg', import.meta.url);
const automationAccounts = new URL('../../images/azure/automation-accounts.svg', import.meta.url);
const availabilitySets = new URL('../../images/azure/availability-sets.svg', import.meta.url);
const avs = new URL('../../images/azure/avs.svg', import.meta.url);
const backlog = new URL('../../images/azure/backlog.svg', import.meta.url);
const batchAccounts = new URL('../../images/azure/batch-accounts.svg', import.meta.url);
const bizTalk = new URL('../../images/azure/biz-talk.svg', import.meta.url);
const blobBlock = new URL('../../images/azure/blob-block.svg', import.meta.url);
const blobPage = new URL('../../images/azure/blob-page.svg', import.meta.url);
const blockchainService = new URL('../../images/azure/blockchain-service.svg', import.meta.url);
const blueprints = new URL('../../images/azure/blueprints.svg', import.meta.url);
const botServices = new URL('../../images/azure/bot-services.svg', import.meta.url);
const branch = new URL('../../images/azure/branch.svg', import.meta.url);
const browser = new URL('../../images/azure/browser.svg', import.meta.url);
const bug = new URL('../../images/azure/bug.svg', import.meta.url);
const builds = new URL('../../images/azure/builds.svg', import.meta.url);
const cache = new URL('../../images/azure/cache.svg', import.meta.url);
const cacheRedis = new URL('../../images/azure/cache-redis.svg', import.meta.url);
const capacity = new URL('../../images/azure/capacity.svg', import.meta.url);
const cdnProfiles = new URL('../../images/azure/cdn-profiles.svg', import.meta.url);
const cloudServicesClassic = new URL('../../images/azure/cloud-services-(classic).svg', import.meta.url);
const code = new URL('../../images/azure/code.svg', import.meta.url);
const cognitiveServices = new URL('../../images/azure/cognitive-services.svg', import.meta.url);
const commit = new URL('../../images/azure/commit.svg', import.meta.url);
const compliance = new URL('../../images/azure/compliance.svg', import.meta.url);
const consortium = new URL('../../images/azure/consortium.svg', import.meta.url);
const containerInstances = new URL('../../images/azure/container-instances.svg', import.meta.url);
const containerRegistries = new URL('../../images/azure/container-registries.svg', import.meta.url);
const containerServicesDeprecated = new URL('../../images/azure/container-services-(deprecated).svg', import.meta.url);
const controls = new URL('../../images/azure/controls.svg', import.meta.url);
const controlsHorizontal = new URL('../../images/azure/controls-horizontal.svg', import.meta.url);
const cosmosDb = new URL('../../images/azure/cosmos-db.svg', import.meta.url);
const costAlerts = new URL('../../images/azure/cost-alerts.svg', import.meta.url);
const costAnalysis = new URL('../../images/azure/cost-analysis.svg', import.meta.url);
const costBudgets = new URL('../../images/azure/cost-budgets.svg', import.meta.url);
const costManagement = new URL('../../images/azure/cost-management.svg', import.meta.url);
const counter = new URL('../../images/azure/counter.svg', import.meta.url);
const cubes = new URL('../../images/azure/cubes.svg', import.meta.url);
const dashboard = new URL('../../images/azure/dashboard.svg', import.meta.url);
const dataBox = new URL('../../images/azure/data-box.svg', import.meta.url);
const dataBoxEdge = new URL('../../images/azure/data-box-edge.svg', import.meta.url);
const dataCatalog = new URL('../../images/azure/data-catalog.svg', import.meta.url);
const dataExplorerClusters = new URL('../../images/azure/data-explorer-clusters.svg', import.meta.url);
const dataFactory = new URL('../../images/azure/data-factory.svg', import.meta.url);
const dataLakeStoreGen1 = new URL('../../images/azure/data-lake-store-gen1.svg', import.meta.url);
const databaseMariadbServer = new URL('../../images/azure/database-mariadb-server.svg', import.meta.url);
const databaseMigrationServices = new URL('../../images/azure/database-migration-services.svg', import.meta.url);
const databaseMysqlServer = new URL('../../images/azure/database-mysql-server.svg', import.meta.url);
const databasePostgresqlServer = new URL('../../images/azure/database-postgresql-server.svg', import.meta.url);
const ddosProtectionPlans = new URL('../../images/azure/ddos-protection-plans.svg', import.meta.url);
const devConsole = new URL('../../images/azure/dev-console.svg', import.meta.url);
const deviceProvisioningServices = new URL('../../images/azure/device-provisioning-services.svg', import.meta.url);
const deviceSecurityApple = new URL('../../images/azure/device-security-apple.svg', import.meta.url);
const deviceSecurityGoogle = new URL('../../images/azure/device-security-google.svg', import.meta.url);
const deviceSecurityWindows = new URL('../../images/azure/device-security-windows.svg', import.meta.url);
const devops = new URL('../../images/azure/devops.svg', import.meta.url);
const devtestLabs = new URL('../../images/azure/devtest-labs.svg', import.meta.url);
const diagnosticsSettings = new URL('../../images/azure/diagnostics-settings.svg', import.meta.url);
const digitalTwins = new URL('../../images/azure/digital-twins.svg', import.meta.url);
const diskEncryptionSets = new URL('../../images/azure/disk-encryption-sets.svg', import.meta.url);
const disks = new URL('../../images/azure/disks.svg', import.meta.url);
const disksClassic = new URL('../../images/azure/disks-(classic).svg', import.meta.url);
const disksSnapshots = new URL('../../images/azure/disks-snapshots.svg', import.meta.url);
const dnsZones = new URL('../../images/azure/dns-zones.svg', import.meta.url);
const download = new URL('../../images/azure/download.svg', import.meta.url);
const education = new URL('../../images/azure/education.svg', import.meta.url);
const elasticJobAgents = new URL('../../images/azure/elastic-job-agents.svg', import.meta.url);
const elixir = new URL('../../images/azure/elixir.svg', import.meta.url);
const elixirPurple = new URL('../../images/azure/elixir-purple.svg', import.meta.url);
const enterpriseApplications = new URL('../../images/azure/enterprise-applications.svg', import.meta.url);
const error = new URL('../../images/azure/error.svg', import.meta.url);
const eventGridDomains = new URL('../../images/azure/event-grid-domains.svg', import.meta.url);
const eventGridSubscriptions = new URL('../../images/azure/event-grid-subscriptions.svg', import.meta.url);
const eventGridTopics = new URL('../../images/azure/event-grid-topics.svg', import.meta.url);
const eventHubClusters = new URL('../../images/azure/event-hub-clusters.svg', import.meta.url);
const eventHubs = new URL('../../images/azure/event-hubs.svg', import.meta.url);
const extensions = new URL('../../images/azure/extensions.svg', import.meta.url);
const file = new URL('../../images/azure/file.svg', import.meta.url);
const files = new URL('../../images/azure/files.svg', import.meta.url);
const firewallManager = new URL('../../images/azure/firewall-manager.svg', import.meta.url);
const folderBlank = new URL('../../images/azure/folder-blank.svg', import.meta.url);
const folderWebsite = new URL('../../images/azure/folder-website.svg', import.meta.url);
const frontDoors = new URL('../../images/azure/front-doors.svg', import.meta.url);
const ftp = new URL('../../images/azure/ftp.svg', import.meta.url);
const functionApps = new URL('../../images/azure/function-apps.svg', import.meta.url);
const gear = new URL('../../images/azure/gear.svg', import.meta.url);
const globe = new URL('../../images/azure/globe.svg', import.meta.url);
const globeError = new URL('../../images/azure/globe-error.svg', import.meta.url);
const globeSuccess = new URL('../../images/azure/globe-success.svg', import.meta.url);
const globeWarning = new URL('../../images/azure/globe-warning.svg', import.meta.url);
const groups = new URL('../../images/azure/groups.svg', import.meta.url);
const guide = new URL('../../images/azure/guide.svg', import.meta.url);
const hdInsightClusters = new URL('../../images/azure/hd-insight-clusters.svg', import.meta.url);
const heart = new URL('../../images/azure/heart.svg', import.meta.url);
const helpAndSupport = new URL('../../images/azure/help-and-support.svg', import.meta.url);
const identityGovernance = new URL('../../images/azure/identity-governance.svg', import.meta.url);
const image = new URL('../../images/azure/image.svg', import.meta.url);
const imageDefinitions = new URL('../../images/azure/image-definitions.svg', import.meta.url);
const imageVersions = new URL('../../images/azure/image-versions.svg', import.meta.url);
const images = new URL('../../images/azure/images.svg', import.meta.url);
const information = new URL('../../images/azure/information.svg', import.meta.url);
const infrastructureBackup = new URL('../../images/azure/infrastructure-backup.svg', import.meta.url);
const inputOutput = new URL('../../images/azure/input-output.svg', import.meta.url);
const instancePools = new URL('../../images/azure/instance-pools.svg', import.meta.url);
const integrationAccounts = new URL('../../images/azure/integration-accounts.svg', import.meta.url);
const iotCentralApplications = new URL('../../images/azure/iot-central-applications.svg', import.meta.url);
const iotHub = new URL('../../images/azure/iot-hub.svg', import.meta.url);
const ipGroups = new URL('../../images/azure/ip-groups.svg', import.meta.url);
const journeyHub = new URL('../../images/azure/journey-hub.svg', import.meta.url);
const kubernetesServices = new URL('../../images/azure/kubernetes-services.svg', import.meta.url);
const labServices = new URL('../../images/azure/lab-services.svg', import.meta.url);
const launchPortal = new URL('../../images/azure/launch-portal.svg', import.meta.url);
const learn = new URL('../../images/azure/learn.svg', import.meta.url);
const lighthouse = new URL('../../images/azure/lighthouse.svg', import.meta.url);
const loadBalancers = new URL('../../images/azure/load-balancers.svg', import.meta.url);
const loadTest = new URL('../../images/azure/load-test.svg', import.meta.url);
const location = new URL('../../images/azure/location.svg', import.meta.url);
const logAnalyticsWorkspaces = new URL('../../images/azure/log-analytics-workspaces.svg', import.meta.url);
const logStreaming = new URL('../../images/azure/log-streaming.svg', import.meta.url);
const logicApps = new URL('../../images/azure/logic-apps.svg', import.meta.url);
const machinesAzureArc = new URL('../../images/azure/machines-azure-arc.svg', import.meta.url);
const managedApplicationsCenter = new URL('../../images/azure/managed-applications-center.svg', import.meta.url);
const managedDatabase = new URL('../../images/azure/managed-database.svg', import.meta.url);
const managementGroups = new URL('../../images/azure/management-groups.svg', import.meta.url);
const managementPortal = new URL('../../images/azure/management-portal.svg', import.meta.url);
const mapsAccounts = new URL('../../images/azure/maps-accounts.svg', import.meta.url);
const marketplace = new URL('../../images/azure/marketplace.svg', import.meta.url);
const media = new URL('../../images/azure/media.svg', import.meta.url);
const mediaFile = new URL('../../images/azure/media-file.svg', import.meta.url);
const meshApplications = new URL('../../images/azure/mesh-applications.svg', import.meta.url);
const metrics = new URL('../../images/azure/metrics.svg', import.meta.url);
const migrate = new URL('../../images/azure/migrate.svg', import.meta.url);
const mobile = new URL('../../images/azure/mobile.svg', import.meta.url);
const mobileEngagement = new URL('../../images/azure/mobile-engagement.svg', import.meta.url);
const module = new URL('../../images/azure/module.svg', import.meta.url);
const monitor = new URL('../../images/azure/monitor.svg', import.meta.url);
const multiTenancy = new URL('../../images/azure/multi-tenancy.svg', import.meta.url);
const myCustomers = new URL('../../images/azure/my-customers.svg', import.meta.url);
const networkSecurityGroups = new URL('../../images/azure/network-security-groups.svg', import.meta.url);
const networkWatcher = new URL('../../images/azure/network-watcher.svg', import.meta.url);
const notificationHubs = new URL('../../images/azure/notification-hubs.svg', import.meta.url);
const offers = new URL('../../images/azure/offers.svg', import.meta.url);
const operationLogClassic = new URL('../../images/azure/operation-log-(classic).svg', import.meta.url);
const osImagesClassic = new URL('../../images/azure/os-images-(classic).svg', import.meta.url);
const outboundConnection = new URL('../../images/azure/outbound-connection.svg', import.meta.url);
const plans = new URL('../../images/azure/plans.svg', import.meta.url);
const policy = new URL('../../images/azure/policy.svg', import.meta.url);
const power = new URL('../../images/azure/power.svg', import.meta.url);
const powerUp = new URL('../../images/azure/power-up.svg', import.meta.url);
const powershell = new URL('../../images/azure/powershell.svg', import.meta.url);
const preview = new URL('../../images/azure/preview.svg', import.meta.url);
const privateLink = new URL('../../images/azure/private-link.svg', import.meta.url);
const privateLinkService = new URL('../../images/azure/private-link-service.svg', import.meta.url);
const processExplorer = new URL('../../images/azure/process-explorer.svg', import.meta.url);
const productionReadyDatabase = new URL('../../images/azure/production-ready-database.svg', import.meta.url);
const publicIpAddresses = new URL('../../images/azure/public-ip-addresses.svg', import.meta.url);
const publicIpAddressesClassic = new URL('../../images/azure/public-ip-addresses-(classic).svg', import.meta.url);
const quickstartCenter = new URL('../../images/azure/quickstart-center.svg', import.meta.url);
const recent = new URL('../../images/azure/recent.svg', import.meta.url);
const recoveryServicesVaults = new URL('../../images/azure/recovery-services-vaults.svg', import.meta.url);
const relays = new URL('../../images/azure/relays.svg', import.meta.url);
const remoteRendering = new URL('../../images/azure/remote-rendering.svg', import.meta.url);
const reservations = new URL('../../images/azure/reservations.svg', import.meta.url);
const resourceGraphExplorer = new URL('../../images/azure/resource-graph-explorer.svg', import.meta.url);
const resourceGroupList = new URL('../../images/azure/resource-group-list.svg', import.meta.url);
const resourceGroups = new URL('../../images/azure/resource-groups.svg', import.meta.url);
const resourceLinked = new URL('../../images/azure/resource-linked.svg', import.meta.url);
const routeFilters = new URL('../../images/azure/route-filters.svg', import.meta.url);
const sapAzureMonitor = new URL('../../images/azure/sap-azure-monitor.svg', import.meta.url);
const scale = new URL('../../images/azure/scale.svg', import.meta.url);
const scheduler = new URL('../../images/azure/scheduler.svg', import.meta.url);
const search = new URL('../../images/azure/search.svg', import.meta.url);
const searchGrid = new URL('../../images/azure/search-grid.svg', import.meta.url);
const searchServices = new URL('../../images/azure/search-services.svg', import.meta.url);
const serverFarm = new URL('../../images/azure/server-farm.svg', import.meta.url);
const serviceBus = new URL('../../images/azure/service-bus.svg', import.meta.url);
const serviceFabricClusters = new URL('../../images/azure/service-fabric-clusters.svg', import.meta.url);
const serviceHealth = new URL('../../images/azure/service-health.svg', import.meta.url);
const serviceProviders = new URL('../../images/azure/service-providers.svg', import.meta.url);
const sharedImageGalleries = new URL('../../images/azure/shared-image-galleries.svg', import.meta.url);
const softwareAsAService = new URL('../../images/azure/software-as-a-service.svg', import.meta.url);
const solutions = new URL('../../images/azure/solutions.svg', import.meta.url);
const sqlDataWarehouses = new URL('../../images/azure/sql-data-warehouses.svg', import.meta.url);
const sqlDatabase = new URL('../../images/azure/sql-database.svg', import.meta.url);
const sqlElasticPools = new URL('../../images/azure/sql-elastic-pools.svg', import.meta.url);
const sqlManagedInstance = new URL('../../images/azure/sql-managed-instance.svg', import.meta.url);
const sqlServer = new URL('../../images/azure/sql-server.svg', import.meta.url);
const sqlServerStretchDatabases = new URL('../../images/azure/sql-server-stretch-databases.svg', import.meta.url);
const sqlVm = new URL('../../images/azure/sql-vm.svg', import.meta.url);
const ssd = new URL('../../images/azure/ssd.svg', import.meta.url);
const stack = new URL('../../images/azure/stack.svg', import.meta.url);
const storageAzureFiles = new URL('../../images/azure/storage-azure-files.svg', import.meta.url);
const storageContainer = new URL('../../images/azure/storage-container.svg', import.meta.url);
const storageQueue = new URL('../../images/azure/storage-queue.svg', import.meta.url);
const streamAnalyticsJobs = new URL('../../images/azure/stream-analytics-jobs.svg', import.meta.url);
const subscriptions = new URL('../../images/azure/subscriptions.svg', import.meta.url);
const synapseAnalytics = new URL('../../images/azure/synapse-analytics.svg', import.meta.url);
const table = new URL('../../images/azure/table.svg', import.meta.url);
const tags = new URL('../../images/azure/tags.svg', import.meta.url);
const tfsVcRepository = new URL('../../images/azure/tfs-vc-repository.svg', import.meta.url);
const timeSeriesInsightsEnvironments = new URL(
  '../../images/azure/time-series-insights-environments.svg',
  import.meta.url
);
const timeSeriesInsightsEventSources = new URL(
  '../../images/azure/time-series-insights-event-sources.svg',
  import.meta.url
);
const tokenService = new URL('../../images/azure/token-service.svg', import.meta.url);
const toolbox = new URL('../../images/azure/toolbox.svg', import.meta.url);
const trafficManagerProfiles = new URL('../../images/azure/traffic-manager-profiles.svg', import.meta.url);
const updates = new URL('../../images/azure/updates.svg', import.meta.url);
const userPrivacy = new URL('../../images/azure/user-privacy.svg', import.meta.url);
const userSubscriptions = new URL('../../images/azure/user-subscriptions.svg', import.meta.url);
const users = new URL('../../images/azure/users.svg', import.meta.url);
const versions = new URL('../../images/azure/versions.svg', import.meta.url);
const virtualClusters = new URL('../../images/azure/virtual-clusters.svg', import.meta.url);
const virtualMachine = new URL('../../images/azure/virtual-machine.svg', import.meta.url);
const virtualMachinesClassic = new URL('../../images/azure/virtual-machines-(classic).svg', import.meta.url);
const virtualNetworkGateways = new URL('../../images/azure/virtual-network-gateways.svg', import.meta.url);
const virtualNetworks = new URL('../../images/azure/virtual-networks.svg', import.meta.url);
const vmImagesClassic = new URL('../../images/azure/vm-images-(classic).svg', import.meta.url);
const vmScaleSets = new URL('../../images/azure/vm-scale-sets.svg', import.meta.url);
const webSlots = new URL('../../images/azure/web-slots.svg', import.meta.url);
const webTest = new URL('../../images/azure/web-test.svg', import.meta.url);
const websitePower = new URL('../../images/azure/website-power.svg', import.meta.url);
const websiteStaging = new URL('../../images/azure/website-staging.svg', import.meta.url);
const workbooks = new URL('../../images/azure/workbooks.svg', import.meta.url);
const workflow = new URL('../../images/azure/workflow.svg', import.meta.url);
const workspaces = new URL('../../images/azure/workspaces.svg', import.meta.url);

export {
  absMember,
  activeDirectory,
  activeDirectoryConnectHealth,
  activityLog,
  adB2C,
  adDomainServices,
  adRolesAndAdministrators,
  advisor,
  alerts,
  allResources,
  analysisServices,
  apiManagementServices,
  appRegistrations,
  appServiceCertificates,
  appServiceDomains,
  appServiceEnvironments,
  appServicePlans,
  appServices,
  applicationInsights,
  arc,
  automationAccounts,
  availabilitySets,
  avs,
  backlog,
  batchAccounts,
  bizTalk,
  blobBlock,
  blobPage,
  blockchainService,
  blueprints,
  botServices,
  branch,
  browser,
  bug,
  builds,
  cache,
  cacheRedis,
  capacity,
  cdnProfiles,
  cloudServicesClassic,
  code,
  cognitiveServices,
  commit,
  compliance,
  consortium,
  containerInstances,
  containerRegistries,
  containerServicesDeprecated,
  controls,
  controlsHorizontal,
  cosmosDb,
  costAlerts,
  costAnalysis,
  costBudgets,
  costManagement,
  counter,
  cubes,
  dashboard,
  dataBox,
  dataBoxEdge,
  dataCatalog,
  dataExplorerClusters,
  dataFactory,
  dataLakeStoreGen1,
  databaseMariadbServer,
  databaseMigrationServices,
  databaseMysqlServer,
  databasePostgresqlServer,
  ddosProtectionPlans,
  devConsole,
  deviceProvisioningServices,
  deviceSecurityApple,
  deviceSecurityGoogle,
  deviceSecurityWindows,
  devops,
  devtestLabs,
  diagnosticsSettings,
  digitalTwins,
  diskEncryptionSets,
  disks,
  disksClassic,
  disksSnapshots,
  dnsZones,
  download,
  education,
  elasticJobAgents,
  elixir,
  elixirPurple,
  enterpriseApplications,
  error,
  eventGridDomains,
  eventGridSubscriptions,
  eventGridTopics,
  eventHubClusters,
  eventHubs,
  extensions,
  file,
  files,
  firewallManager,
  folderBlank,
  folderWebsite,
  frontDoors,
  ftp,
  functionApps,
  gear,
  globe,
  globeError,
  globeSuccess,
  globeWarning,
  groups,
  guide,
  hdInsightClusters,
  heart,
  helpAndSupport,
  identityGovernance,
  image,
  imageDefinitions,
  imageVersions,
  images,
  information,
  infrastructureBackup,
  inputOutput,
  instancePools,
  integrationAccounts,
  iotCentralApplications,
  iotHub,
  ipGroups,
  journeyHub,
  kubernetesServices,
  labServices,
  launchPortal,
  learn,
  lighthouse,
  loadBalancers,
  loadTest,
  location,
  logAnalyticsWorkspaces,
  logStreaming,
  logicApps,
  machinesAzureArc,
  managedApplicationsCenter,
  managedDatabase,
  managementGroups,
  managementPortal,
  mapsAccounts,
  marketplace,
  media,
  mediaFile,
  meshApplications,
  metrics,
  migrate,
  mobile,
  mobileEngagement,
  module,
  monitor,
  multiTenancy,
  myCustomers,
  networkSecurityGroups,
  networkWatcher,
  notificationHubs,
  offers,
  operationLogClassic,
  osImagesClassic,
  outboundConnection,
  plans,
  policy,
  power,
  powerUp,
  powershell,
  preview,
  privateLink,
  privateLinkService,
  processExplorer,
  productionReadyDatabase,
  publicIpAddresses,
  publicIpAddressesClassic,
  quickstartCenter,
  recent,
  recoveryServicesVaults,
  relays,
  remoteRendering,
  reservations,
  resourceGraphExplorer,
  resourceGroupList,
  resourceGroups,
  resourceLinked,
  routeFilters,
  sapAzureMonitor,
  scale,
  scheduler,
  search,
  searchGrid,
  searchServices,
  serverFarm,
  serviceBus,
  serviceFabricClusters,
  serviceHealth,
  serviceProviders,
  sharedImageGalleries,
  softwareAsAService,
  solutions,
  sqlDataWarehouses,
  sqlDatabase,
  sqlElasticPools,
  sqlManagedInstance,
  sqlServer,
  sqlServerStretchDatabases,
  sqlVm,
  ssd,
  stack,
  storageAzureFiles,
  storageContainer,
  storageQueue,
  streamAnalyticsJobs,
  subscriptions,
  synapseAnalytics,
  table,
  tags,
  tfsVcRepository,
  timeSeriesInsightsEnvironments,
  timeSeriesInsightsEventSources,
  tokenService,
  toolbox,
  trafficManagerProfiles,
  updates,
  userPrivacy,
  userSubscriptions,
  users,
  versions,
  virtualClusters,
  virtualMachine,
  virtualMachinesClassic,
  virtualNetworkGateways,
  virtualNetworks,
  vmImagesClassic,
  vmScaleSets,
  webSlots,
  webTest,
  websitePower,
  websiteStaging,
  workbooks,
  workflow,
  workspaces,
};
