// !!! DO NOT EDIT !!! -- automatically generated by scripts/assets.ts

const cloudRun = new URL('../../images/gcp/cloud-run.svg', import.meta.url);
const dataCatalog = new URL('../../images/gcp/data-catalog.svg', import.meta.url);
const firestore = new URL('../../images/gcp/firestore.svg', import.meta.url);
const gke = new URL('../../images/gcp/gke.svg', import.meta.url);

export {cloudRun, dataCatalog, firestore, gke};
