// !!! DO NOT EDIT !!! -- automatically generated by scripts/assets.ts

const browser = new URL('../../images/generic/browser.svg', import.meta.url);
const cassandra = new URL('../../images/generic/cassandra.svg', import.meta.url);
const component = new URL('../../images/generic/component.svg', import.meta.url);
const consul = new URL('../../images/generic/consul.svg', import.meta.url);
const elasticsearch = new URL('../../images/generic/elasticsearch.svg', import.meta.url);
const firebase = new URL('../../images/generic/firebase.svg', import.meta.url);
const kafka = new URL('../../images/generic/kafka.svg', import.meta.url);
const mariadb = new URL('../../images/generic/mariadb.svg', import.meta.url);
const mongodb = new URL('../../images/generic/mongodb.svg', import.meta.url);
const mysql = new URL('../../images/generic/mysql.svg', import.meta.url);
const nomad = new URL('../../images/generic/nomad.svg', import.meta.url);
const postgres = new URL('../../images/generic/postgres.svg', import.meta.url);
const user = new URL('../../images/generic/user.svg', import.meta.url);
const users = new URL('../../images/generic/users.svg', import.meta.url);
const vault = new URL('../../images/generic/vault.svg', import.meta.url);

export {
  browser,
  cassandra,
  component,
  consul,
  elasticsearch,
  firebase,
  kafka,
  mariadb,
  mongodb,
  mysql,
  nomad,
  postgres,
  user,
  users,
  vault,
};
