// !!! DO NOT EDIT !!! -- automatically generated by scripts/assets.ts

const cRole = new URL('../../images/k8s/c-role.svg', import.meta.url);
const cm = new URL('../../images/k8s/cm.svg', import.meta.url);
const controlPlane = new URL('../../images/k8s/control-plane.svg', import.meta.url);
const crb = new URL('../../images/k8s/crb.svg', import.meta.url);
const crd = new URL('../../images/k8s/crd.svg', import.meta.url);
const cronjob = new URL('../../images/k8s/cronjob.svg', import.meta.url);
const deploy = new URL('../../images/k8s/deploy.svg', import.meta.url);
const ds = new URL('../../images/k8s/ds.svg', import.meta.url);
const ep = new URL('../../images/k8s/ep.svg', import.meta.url);
const etcd = new URL('../../images/k8s/etcd.svg', import.meta.url);
const group = new URL('../../images/k8s/group.svg', import.meta.url);
const hpa = new URL('../../images/k8s/hpa.svg', import.meta.url);
const ing = new URL('../../images/k8s/ing.svg', import.meta.url);
const job = new URL('../../images/k8s/job.svg', import.meta.url);
const limits = new URL('../../images/k8s/limits.svg', import.meta.url);
const netpol = new URL('../../images/k8s/netpol.svg', import.meta.url);
const node = new URL('../../images/k8s/node.svg', import.meta.url);
const ns = new URL('../../images/k8s/ns.svg', import.meta.url);
const pod = new URL('../../images/k8s/pod.svg', import.meta.url);
const psp = new URL('../../images/k8s/psp.svg', import.meta.url);
const pv = new URL('../../images/k8s/pv.svg', import.meta.url);
const pvc = new URL('../../images/k8s/pvc.svg', import.meta.url);
const quota = new URL('../../images/k8s/quota.svg', import.meta.url);
const rb = new URL('../../images/k8s/rb.svg', import.meta.url);
const role = new URL('../../images/k8s/role.svg', import.meta.url);
const rs = new URL('../../images/k8s/rs.svg', import.meta.url);
const sa = new URL('../../images/k8s/sa.svg', import.meta.url);
const sc = new URL('../../images/k8s/sc.svg', import.meta.url);
const secret = new URL('../../images/k8s/secret.svg', import.meta.url);
const sts = new URL('../../images/k8s/sts.svg', import.meta.url);
const svc = new URL('../../images/k8s/svc.svg', import.meta.url);
const user = new URL('../../images/k8s/user.svg', import.meta.url);
const vol = new URL('../../images/k8s/vol.svg', import.meta.url);

export {
  cRole,
  cm,
  controlPlane,
  crb,
  crd,
  cronjob,
  deploy,
  ds,
  ep,
  etcd,
  group,
  hpa,
  ing,
  job,
  limits,
  netpol,
  node,
  ns,
  pod,
  psp,
  pv,
  pvc,
  quota,
  rb,
  role,
  rs,
  sa,
  sc,
  secret,
  sts,
  svc,
  user,
  vol,
};
